// Otros nombres con los que la gente busca los alimentos de la base (marcas, formas, sinónimos).
// Sirven para dos cosas: que el buscador encuentre "Fideos secos" al escribir "spaghetti", y para
// proponer por qué alimento de las recetas vale un producto ("Tirabuzón Matarazzo" cuenta como fideos).
// Van por slug, en minúscula y sin tildes.
export const ALIAS = {
  fideos: ['fideo', 'spaghetti', 'espagueti', 'tallarin', 'tirabuzon', 'mostachol', 'moño', 'codito', 'penne', 'fusilli', 'rigatoni', 'macarron', 'cabello de angel', 'dedalito', 'municion', 'pasta seca'],
  polenta: ['presto pronta', 'polenta instantanea', 'harina de maiz'],
  'pure-tomate': ['pulpa de tomate', 'pure tomate'],
  'salsa-tomate': ['pomarola', 'filetto', 'salsa lista', 'tuco', 'salsa portuguesa', 'salsa de tomate'],
  'tomate-triturado': ['tomate perita', 'tomate cubeteado', 'tomate triturado'],
  caldo: ['caldito', 'caldo de verdura', 'caldo de gallina', 'caldo de carne', 'caldo en polvo'],
  lentejas: ['lenteja', 'lentejon'],
  jardinera: ['macedonia de verduras', 'ensalada jardinera'],
  aceite: ['aceite de girasol', 'aceite mezcla', 'aceite de maiz'],
  'aceite-oliva': ['oliva extra virgen'],
  leche: ['leche liviana', 'leche semidescremada'],
  'leche-descremada': ['leche cero', 'leche 0%'],
  'queso-rallado': ['reggianito rallado', 'parmesano rallado', 'queso en hebras'],
  'queso-cremoso': ['cuartirolo', 'queso fresco'],
  'queso-tybo': ['queso barra', 'queso de maquina', 'queso danbo', 'queso en fetas'],
  muzzarella: ['mozzarella', 'mozarela', 'muzarela', 'musarela'],
  'queso-untable-clasico': ['casancrem', 'finlandia', 'mendicrim', 'queso crema'],
  manteca: ['mantequilla'],
  'pan-integral': ['pan de salvado', 'pan integral'],
  'pan-lactal-blanco': ['pan de molde', 'pan lactal', 'pan blanco'],
  'galletita-agua': ['galletitas de agua', 'crackers', 'criollitas', 'traviata', 'express', 'mediatarde'],
  'galletita-salvado': ['galletitas de salvado', 'cerealitas'],
  'galletita-dulce': ['galletitas maria', 'lincoln', 'galletitas dulces', 'galletitas de vainilla'],
  'galletita-rellena': ['oreo', 'pepitos', 'melba', 'sonrisas', 'galletitas rellenas'],
  'galleta-arroz': ['galletitas de arroz', 'tostadas de arroz'],
  'tostadas-mesa': ['tostadas', 'riera'],
  arvejas: ['arveja', 'guisantes'],
  choclo: ['choclo en grano', 'choclo cremoso', 'maiz dulce'],
  'atun-natural': ['atun en agua', 'lomitos de atun', 'atun'],
  mostaza: ['savora'],
  ketchup: ['catsup'],
  'cafe-polvo': ['cafe soluble', 'nescafe', 'dolca', 'cafe instantaneo'],
  yerba: ['yerba mate'],
  saquitos: ['te en saquitos', 'mate cocido en saquitos', 'saquitos de te'],
  'mani-pelado': ['mani salado', 'mani tostado', 'mani'],
  salchicha: ['salchichas', 'vienisima', 'viena'],
  'hamburguesa-carne': ['paty', 'medallon de carne'],
  'milanesa-pollo': ['suprema rebozada', 'milanesa de pollo'],
  nuggets: ['patitas de pollo', 'bocaditos de pollo'],
  harina: ['harina 000', 'harina 0000', 'harina leudante'],
  maicena: ['maizena', 'almidon de maiz'],
  'pan-rallado': ['rebozador'],
  'pure-instantaneo': ['pure instantaneo', 'pure de papas'],
  cacao: ['nesquik', 'toddy', 'zucoa'],
  vinagre: ['vinagre de alcohol', 'vinagre de manzana', 'vinagre de vino'],
  'copos-maiz': ['corn flakes', 'copos de maiz'],
  'cereal-azucarado': ['zucaritas', 'chocapic', 'froot loops'],
  avena: ['avena arrollada', 'avena instantanea', 'quaker'],
  gaseosa: ['coca cola', 'pepsi', 'sprite', 'fanta', 'seven up', 'coca'],
  'gaseosa-zero': ['coca zero', 'coca light', 'sprite zero', 'pepsi black', 'gaseosa light'],
  'jugo-polvo': ['tang', 'clight', 'jugo en polvo'],
  'agua-saborizada': ['levite', 'aquarius'],
  isotonica: ['gatorade', 'powerade'],
  energizante: ['speed', 'red bull', 'monster'],
  chocolatada: ['cindor', 'chocolatada'],
  'papas-paquete': ['lays', 'pringles', 'papas de paquete'],
  chizitos: ['cheetos'],
  'proteina-polvo': ['whey', 'proteina de suero'],
  'barrita-cereal': ['barra de cereal', 'cereal mix'],
  'postre-mani': ['mantecol'],
  'postre-lacteo': ['serenito', 'danette', 'sublime'],
  'dulce-membrillo': ['dulce de batata', 'dulce de membrillo', 'membrillo'],
  'yogur-proteico': ['yogur proteico', 'ser pro', 'yogur con proteina'],
  'hamburguesa': ['hamburguesa de local', 'combo de hamburguesa'],
}

// Alimentos de la base que valen por otro de la base en las recetas, sin que haya que vincularlos:
// si la receta pide leche y en la despensa hay leche entera, alcanza. De izquierda (lo que hay) a derecha (lo que piden).
// Solo van los que se reemplazan uno por uno en peso; lo seco contra lo de lata o lo crudo contra lo cocido, no.
export const FAMILIA = {
  'leche-entera': 'leche',
  'leche-descremada': 'leche',
  'fideos-integrales': 'fideos',
  'arroz-integral': 'arroz',
  'aceite-oliva': 'aceite',
  'atun-aceite': 'atun-natural',
  'pan-lactal-blanco': 'pan-integral',
  'queso-untable-clasico': 'queso-untable',
  mayonesa: 'mayonesa-light',
  mermelada: 'mermelada-light',
  'yogur-descremado': 'yogur-natural',
  'yogur-griego': 'yogur-natural',
  'tomate-triturado': 'pure-tomate',
  'queso-port-salut': 'queso-cremoso',
}
