-- Tupper, actualización 6: categorías por góndola, más alimentos y más recetas en la base.
-- Ya está aplicada en el proyecto de Supabase. Para recrear la base desde cero el orden es:
-- schema.sql, actualizacion-2.sql a actualizacion-6.sql y seed.sql.
-- No borra nada: cambia la categoría de los alimentos y agrega filas nuevas.

-- 1. Los alimentos de la base pasan a las categorías nuevas
update public.foods f set category = v.category
from (values
  ('pata-muslo', 'Carnes y huevos'),
  ('pechuga-pollo', 'Carnes y huevos'),
  ('milanesa-pollo', 'Carnes y huevos'),
  ('atun-natural', 'Pescados'),
  ('huevo', 'Carnes y huevos'),
  ('carne-magra', 'Carnes y huevos'),
  ('carne-picada', 'Carnes y huevos'),
  ('lentejas', 'Legumbres'),
  ('jamon-cocido', 'Carnes y huevos'),
  ('merluza', 'Pescados'),
  ('arroz', 'Pastas y arroz'),
  ('fideos', 'Pastas y arroz'),
  ('avena', 'Cereales'),
  ('pan-integral', 'Panadería'),
  ('pan-frances', 'Panadería'),
  ('papa', 'Verduras'),
  ('batata', 'Verduras'),
  ('copos-maiz', 'Cereales'),
  ('rapidita', 'Panadería'),
  ('lechuga', 'Verduras'),
  ('tomate', 'Verduras'),
  ('cebolla', 'Verduras'),
  ('morron', 'Verduras'),
  ('calabaza', 'Verduras'),
  ('zapallito', 'Verduras'),
  ('zanahoria', 'Verduras'),
  ('banana', 'Frutas'),
  ('manzana', 'Frutas'),
  ('mandarina', 'Frutas'),
  ('naranja', 'Frutas'),
  ('leche', 'Lácteos'),
  ('leche-entera', 'Lácteos'),
  ('yogur-natural', 'Lácteos'),
  ('queso-cremoso', 'Lácteos'),
  ('queso-rallado', 'Lácteos'),
  ('queso-untable', 'Lácteos'),
  ('manteca', 'Lácteos'),
  ('dulce-de-leche', 'Despensa'),
  ('pure-tomate', 'Salsas y aderezos'),
  ('salsa-bolonesa', 'Salsas y aderezos'),
  ('arvejas', 'Enlatados'),
  ('choclo', 'Enlatados'),
  ('aceite', 'Despensa'),
  ('caldo', 'Despensa'),
  ('azucar', 'Despensa'),
  ('miel', 'Despensa'),
  ('mayonesa', 'Salsas y aderezos'),
  ('mostaza', 'Salsas y aderezos'),
  ('mani-cascara', 'Snacks y dulces'),
  ('mani-pelado', 'Snacks y dulces'),
  ('criollo', 'Panadería'),
  ('galletita-rellena', 'Snacks y dulces'),
  ('galletita-agua', 'Panadería'),
  ('alfajor', 'Snacks y dulces'),
  ('medialuna', 'Panadería'),
  ('chocolate', 'Snacks y dulces'),
  ('helado', 'Congelados'),
  ('lomito', 'Comidas hechas'),
  ('hamburguesa', 'Comidas hechas'),
  ('papas-fritas', 'Comidas hechas'),
  ('pizza', 'Comidas hechas'),
  ('empanada', 'Comidas hechas'),
  ('mate', 'Bebidas'),
  ('gaseosa', 'Bebidas'),
  ('gaseosa-zero', 'Bebidas'),
  ('jugo-naranja', 'Bebidas'),
  ('cerveza', 'Bebidas'),
  ('fernet-coca', 'Bebidas'),
  ('vino', 'Bebidas'),
  ('agua', 'Bebidas'),
  ('soda', 'Bebidas'),
  ('agua-saborizada', 'Bebidas'),
  ('agua-saborizada-zero', 'Bebidas'),
  ('tonica', 'Bebidas'),
  ('jugo-polvo', 'Bebidas'),
  ('jugo-caja', 'Bebidas'),
  ('limonada', 'Bebidas'),
  ('isotonica', 'Bebidas'),
  ('energizante', 'Bebidas'),
  ('energizante-zero', 'Bebidas'),
  ('cafe-con-leche', 'Bebidas'),
  ('chocolatada', 'Bebidas'),
  ('licuado-banana', 'Bebidas'),
  ('yogur-bebible', 'Bebidas'),
  ('cerveza-negra', 'Bebidas'),
  ('cerveza-ipa', 'Bebidas'),
  ('cerveza-sin-alcohol', 'Bebidas'),
  ('vino-blanco', 'Bebidas'),
  ('espumante', 'Bebidas'),
  ('sidra', 'Bebidas'),
  ('fernet', 'Bebidas'),
  ('bebida-blanca', 'Bebidas'),
  ('gin-tonic', 'Bebidas'),
  ('ron-cola', 'Bebidas'),
  ('campari', 'Bebidas'),
  ('aperol-spritz', 'Bebidas'),
  ('vermut', 'Bebidas'),
  ('trago-dulce', 'Bebidas'),
  ('licor', 'Bebidas'),
  ('pechuga-cruda', 'Carnes y huevos'),
  ('carne-picada-cruda', 'Carnes y huevos'),
  ('bife-nalga', 'Carnes y huevos'),
  ('milanesa-carne', 'Carnes y huevos'),
  ('filet-merluza', 'Pescados'),
  ('garbanzos', 'Enlatados'),
  ('milanesa-soja', 'Congelados'),
  ('polenta', 'Pastas y arroz'),
  ('tapa-tarta', 'Panadería'),
  ('galleta-arroz', 'Panadería'),
  ('pan-rallado', 'Panadería'),
  ('palta', 'Verduras'),
  ('acelga', 'Verduras'),
  ('brocoli', 'Verduras'),
  ('pera', 'Frutas'),
  ('durazno', 'Frutas'),
  ('frutilla', 'Frutas'),
  ('uva', 'Frutas'),
  ('queso-port-salut', 'Lácteos'),
  ('ricota', 'Lácteos'),
  ('crema', 'Lácteos'),
  ('yogur-saborizado', 'Lácteos'),
  ('salsa-soja', 'Salsas y aderezos'),
  ('mermelada', 'Despensa'),
  ('mermelada-light', 'Despensa'),
  ('cacao', 'Despensa'),
  ('aceitunas', 'Enlatados'),
  ('ketchup', 'Salsas y aderezos'),
  ('nueces', 'Snacks y dulces'),
  ('almendras', 'Snacks y dulces'),
  ('barrita-cereal', 'Snacks y dulces'),
  ('turron', 'Snacks y dulces'),
  ('papas-paquete', 'Snacks y dulces'),
  ('sandwich-miga', 'Comidas hechas'),
  ('pancho', 'Comidas hechas'),
  ('choripan', 'Comidas hechas'),
  ('asado', 'Comidas hechas'),
  ('tarta-porcion', 'Comidas hechas'),
  ('sushi', 'Comidas hechas'),
  ('wrap-comprado', 'Comidas hechas'),
  ('terere', 'Bebidas'),
  ('terere-jugo', 'Bebidas'),
  ('mate-cocido', 'Bebidas'),
  ('mate-cocido-leche', 'Bebidas'),
  ('cafe', 'Bebidas'),
  ('cortado', 'Bebidas'),
  ('capuchino', 'Bebidas'),
  ('te', 'Bebidas'),
  ('te-leche', 'Bebidas')
) as v(slug, category)
where f.slug = v.slug and f.owner is null and f.category is distinct from v.category;

-- 2. Los alimentos propios que tenían una categoría que ya no existe
update public.foods set category = case category when 'Proteínas' then 'Carnes y huevos' when 'Carbohidratos' then 'Pastas y arroz' else 'Snacks y dulces' end
where owner is not null and category in ('Proteínas', 'Carbohidratos', 'Snacks');

-- 3. Los alimentos y las recetas nuevos están en seed.sql: se ejecuta de nuevo y agrega solo lo que falta.
