-- Datos base de Tupper (alimentos y recetas comunes). Generado con scripts/gen-seed.mjs

insert into public.foods (slug, name, unit, unit_grams, unit_label, kcal, protein, carbs, fat, category, alcohol) values
  ('pata-muslo', 'Pata muslo (sin piel)', 'u', 150, 'pieza', 185, 25, 0, 9, 'Carnes y huevos', false),
  ('pechuga-pollo', 'Pechuga de pollo cocida', 'g', null, null, 165, 31, 0, 3.6, 'Carnes y huevos', false),
  ('milanesa-pollo', 'Milanesa de pollo al horno', 'u', 110, 'unidad', 230, 16, 14, 12, 'Carnes y huevos', false),
  ('atun-natural', 'Atún al natural (lata 170 g)', 'u', 120, 'lata', 110, 25, 0, 1, 'Pescados', false),
  ('huevo', 'Huevo', 'u', 50, 'unidad', 150, 12.5, 1, 10.5, 'Carnes y huevos', false),
  ('carne-magra', 'Carne vacuna magra cocida', 'g', null, null, 200, 28, 0, 9, 'Carnes y huevos', false),
  ('carne-picada', 'Carne picada especial cocida', 'g', null, null, 230, 26, 0, 14, 'Carnes y huevos', false),
  ('lentejas', 'Lentejas secas', 'g', null, null, 340, 24, 60, 1, 'Legumbres', false),
  ('jamon-cocido', 'Jamón cocido', 'g', null, null, 110, 18, 1.5, 3.5, 'Carnes y huevos', false),
  ('merluza', 'Merluza cocida', 'g', null, null, 95, 20, 0, 1.5, 'Pescados', false),
  ('arroz', 'Arroz largo fino (crudo)', 'g', null, null, 360, 7, 79, 0.6, 'Pastas y arroz', false),
  ('fideos', 'Fideos secos (crudos)', 'g', null, null, 355, 12, 72, 1.5, 'Pastas y arroz', false),
  ('avena', 'Avena', 'g', null, null, 380, 13, 62, 7, 'Cereales', false),
  ('pan-integral', 'Pan lactal integral', 'u', 25, 'rodaja', 250, 10, 43, 3.5, 'Panadería', false),
  ('pan-frances', 'Pan francés', 'g', null, null, 270, 9, 55, 1.5, 'Panadería', false),
  ('papa', 'Papa', 'g', null, null, 80, 2, 17, 0.1, 'Verduras', false),
  ('batata', 'Batata', 'g', null, null, 90, 1.6, 20, 0.1, 'Verduras', false),
  ('copos-maiz', 'Copos de maíz sin azúcar', 'g', null, null, 370, 7, 84, 0.5, 'Cereales', false),
  ('rapidita', 'Tortilla de trigo (rapidita)', 'u', 40, 'unidad', 300, 8, 50, 7, 'Panadería', false),
  ('lechuga', 'Lechuga', 'g', null, null, 15, 1.3, 2.9, 0.2, 'Verduras', false),
  ('tomate', 'Tomate', 'u', 120, 'unidad', 18, 0.9, 3.9, 0.2, 'Verduras', false),
  ('cebolla', 'Cebolla', 'u', 120, 'unidad', 40, 1.1, 9, 0.1, 'Verduras', false),
  ('morron', 'Morrón', 'u', 150, 'unidad', 27, 1, 6, 0.3, 'Verduras', false),
  ('calabaza', 'Calabaza', 'g', null, null, 30, 1, 7, 0.1, 'Verduras', false),
  ('zapallito', 'Zapallito', 'u', 150, 'unidad', 17, 1.2, 3, 0.3, 'Verduras', false),
  ('zanahoria', 'Zanahoria', 'u', 80, 'unidad', 41, 0.9, 10, 0.2, 'Verduras', false),
  ('banana', 'Banana', 'u', 100, 'unidad', 90, 1.1, 23, 0.3, 'Frutas', false),
  ('manzana', 'Manzana', 'u', 150, 'unidad', 52, 0.3, 14, 0.2, 'Frutas', false),
  ('mandarina', 'Mandarina', 'u', 80, 'unidad', 50, 0.8, 12, 0.3, 'Frutas', false),
  ('naranja', 'Naranja', 'u', 150, 'unidad', 47, 0.9, 12, 0.1, 'Frutas', false),
  ('leche', 'Leche parcialmente descremada', 'ml', null, null, 45, 3.1, 4.7, 1.5, 'Lácteos', false),
  ('leche-entera', 'Leche entera', 'ml', null, null, 60, 3, 4.7, 3, 'Lácteos', false),
  ('yogur-natural', 'Yogur natural', 'g', null, null, 62, 3.5, 5, 3, 'Lácteos', false),
  ('queso-cremoso', 'Queso cremoso', 'g', null, null, 280, 19, 2, 22, 'Lácteos', false),
  ('queso-rallado', 'Queso rallado', 'g', null, null, 390, 33, 3, 27, 'Lácteos', false),
  ('queso-untable', 'Queso untable light', 'g', null, null, 130, 9, 4, 9, 'Lácteos', false),
  ('manteca', 'Manteca', 'g', null, null, 740, 0.6, 0, 82, 'Lácteos', false),
  ('dulce-de-leche', 'Dulce de leche', 'g', null, null, 315, 6, 55, 7, 'Despensa', false),
  ('pure-tomate', 'Puré de tomate', 'g', null, null, 30, 1.5, 6, 0.2, 'Salsas y aderezos', false),
  ('salsa-bolonesa', 'Salsa boloñesa lista', 'g', null, null, 70, 3, 9, 2.5, 'Salsas y aderezos', false),
  ('arvejas', 'Arvejas en lata', 'g', null, null, 70, 4.5, 12, 0.4, 'Enlatados', false),
  ('choclo', 'Choclo en lata', 'g', null, null, 85, 2.5, 18, 1, 'Enlatados', false),
  ('aceite', 'Aceite', 'ml', null, null, 810, 0, 0, 92, 'Despensa', false),
  ('caldo', 'Caldo en cubo', 'u', 10, 'cubo', 200, 10, 20, 8, 'Despensa', false),
  ('azucar', 'Azúcar', 'g', null, null, 400, 0, 100, 0, 'Despensa', false),
  ('miel', 'Miel', 'g', null, null, 304, 0.3, 82, 0, 'Despensa', false),
  ('mayonesa', 'Mayonesa', 'g', null, null, 680, 1, 2, 75, 'Salsas y aderezos', false),
  ('mostaza', 'Mostaza', 'g', null, null, 66, 4, 6, 3, 'Salsas y aderezos', false),
  ('mani-cascara', 'Maní con cáscara (peso con cáscara)', 'g', null, null, 400, 17, 11, 33, 'Snacks y dulces', false),
  ('mani-pelado', 'Maní pelado', 'g', null, null, 590, 25, 16, 49, 'Snacks y dulces', false),
  ('criollo', 'Criollo', 'u', 25, 'unidad', 430, 9, 55, 19, 'Panadería', false),
  ('galletita-rellena', 'Galletita rellena tipo Oreo', 'u', 11, 'unidad', 480, 5, 70, 20, 'Snacks y dulces', false),
  ('galletita-agua', 'Galletita de agua', 'u', 5, 'unidad', 430, 10, 70, 12, 'Panadería', false),
  ('alfajor', 'Alfajor de chocolate', 'u', 50, 'unidad', 420, 5, 62, 17, 'Snacks y dulces', false),
  ('medialuna', 'Medialuna', 'u', 40, 'unidad', 400, 7, 48, 20, 'Panadería', false),
  ('chocolate', 'Chocolate', 'g', null, null, 540, 7, 57, 31, 'Snacks y dulces', false),
  ('helado', 'Helado', 'g', null, null, 200, 3.5, 24, 10, 'Congelados', false),
  ('lomito', 'Lomito completo (estimado)', 'u', 400, 'unidad', 250, 13, 22, 12, 'Comidas hechas', false),
  ('hamburguesa', 'Hamburguesa completa (estimado)', 'u', 250, 'unidad', 260, 14, 20, 14, 'Comidas hechas', false),
  ('papas-fritas', 'Papas fritas', 'g', null, null, 300, 3.5, 38, 15, 'Comidas hechas', false),
  ('pizza', 'Pizza muzzarella', 'u', 125, 'porción', 260, 11, 30, 10, 'Comidas hechas', false),
  ('empanada', 'Empanada de carne', 'u', 80, 'unidad', 280, 11, 27, 14, 'Comidas hechas', false),
  ('mate', 'Mate', 'ml', null, null, 0, 0, 0, 0, 'Bebidas', false),
  ('gaseosa', 'Gaseosa común', 'ml', null, null, 42, 0, 10.5, 0, 'Bebidas', false),
  ('gaseosa-zero', 'Gaseosa zero', 'ml', null, null, 0, 0, 0, 0, 'Bebidas', false),
  ('jugo-naranja', 'Jugo de naranja', 'ml', null, null, 45, 0.7, 10, 0.2, 'Bebidas', false),
  ('cerveza', 'Cerveza', 'ml', null, null, 43, 0.4, 3.5, 0, 'Bebidas', true),
  ('fernet-coca', 'Fernet con coca', 'ml', null, null, 80, 0, 9, 0, 'Bebidas', true),
  ('vino', 'Vino', 'ml', null, null, 83, 0, 2.5, 0, 'Bebidas', true),
  ('agua', 'Agua', 'ml', null, null, 0, 0, 0, 0, 'Bebidas', false),
  ('soda', 'Soda o agua con gas', 'ml', null, null, 0, 0, 0, 0, 'Bebidas', false),
  ('agua-saborizada', 'Agua saborizada con azúcar', 'ml', null, null, 18, 0, 4.5, 0, 'Bebidas', false),
  ('agua-saborizada-zero', 'Agua saborizada sin azúcar', 'ml', null, null, 1, 0, 0.2, 0, 'Bebidas', false),
  ('tonica', 'Agua tónica', 'ml', null, null, 34, 0, 8.5, 0, 'Bebidas', false),
  ('jugo-polvo', 'Jugo en polvo preparado', 'ml', null, null, 10, 0, 2.3, 0, 'Bebidas', false),
  ('jugo-caja', 'Jugo de caja o botella', 'ml', null, null, 45, 0.3, 11, 0, 'Bebidas', false),
  ('limonada', 'Limonada con azúcar', 'ml', null, null, 40, 0, 10, 0, 'Bebidas', false),
  ('isotonica', 'Bebida isotónica (tipo Gatorade)', 'ml', null, null, 24, 0, 6, 0, 'Bebidas', false),
  ('energizante', 'Energizante (tipo Speed o Red Bull)', 'ml', null, null, 45, 0, 11, 0, 'Bebidas', false),
  ('energizante-zero', 'Energizante sin azúcar', 'ml', null, null, 3, 0, 0, 0, 'Bebidas', false),
  ('cafe-con-leche', 'Café con leche', 'ml', null, null, 25, 1.6, 2.4, 0.8, 'Bebidas', false),
  ('chocolatada', 'Leche chocolatada', 'ml', null, null, 75, 3, 12, 1.8, 'Bebidas', false),
  ('licuado-banana', 'Licuado de banana con leche', 'ml', null, null, 70, 2.5, 12, 1.3, 'Bebidas', false),
  ('yogur-bebible', 'Yogur bebible', 'ml', null, null, 75, 2.8, 12.5, 1.5, 'Bebidas', false),
  ('cerveza-negra', 'Cerveza negra', 'ml', null, null, 55, 0.5, 5, 0, 'Bebidas', true),
  ('cerveza-ipa', 'Cerveza IPA o artesanal', 'ml', null, null, 55, 0.5, 4.5, 0, 'Bebidas', true),
  ('cerveza-sin-alcohol', 'Cerveza sin alcohol', 'ml', null, null, 25, 0.3, 5.5, 0, 'Bebidas', false),
  ('vino-blanco', 'Vino blanco o rosado', 'ml', null, null, 80, 0, 2, 0, 'Bebidas', true),
  ('espumante', 'Espumante o champagne', 'ml', null, null, 78, 0, 1.5, 0, 'Bebidas', true),
  ('sidra', 'Sidra', 'ml', null, null, 50, 0, 5, 0, 'Bebidas', true),
  ('fernet', 'Fernet solo', 'ml', null, null, 240, 0, 8, 0, 'Bebidas', true),
  ('bebida-blanca', 'Vodka, gin, whisky o ron (solo)', 'ml', null, null, 222, 0, 0, 0, 'Bebidas', true),
  ('gin-tonic', 'Gin tonic', 'ml', null, null, 80, 0, 6.4, 0, 'Bebidas', true),
  ('ron-cola', 'Ron con coca (cuba libre)', 'ml', null, null, 75, 0, 7.5, 0, 'Bebidas', true),
  ('campari', 'Campari u otro bitter (solo)', 'ml', null, null, 230, 0, 24, 0, 'Bebidas', true),
  ('aperol-spritz', 'Aperol spritz', 'ml', null, null, 90, 0, 8, 0, 'Bebidas', true),
  ('vermut', 'Vermut (Cinzano, Gancia)', 'ml', null, null, 140, 0, 12, 0, 'Bebidas', true),
  ('trago-dulce', 'Trago dulce (daiquiri, mojito, caipirinha)', 'ml', null, null, 120, 0, 12, 0, 'Bebidas', true),
  ('licor', 'Licor dulce', 'ml', null, null, 280, 0, 30, 0, 'Bebidas', true),
  ('pechuga-cruda', 'Pechuga de pollo (cruda)', 'g', null, null, 110, 23, 0, 1.5, 'Carnes y huevos', false),
  ('carne-picada-cruda', 'Carne picada (cruda)', 'g', null, null, 200, 19, 0, 13, 'Carnes y huevos', false),
  ('bife-nalga', 'Bife de nalga o cuadrada (crudo)', 'g', null, null, 130, 21, 0, 5, 'Carnes y huevos', false),
  ('milanesa-carne', 'Milanesa de carne al horno', 'u', 120, 'unidad', 240, 20, 12, 12, 'Carnes y huevos', false),
  ('filet-merluza', 'Filet de merluza (crudo)', 'g', null, null, 85, 18, 0, 1, 'Pescados', false),
  ('garbanzos', 'Garbanzos en lata', 'g', null, null, 120, 7, 18, 2, 'Enlatados', false),
  ('milanesa-soja', 'Milanesa de soja', 'u', 85, 'unidad', 200, 15, 15, 8, 'Congelados', false),
  ('polenta', 'Polenta (harina de maíz)', 'g', null, null, 350, 8, 77, 1.5, 'Pastas y arroz', false),
  ('tapa-tarta', 'Tapa de tarta', 'u', 200, 'unidad', 300, 6, 45, 10, 'Panadería', false),
  ('galleta-arroz', 'Galleta de arroz', 'u', 9, 'unidad', 385, 8, 81, 3, 'Panadería', false),
  ('pan-rallado', 'Pan rallado', 'g', null, null, 370, 11, 73, 3, 'Panadería', false),
  ('palta', 'Palta', 'u', 150, 'unidad', 160, 2, 9, 15, 'Verduras', false),
  ('acelga', 'Acelga o espinaca', 'g', null, null, 22, 2.5, 3.5, 0.3, 'Verduras', false),
  ('brocoli', 'Brócoli', 'g', null, null, 34, 2.8, 7, 0.4, 'Verduras', false),
  ('pera', 'Pera', 'u', 150, 'unidad', 57, 0.4, 15, 0.1, 'Frutas', false),
  ('durazno', 'Durazno', 'u', 130, 'unidad', 39, 0.9, 10, 0.3, 'Frutas', false),
  ('frutilla', 'Frutillas', 'g', null, null, 32, 0.7, 7.7, 0.3, 'Frutas', false),
  ('uva', 'Uvas', 'g', null, null, 69, 0.7, 18, 0.2, 'Frutas', false),
  ('queso-port-salut', 'Queso port salut light', 'g', null, null, 230, 24, 2, 14, 'Lácteos', false),
  ('ricota', 'Ricota', 'g', null, null, 150, 11, 3, 10, 'Lácteos', false),
  ('crema', 'Crema de leche', 'g', null, null, 340, 2, 3, 35, 'Lácteos', false),
  ('yogur-saborizado', 'Yogur saborizado', 'g', null, null, 90, 3.5, 14, 2.5, 'Lácteos', false),
  ('salsa-soja', 'Salsa de soja', 'ml', null, null, 55, 8, 5, 0, 'Salsas y aderezos', false),
  ('mermelada', 'Mermelada', 'g', null, null, 250, 0.4, 62, 0, 'Despensa', false),
  ('mermelada-light', 'Mermelada light', 'g', null, null, 120, 0.4, 30, 0, 'Despensa', false),
  ('cacao', 'Cacao en polvo azucarado', 'g', null, null, 380, 4, 88, 2.5, 'Despensa', false),
  ('aceitunas', 'Aceitunas', 'g', null, null, 145, 1, 4, 15, 'Enlatados', false),
  ('ketchup', 'Ketchup', 'g', null, null, 100, 1.2, 25, 0.1, 'Salsas y aderezos', false),
  ('nueces', 'Nueces', 'g', null, null, 650, 15, 14, 65, 'Snacks y dulces', false),
  ('almendras', 'Almendras', 'g', null, null, 580, 21, 22, 50, 'Snacks y dulces', false),
  ('barrita-cereal', 'Barrita de cereal', 'u', 23, 'unidad', 390, 6, 70, 9, 'Snacks y dulces', false),
  ('turron', 'Turrón de maní', 'u', 25, 'unidad', 400, 9, 70, 10, 'Snacks y dulces', false),
  ('papas-paquete', 'Papas fritas de paquete', 'g', null, null, 540, 6, 52, 34, 'Snacks y dulces', false),
  ('sandwich-miga', 'Sándwich de miga', 'u', 60, 'unidad', 250, 9, 28, 11, 'Comidas hechas', false),
  ('pancho', 'Pancho', 'u', 150, 'unidad', 250, 9, 24, 13, 'Comidas hechas', false),
  ('choripan', 'Choripán', 'u', 250, 'unidad', 300, 13, 20, 18, 'Comidas hechas', false),
  ('asado', 'Asado (carne)', 'g', null, null, 280, 24, 0, 20, 'Comidas hechas', false),
  ('tarta-porcion', 'Tarta de jamón y queso (porción)', 'u', 150, 'porción', 250, 10, 20, 14, 'Comidas hechas', false),
  ('sushi', 'Sushi (pieza)', 'u', 30, 'pieza', 150, 5, 25, 3, 'Comidas hechas', false),
  ('wrap-comprado', 'Wrap de pollo comprado (estimado)', 'u', 300, 'unidad', 200, 11, 20, 8, 'Comidas hechas', false),
  ('terere', 'Tereré con agua', 'ml', null, null, 0, 0, 0, 0, 'Bebidas', false),
  ('terere-jugo', 'Tereré con jugo', 'ml', null, null, 10, 0, 2.3, 0, 'Bebidas', false),
  ('mate-cocido', 'Mate cocido', 'ml', null, null, 0, 0, 0, 0, 'Bebidas', false),
  ('mate-cocido-leche', 'Mate cocido con leche', 'ml', null, null, 22, 1.5, 2.3, 0.7, 'Bebidas', false),
  ('cafe', 'Café negro', 'ml', null, null, 1, 0.1, 0, 0, 'Bebidas', false),
  ('cortado', 'Café cortado', 'ml', null, null, 10, 0.6, 0.9, 0.3, 'Bebidas', false),
  ('capuchino', 'Capuchino', 'ml', null, null, 40, 2, 4.5, 1.5, 'Bebidas', false),
  ('te', 'Té', 'ml', null, null, 0, 0, 0, 0, 'Bebidas', false),
  ('te-leche', 'Té con leche', 'ml', null, null, 12, 0.8, 1.2, 0.4, 'Bebidas', false),
  ('hamburguesa-carne', 'Hamburguesa de carne (medallón crudo)', 'u', 80, 'unidad', 250, 15, 2, 20, 'Carnes y huevos', false),
  ('salchicha', 'Salchicha tipo viena', 'u', 45, 'unidad', 270, 11, 3, 24, 'Carnes y huevos', false),
  ('chorizo', 'Chorizo parrillero', 'u', 100, 'unidad', 300, 15, 1, 26, 'Carnes y huevos', false),
  ('carre-cerdo', 'Carré o bondiola de cerdo (crudo)', 'g', null, null, 170, 20, 0, 10, 'Carnes y huevos', false),
  ('carne-guiso', 'Carne para guiso o estofado (cruda)', 'g', null, null, 140, 21, 0, 6, 'Carnes y huevos', false),
  ('pollo-trozado', 'Pollo trozado con piel (crudo)', 'g', null, null, 215, 18, 0, 15, 'Carnes y huevos', false),
  ('paleta', 'Paleta cocida (fiambre)', 'g', null, null, 105, 16, 3, 3, 'Carnes y huevos', false),
  ('salame', 'Salame', 'g', null, null, 400, 22, 1, 34, 'Carnes y huevos', false),
  ('mortadela', 'Mortadela', 'g', null, null, 250, 13, 3, 21, 'Carnes y huevos', false),
  ('atun-aceite', 'Atún en aceite (lata 170 g)', 'u', 120, 'lata', 190, 24, 0, 10, 'Pescados', false),
  ('caballa', 'Caballa en lata', 'g', null, null, 150, 20, 0, 8, 'Pescados', false),
  ('sardinas', 'Sardinas en lata', 'g', null, null, 190, 22, 0, 11, 'Pescados', false),
  ('leche-descremada', 'Leche descremada', 'ml', null, null, 34, 3.2, 4.8, 0.1, 'Lácteos', false),
  ('leche-polvo', 'Leche en polvo entera', 'g', null, null, 490, 26, 38, 26, 'Lácteos', false),
  ('yogur-griego', 'Yogur griego natural', 'g', null, null, 95, 8, 4, 5, 'Lácteos', false),
  ('yogur-descremado', 'Yogur descremado', 'g', null, null, 40, 4, 5, 0.1, 'Lácteos', false),
  ('yogur-proteico', 'Yogur alto en proteínas', 'g', null, null, 65, 7, 6, 1, 'Lácteos', false),
  ('queso-tybo', 'Queso tybo o en barra (fetas)', 'g', null, null, 330, 25, 1, 25, 'Lácteos', false),
  ('muzzarella', 'Queso muzzarella', 'g', null, null, 290, 21, 2, 22, 'Lácteos', false),
  ('queso-untable-clasico', 'Queso untable clásico', 'g', null, null, 240, 7, 3, 22, 'Lácteos', false),
  ('postre-lacteo', 'Postre de vainilla o chocolate (pote)', 'g', null, null, 125, 3, 20, 3.5, 'Lácteos', false),
  ('flan', 'Flan', 'g', null, null, 120, 3.5, 20, 3, 'Lácteos', false),
  ('ajo', 'Ajo (diente)', 'u', 5, 'diente', 149, 6.4, 33, 0.5, 'Verduras', false),
  ('pepino', 'Pepino', 'u', 200, 'unidad', 15, 0.7, 3.6, 0.1, 'Verduras', false),
  ('berenjena', 'Berenjena', 'u', 250, 'unidad', 25, 1, 6, 0.2, 'Verduras', false),
  ('repollo', 'Repollo', 'g', null, null, 25, 1.3, 6, 0.1, 'Verduras', false),
  ('remolacha', 'Remolacha', 'u', 100, 'unidad', 43, 1.6, 10, 0.2, 'Verduras', false),
  ('champinones', 'Champiñones', 'g', null, null, 22, 3.1, 3.3, 0.3, 'Verduras', false),
  ('chauchas', 'Chauchas', 'g', null, null, 31, 1.8, 7, 0.2, 'Verduras', false),
  ('rucula', 'Rúcula', 'g', null, null, 25, 2.6, 3.7, 0.7, 'Verduras', false),
  ('coliflor', 'Coliflor', 'g', null, null, 25, 1.9, 5, 0.3, 'Verduras', false),
  ('cebolla-verdeo', 'Cebolla de verdeo', 'g', null, null, 32, 1.8, 7, 0.2, 'Verduras', false),
  ('tomate-cherry', 'Tomates cherry', 'g', null, null, 18, 0.9, 3.9, 0.2, 'Verduras', false),
  ('limon', 'Limón', 'u', 100, 'unidad', 29, 1.1, 9, 0.3, 'Frutas', false),
  ('kiwi', 'Kiwi', 'u', 75, 'unidad', 61, 1.1, 15, 0.5, 'Frutas', false),
  ('anana', 'Ananá', 'g', null, null, 50, 0.5, 13, 0.1, 'Frutas', false),
  ('sandia', 'Sandía', 'g', null, null, 30, 0.6, 8, 0.2, 'Frutas', false),
  ('melon', 'Melón', 'g', null, null, 34, 0.8, 8, 0.2, 'Frutas', false),
  ('ciruela', 'Ciruela', 'u', 65, 'unidad', 46, 0.7, 11, 0.3, 'Frutas', false),
  ('pomelo', 'Pomelo', 'u', 250, 'unidad', 42, 0.8, 11, 0.1, 'Frutas', false),
  ('arandanos', 'Arándanos', 'g', null, null, 57, 0.7, 14, 0.3, 'Frutas', false),
  ('fideos-integrales', 'Fideos integrales (crudos)', 'g', null, null, 345, 13, 66, 2.5, 'Pastas y arroz', false),
  ('fideos-frescos', 'Fideos frescos (tallarines)', 'g', null, null, 280, 11, 55, 2, 'Pastas y arroz', false),
  ('fideos-instantaneos', 'Fideos instantáneos (tipo ramen)', 'g', null, null, 450, 9, 60, 19, 'Pastas y arroz', false),
  ('arroz-integral', 'Arroz integral (crudo)', 'g', null, null, 350, 7.5, 73, 2.7, 'Pastas y arroz', false),
  ('ravioles', 'Ravioles de ricota o verdura (frescos)', 'g', null, null, 200, 9, 30, 5, 'Pastas y arroz', false),
  ('noquis', 'Ñoquis de papa (frescos)', 'g', null, null, 160, 4, 34, 1, 'Pastas y arroz', false),
  ('porotos', 'Porotos secos', 'g', null, null, 335, 22, 60, 1.2, 'Legumbres', false),
  ('garbanzos-secos', 'Garbanzos secos', 'g', null, null, 364, 19, 61, 6, 'Legumbres', false),
  ('soja-texturizada', 'Soja texturizada', 'g', null, null, 330, 50, 30, 1, 'Legumbres', false),
  ('pan-lactal-blanco', 'Pan lactal blanco', 'u', 25, 'rodaja', 265, 8, 50, 3, 'Panadería', false),
  ('pan-hamburguesa', 'Pan de hamburguesa', 'u', 60, 'unidad', 280, 9, 50, 4, 'Panadería', false),
  ('pan-pancho', 'Pan de pancho', 'u', 40, 'unidad', 280, 9, 50, 4, 'Panadería', false),
  ('pan-arabe', 'Pan árabe', 'u', 60, 'unidad', 260, 9, 53, 1, 'Panadería', false),
  ('tostadas-mesa', 'Tostadas de mesa', 'u', 7, 'unidad', 390, 11, 72, 6, 'Panadería', false),
  ('galletita-salvado', 'Galletita de salvado', 'u', 6, 'unidad', 430, 10, 62, 15, 'Panadería', false),
  ('bizcochos', 'Bizcochos de grasa', 'u', 8, 'unidad', 480, 9, 58, 23, 'Panadería', false),
  ('grisines', 'Grisines', 'g', null, null, 400, 11, 70, 8, 'Panadería', false),
  ('prepizza', 'Prepizza', 'u', 250, 'unidad', 270, 8, 52, 3, 'Panadería', false),
  ('tapa-empanada', 'Tapa de empanada', 'u', 28, 'tapa', 300, 7, 50, 8, 'Panadería', false),
  ('granola', 'Granola', 'g', null, null, 430, 10, 65, 14, 'Cereales', false),
  ('cereal-azucarado', 'Cereales azucarados o de chocolate', 'g', null, null, 385, 5, 87, 2, 'Cereales', false),
  ('quinoa', 'Quinoa (cruda)', 'g', null, null, 370, 14, 64, 6, 'Cereales', false),
  ('chia', 'Semillas de chía', 'g', null, null, 490, 17, 42, 31, 'Cereales', false),
  ('jardinera', 'Jardinera en lata', 'g', null, null, 55, 2.5, 10, 0.4, 'Enlatados', false),
  ('lentejas-lata', 'Lentejas en lata', 'g', null, null, 90, 7, 13, 0.5, 'Enlatados', false),
  ('porotos-lata', 'Porotos en lata', 'g', null, null, 95, 6, 16, 0.5, 'Enlatados', false),
  ('palmitos', 'Palmitos', 'g', null, null, 28, 2.5, 4.6, 0.6, 'Enlatados', false),
  ('duraznos-almibar', 'Duraznos en almíbar', 'g', null, null, 75, 0.4, 19, 0.1, 'Enlatados', false),
  ('picadillo', 'Picadillo o paté de carne', 'g', null, null, 210, 11, 3, 17, 'Enlatados', false),
  ('salsa-tomate', 'Salsa de tomate lista (pomarola, filetto)', 'g', null, null, 45, 1.5, 7, 1.2, 'Salsas y aderezos', false),
  ('tomate-triturado', 'Tomate triturado o perita en lata', 'g', null, null, 25, 1.2, 4.5, 0.2, 'Salsas y aderezos', false),
  ('salsa-golf', 'Salsa golf', 'g', null, null, 420, 1, 12, 41, 'Salsas y aderezos', false),
  ('mayonesa-light', 'Mayonesa light', 'g', null, null, 330, 1, 10, 32, 'Salsas y aderezos', false),
  ('vinagre', 'Vinagre', 'ml', null, null, 4, 0, 0.6, 0, 'Salsas y aderezos', false),
  ('aceto', 'Aceto balsámico', 'ml', null, null, 90, 0.5, 17, 0, 'Salsas y aderezos', false),
  ('jugo-limon', 'Jugo de limón (en botella)', 'ml', null, null, 22, 0.4, 7, 0, 'Salsas y aderezos', false),
  ('salsa-barbacoa', 'Salsa barbacoa', 'g', null, null, 170, 1, 40, 0.5, 'Salsas y aderezos', false),
  ('salsa-blanca', 'Salsa blanca', 'g', null, null, 110, 3.5, 9, 6.5, 'Salsas y aderezos', false),
  ('chimichurri', 'Chimichurri', 'g', null, null, 250, 1, 6, 25, 'Salsas y aderezos', false),
  ('pesto', 'Pesto', 'g', null, null, 450, 5, 6, 45, 'Salsas y aderezos', false),
  ('aceite-oliva', 'Aceite de oliva', 'ml', null, null, 820, 0, 0, 92, 'Despensa', false),
  ('sal', 'Sal', 'g', null, null, 0, 0, 0, 0, 'Despensa', false),
  ('harina', 'Harina de trigo', 'g', null, null, 340, 10, 72, 1, 'Despensa', false),
  ('maicena', 'Fécula de maíz (maicena)', 'g', null, null, 350, 0.3, 87, 0.1, 'Despensa', false),
  ('pure-instantaneo', 'Puré de papas instantáneo (en polvo)', 'g', null, null, 350, 8, 78, 0.6, 'Despensa', false),
  ('leche-condensada', 'Leche condensada', 'g', null, null, 325, 8, 55, 8, 'Despensa', false),
  ('mani-pasta', 'Pasta de maní', 'g', null, null, 600, 25, 20, 50, 'Despensa', false),
  ('cafe-polvo', 'Café instantáneo (en polvo)', 'g', null, null, 240, 12, 41, 0.5, 'Despensa', false),
  ('yerba', 'Yerba mate', 'g', null, null, 0, 0, 0, 0, 'Despensa', false),
  ('saquitos', 'Té o mate cocido (saquito)', 'u', 2, 'saquito', 0, 0, 0, 0, 'Despensa', false),
  ('proteina-polvo', 'Proteína en polvo (whey)', 'g', null, null, 380, 78, 8, 5, 'Despensa', false),
  ('galletita-dulce', 'Galletita dulce simple (vainilla o tipo María)', 'u', 6, 'unidad', 440, 7, 72, 13, 'Snacks y dulces', false),
  ('budin', 'Budín', 'g', null, null, 380, 5, 52, 17, 'Snacks y dulces', false),
  ('magdalena', 'Magdalena', 'u', 30, 'unidad', 420, 5, 50, 22, 'Snacks y dulces', false),
  ('alfajor-maicena', 'Alfajor de maicena', 'u', 40, 'unidad', 420, 5, 65, 16, 'Snacks y dulces', false),
  ('alfajor-triple', 'Alfajor triple', 'u', 70, 'unidad', 430, 5, 62, 18, 'Snacks y dulces', false),
  ('bombon', 'Bombón de chocolate con relleno', 'u', 15, 'unidad', 530, 9, 50, 33, 'Snacks y dulces', false),
  ('gomitas', 'Gomitas', 'g', null, null, 340, 5, 78, 0, 'Snacks y dulces', false),
  ('gelatina', 'Gelatina preparada', 'g', null, null, 60, 1.5, 14, 0, 'Snacks y dulces', false),
  ('dulce-membrillo', 'Dulce de membrillo o batata', 'g', null, null, 270, 0.5, 67, 0.2, 'Snacks y dulces', false),
  ('postre-mani', 'Postre de maní (tipo Mantecol)', 'g', null, null, 540, 13, 45, 35, 'Snacks y dulces', false),
  ('palitos-salados', 'Palitos salados', 'g', null, null, 480, 9, 60, 22, 'Snacks y dulces', false),
  ('chizitos', 'Chizitos', 'g', null, null, 500, 6, 60, 26, 'Snacks y dulces', false),
  ('pochoclo', 'Pochoclo dulce', 'g', null, null, 400, 9, 75, 8, 'Snacks y dulces', false),
  ('mix-frutos-secos', 'Mix de frutos secos', 'g', null, null, 550, 17, 30, 42, 'Snacks y dulces', false),
  ('pasas', 'Pasas de uva', 'g', null, null, 300, 3, 79, 0.5, 'Snacks y dulces', false),
  ('barrita-proteica', 'Barrita proteica', 'u', 45, 'unidad', 380, 30, 35, 13, 'Snacks y dulces', false),
  ('nuggets', 'Nuggets de pollo', 'u', 20, 'unidad', 250, 13, 16, 15, 'Congelados', false),
  ('medallon-pollo', 'Medallón de pollo rebozado', 'u', 65, 'unidad', 220, 12, 15, 12, 'Congelados', false),
  ('filet-rebozado', 'Filet de merluza rebozado', 'u', 100, 'unidad', 200, 12, 18, 9, 'Congelados', false),
  ('medallon-verdura', 'Medallón de verdura', 'u', 80, 'unidad', 180, 5, 22, 8, 'Congelados', false),
  ('papas-congeladas', 'Papas prefritas congeladas (al horno)', 'g', null, null, 150, 2.5, 24, 5, 'Congelados', false),
  ('vegetales-congelados', 'Vegetales congelados (mix)', 'g', null, null, 50, 3, 8, 0.5, 'Congelados', false),
  ('milanesa-napolitana', 'Milanesa napolitana (estimado)', 'u', 250, 'unidad', 250, 15, 12, 15, 'Comidas hechas', false),
  ('sandwich-milanesa', 'Sándwich de milanesa (estimado)', 'u', 350, 'unidad', 250, 13, 25, 11, 'Comidas hechas', false),
  ('empanada-jyq', 'Empanada de jamón y queso', 'u', 80, 'unidad', 290, 11, 28, 15, 'Comidas hechas', false),
  ('empanada-pollo', 'Empanada de pollo', 'u', 80, 'unidad', 260, 12, 27, 11, 'Comidas hechas', false),
  ('tarta-verdura-porcion', 'Tarta de verdura (porción)', 'u', 150, 'porción', 200, 7, 20, 10, 'Comidas hechas', false),
  ('canelones', 'Canelones con salsa (porción)', 'u', 300, 'porción', 140, 6, 14, 6, 'Comidas hechas', false),
  ('ensalada-rusa', 'Ensalada rusa', 'g', null, null, 150, 2, 12, 10, 'Comidas hechas', false),
  ('pollo-spiedo', 'Pollo al spiedo (con piel)', 'g', null, null, 215, 25, 0, 13, 'Comidas hechas', false),
  ('tostado-bar', 'Tostado de jamón y queso (de bar)', 'u', 150, 'unidad', 270, 14, 28, 11, 'Comidas hechas', false),
  ('bebida-almendras', 'Bebida de almendras', 'ml', null, null, 15, 0.5, 0.5, 1.2, 'Bebidas', false),
  ('bebida-soja', 'Bebida de soja', 'ml', null, null, 40, 3, 3, 1.8, 'Bebidas', false),
  ('batido-proteina', 'Batido de proteína (con agua)', 'ml', null, null, 38, 7.8, 0.8, 0.5, 'Bebidas', false)
on conflict (slug) do nothing;

insert into public.recipes (slug, name, minutes, servings, meal_types, portable, steps) values
  ('pata-muslo-horno', 'Pata muslo al horno con papa y batata', 60, 6, '{almuerzo,cena}', true, 'Horno a 200 °C. Pollo en una placa con sal, pimentón, ajo y orégano: 50–55 min.
Papas y batatas en cubos, sin pelar, en otra placa con el aceite y sal: 35–40 min, moviéndolas una vez.
Porción: 1 pata sin piel y un puñado grande de papas y batatas.'),
  ('arroz-con-pollo', 'Arroz con pollo express', 15, 1, '{almuerzo,cena}', true, 'Hervís el arroz (o usás 1 taza de arroz ya cocido).
Desmenuzás la pata muslo cocida, sin piel.
Todo a una sartén con las arvejas, el choclo y el puré de tomate: 5–7 min revolviendo.'),
  ('fideos-con-atun', 'Fideos con atún', 12, 1, '{almuerzo,cena}', true, 'Hervís los fideos 9–10 min.
Mientras, calentás el puré de tomate con el atún escurrido en una sartén.
Mezclás y queso rallado arriba. Sin pan.'),
  ('milanesas-con-ensalada', 'Milanesas de pollo con ensalada', 25, 1, '{almuerzo,cena}', true, 'Horno a 200 °C, 20–25 min, dando vuelta las milanesas a la mitad.
Ensalada de lechuga y tomate con el aceite, sal y limón o vinagre.'),
  ('ensalada-completa', 'Ensalada completa', 5, 1, '{almuerzo,cena}', true, 'Cortás la lechuga, el tomate y los huevos duros.
Sumás el atún escurrido y el choclo.
Condimentás con el aceite, limón o vinagre y sal. Va con las 2 rodajas de pan.'),
  ('tortilla-papa-atun', 'Tortilla de papa y atún', 15, 1, '{almuerzo,cena}', true, 'Papa en cubitos en un bowl con un chorrito de agua, tapado, al microondas 5–6 min.
Batís los huevos con la papa, el atún y sal.
Sartén antiadherente con el aceite, fuego bajo, 4–5 min por lado. Para dar vuelta, usá un plato.'),
  ('fideos-salsa-pollo', 'Fideos con salsa y pollo', 12, 1, '{almuerzo,cena}', true, 'Hervís los fideos 9–10 min.
Calentás la salsa con la pata muslo cocida y desmenuzada, sin piel.
Mezclás y queso rallado arriba. Sin pan.'),
  ('guiso-lentejas', 'Guiso de lentejas con pollo', 35, 3, '{almuerzo,cena}', true, 'Rehogás la cebolla picada con el aceite, 3 min.
Agregás las lentejas (sin remojo), el puré de tomate, el caldo, la calabaza en cubos, el pollo desmenuzado, pimentón y 1 L de agua.
30 min a fuego medio, revolviendo cada tanto. La calabaza se deshace y no se nota.
Lo que sobra va al freezer.'),
  ('omelette-queso', 'Omelette de queso con ensalada', 5, 1, '{almuerzo,cena}', false, 'Batís los huevos con sal.
Sartén antiadherente, huevos, queso en el medio y doblás: 3–4 min.
Ensalada de lechuga y tomate al lado, con las 2 rodajas de pan.'),
  ('desayuno-sandwich-huevo', 'Sándwich de queso, huevos duros y banana', 5, 1, '{desayuno}', true, 'Sándwich con las 2 rodajas de pan y el queso cremoso.
2 huevos duros (10 min de hervor; podés dejarlos hechos de antes) y la banana.'),
  ('desayuno-huevos-revueltos', 'Huevos revueltos con tostadas y manzana', 5, 1, '{desayuno}', false, 'Batís los huevos con sal en una taza: 1 min 30 s al microondas, revolviendo a la mitad.
Tostás el pan. La manzana, de postre.'),
  ('desayuno-avena', 'Avena con leche y banana', 3, 1, '{desayuno}', false, 'Avena con la leche, 2 min al microondas.
Banana cortada arriba.'),
  ('merienda-leche-mani', 'Leche con maní', 1, 1, '{merienda}', true, '1 vaso de leche sola, con café o en mate cocido, sin azúcar.
60 g de maní con cáscara, medido.'),
  ('merienda-yogur-mani', 'Yogur natural con maní', 1, 1, '{merienda}', true, '200 g de yogur natural.
60 g de maní con cáscara, medido.'),
  ('merienda-banana-mani', 'Banana con maní y mate', 1, 1, '{merienda}', true, '1 banana y 60 g de maní con cáscara, medido. Mate sin azúcar.'),
  ('desayuno-tostadas-untable', 'Tostadas con queso untable y mermelada light', 3, 1, '{desayuno}', false, 'Tostás el pan.
Untás el queso y la mermelada. Va con café con leche o mate.'),
  ('desayuno-yogur-avena', 'Yogur con avena y banana', 2, 1, '{desayuno}', true, 'Mezclás el yogur con la avena.
Banana cortada arriba. Se puede dejar armado la noche anterior.'),
  ('desayuno-copos', 'Copos de maíz con leche y banana', 2, 1, '{desayuno}', false, 'Copos con la leche fría o tibia.
Banana cortada arriba.'),
  ('desayuno-tostado', 'Tostado de jamón y queso con café con leche', 5, 1, '{desayuno}', true, 'Armás el sándwich con el jamón y el queso.
Lo tostás en sartén o tostadora, 2 min por lado.
Café con la leche.'),
  ('desayuno-palta-huevo', 'Tostadas con palta y huevo', 6, 1, '{desayuno}', false, 'Tostás el pan y pisás la media palta arriba, con sal.
Huevos revueltos o a la plancha, sin aceite.'),
  ('desayuno-licuado', 'Licuado de banana, leche y avena', 3, 1, '{desayuno}', false, 'Todo a la licuadora, 30 segundos. Sin azúcar.'),
  ('merienda-tostadas', 'Tostadas con queso untable', 3, 1, '{merienda}', true, 'Tostás el pan y untás el queso. Con mate o café sin azúcar.'),
  ('merienda-yogur-fruta', 'Yogur natural con manzana y avena', 2, 1, '{merienda}', true, 'Yogur con la manzana en cubos y la avena.'),
  ('merienda-sandwich', 'Sándwich de jamón y queso', 2, 1, '{merienda}', true, 'Pan, jamón y queso. Frío o tostado.'),
  ('merienda-fruta-nueces', 'Manzana con nueces', 1, 1, '{merienda}', true, '1 manzana y un puñado chico de nueces (25 g).'),
  ('merienda-galletas-arroz', 'Café con leche y galletas de arroz con queso', 3, 1, '{merienda}', false, 'Café con la leche, sin azúcar.
Galletas de arroz con el queso untable.'),
  ('merienda-huevos-banana', 'Huevos duros y banana', 1, 1, '{merienda}', true, '2 huevos duros (hechos de antes) y 1 banana.'),
  ('pechuga-ensalada', 'Pechuga a la plancha con ensalada', 12, 1, '{almuerzo,cena}', true, 'Pechuga fileteada fina, con sal y limón, a la plancha: 4–5 min por lado.
Ensalada de lechuga y tomate con el aceite.
Va con las 2 rodajas de pan.'),
  ('pechuga-arroz', 'Pechuga con arroz', 20, 1, '{almuerzo,cena}', true, 'Hervís el arroz.
Pechuga en cubos o fileteada, a la plancha con el aceite, sal y pimentón.
Tomate en rodajas al lado.'),
  ('pechuga-pure', 'Pechuga con puré de papa', 25, 1, '{almuerzo,cena}', true, 'Papas en cubos, hervidas 15 min. Las pisás con la leche y sal.
Pechuga a la plancha con el aceite, 4–5 min por lado.'),
  ('salteado-pollo', 'Salteado de pollo con arroz y verduras', 20, 1, '{almuerzo,cena}', true, 'Hervís el arroz.
Pollo en tiras a la sartén con el aceite, 5 min.
Sumás zanahoria rallada, morrón y cebolla en tiras, 5 min más.
Salsa de soja y mezclás con el arroz.'),
  ('pollo-brocoli', 'Pollo con brócoli y arroz', 20, 1, '{almuerzo,cena}', true, 'Hervís el arroz y el brócoli (5 min, que quede firme).
Pollo en cubos a la sartén con el aceite.
Juntás todo con la salsa de soja.'),
  ('pata-muslo-calabaza', 'Pata muslo al horno con calabaza', 55, 4, '{almuerzo,cena}', true, 'Horno a 200 °C. Pollo con sal, pimentón y ajo en una placa: 50–55 min.
Calabaza en cubos grandes con el aceite, en la misma placa o en otra: 35–40 min.
Porción: 1 pata sin piel con calabaza.'),
  ('fideos-bolonesa', 'Fideos con boloñesa casera', 25, 3, '{almuerzo,cena}', true, 'Rehogás la cebolla picada con el aceite y dorás la carne.
Agregás el puré de tomate, sal y orégano: 15 min a fuego bajo.
Hervís los fideos y servís con queso rallado. Sin pan.'),
  ('hamburguesas-caseras', 'Hamburguesas caseras con ensalada', 20, 2, '{almuerzo,cena}', true, 'Mezclás la carne con el huevo, el pan rallado, sal y ajo. Armás 4 hamburguesas.
A la plancha o al horno, 4–5 min por lado.
Ensalada de lechuga y tomate con el aceite.'),
  ('pastel-papa', 'Pastel de papa', 50, 4, '{almuerzo,cena}', true, 'Hervís las papas y hacés un puré con la leche.
Rehogás la cebolla con el aceite, dorás la carne y sumás los huevos duros picados.
En una fuente: carne abajo, puré arriba y queso rallado. Horno 200 °C, 15 min.'),
  ('bife-ensalada', 'Bife a la plancha con ensalada', 10, 1, '{almuerzo,cena}', true, 'Bife a la plancha bien caliente, 3–4 min por lado, sal al final.
Ensalada de lechuga y tomate con el aceite.
Va con las 2 rodajas de pan.'),
  ('bife-pure-calabaza', 'Bife con puré de calabaza', 25, 1, '{almuerzo,cena}', true, 'Calabaza en cubos, hervida o al microondas, 12–15 min. La pisás con sal y el queso rallado.
Bife a la plancha con el aceite, 3–4 min por lado.'),
  ('milanesa-carne-pure', 'Milanesa de carne al horno con puré', 25, 1, '{almuerzo,cena}', true, 'Milanesa al horno a 200 °C, 20 min, dándola vuelta a la mitad.
Puré: papas hervidas y pisadas con la leche.
Tomate en rodajas al lado.'),
  ('arroz-atun-huevo', 'Arroz con atún y huevo', 15, 1, '{almuerzo,cena}', true, 'Hervís el arroz y el huevo (10 min).
Mezclás el arroz con el atún escurrido, las arvejas y el aceite.
Huevo duro picado arriba.'),
  ('ensalada-arroz-atun', 'Ensalada de arroz, atún y choclo', 15, 1, '{almuerzo,cena}', true, 'Hervís el arroz y lo enfriás con agua.
Mezclás con el atún, el choclo, el tomate en cubos y el huevo duro.
Aceite, sal y limón o vinagre.'),
  ('ensalada-lentejas', 'Ensalada de lentejas, huevo y tomate', 30, 1, '{almuerzo,cena}', true, 'Hervís las lentejas 25 min, sin remojo, y las escurrís.
Mezclás con el tomate en cubos y los huevos duros.
Aceite, sal y vinagre.'),
  ('ensalada-garbanzos', 'Ensalada de garbanzos, atún y tomate', 5, 1, '{almuerzo,cena}', true, 'Escurrís los garbanzos y el atún.
Mezclás con el tomate en cubos, el aceite, sal y limón.'),
  ('ensalada-cesar', 'Ensalada César simple', 15, 1, '{almuerzo,cena}', true, 'Pechuga a la plancha y cortada en tiras.
Pan tostado en cubos.
Lechuga, pollo, pan, huevo duro y queso rallado, con el aceite y limón.'),
  ('tarta-atun', 'Tarta de atún', 40, 3, '{almuerzo,cena}', true, 'Tapa en una tartera. Mezclás el atún, la cebolla rehogada, los huevos batidos y el queso en cubos.
Relleno adentro, tomate en rodajas arriba.
Horno a 180 °C, 30 min.'),
  ('tarta-jamon-queso', 'Tarta de jamón y queso', 35, 3, '{almuerzo,cena}', true, 'Tapa en una tartera. Jamón y queso en capas.
Huevos batidos con sal por arriba.
Horno a 180 °C, 25–30 min.'),
  ('tarta-acelga', 'Tarta de acelga y ricota', 40, 3, '{almuerzo,cena}', true, 'Hervís la acelga 3 min, la escurrís bien y la picás.
Mezclás con la ricota, los huevos y el queso rallado.
Relleno sobre la tapa. Horno a 180 °C, 30 min.'),
  ('fideos-tuco', 'Fideos con tuco, huevo y queso', 15, 1, '{almuerzo,cena}', true, 'Hervís los fideos y los huevos.
Calentás el puré de tomate con el aceite, sal y orégano, 5 min.
Fideos con la salsa, huevo duro picado y queso rallado. Sin pan.'),
  ('revuelto-zapallitos', 'Revuelto de zapallitos con huevo', 15, 1, '{almuerzo,cena}', false, 'Cebolla y zapallitos en cubos chicos a la sartén con el aceite, 8 min.
Agregás los huevos batidos y revolvés hasta que cuajen.
Queso rallado arriba. Va con las 2 rodajas de pan.'),
  ('merluza-papas', 'Merluza al horno con papas', 30, 1, '{almuerzo,cena}', true, 'Papas en rodajas finas en una placa con el aceite y sal: 15 min a 200 °C.
Sumás la merluza arriba con sal y limón: 12–15 min más.'),
  ('merluza-ensalada', 'Merluza a la plancha con ensalada', 12, 1, '{almuerzo,cena}', false, 'Merluza a la plancha con sal y limón, 3–4 min por lado.
Ensalada de lechuga y tomate con el aceite.
Va con las 2 rodajas de pan.'),
  ('polenta-salsa', 'Polenta con salsa, queso y huevo', 12, 1, '{almuerzo,cena}', false, 'Polenta en lluvia sobre agua hirviendo con sal, revolviendo 3–5 min.
Calentás el puré de tomate con orégano.
Polenta, salsa, queso en cubos, huevo duro y queso rallado.'),
  ('guiso-arroz-pollo', 'Guiso de arroz con pollo', 35, 3, '{almuerzo,cena}', true, 'Rehogás la cebolla y la zanahoria rallada con el aceite.
Sumás el pollo sin piel, el puré de tomate, el caldo y 700 ml de agua: 15 min.
Agregás el arroz y cocinás 15 min más. Desmenuzás el pollo.'),
  ('guiso-fideos-carne', 'Guiso de fideos con carne', 30, 3, '{almuerzo,cena}', true, 'Rehogás la cebolla y la zanahoria rallada con el aceite y dorás la carne.
Sumás el puré de tomate, el caldo y 700 ml de agua: 10 min.
Agregás los fideos y cocinás hasta que estén.'),
  ('wrap-pollo', 'Wrap de pollo', 15, 1, '{almuerzo,cena}', true, 'Pechuga en tiras a la plancha.
Untás las rapiditas con el queso y armás con el pollo, la lechuga y el tomate.'),
  ('wrap-atun', 'Wrap de atún y huevo', 5, 1, '{almuerzo,cena}', true, 'Untás las rapiditas con el queso.
Atún escurrido, huevo duro picado, lechuga y tomate. Enrollás.'),
  ('sandwich-pollo', 'Sándwich de pollo, huevo y tomate', 12, 1, '{almuerzo,cena}', true, 'Pechuga a la plancha.
Armás 2 sándwiches con el pollo, huevo duro, tomate, lechuga y mostaza.'),
  ('tortilla-papa', 'Tortilla de papa', 25, 2, '{almuerzo,cena}', true, 'Papas en cubitos al microondas con un chorrito de agua, tapadas, 8 min.
Cebolla rehogada con parte del aceite. Mezclás todo con los huevos batidos y sal.
Sartén con el resto del aceite, fuego bajo, 5 min por lado.
Va con tomate en rodajas.'),
  ('omelette-jamon-queso', 'Omelette de jamón y queso con ensalada', 6, 1, '{almuerzo,cena}', false, 'Batís los huevos con sal.
Sartén antiadherente, huevos, jamón y queso en el medio y doblás: 3–4 min.
Ensalada de lechuga y tomate, con las 2 rodajas de pan.'),
  ('arroz-huevo-arvejas', 'Arroz con huevo y arvejas', 15, 1, '{almuerzo,cena}', true, 'Hervís el arroz.
Huevos revueltos en la sartén con el aceite.
Mezclás arroz, huevo y arvejas, con sal y pimentón.'),
  ('pizzetas-rapidita', 'Pizzetas de rapidita', 10, 1, '{almuerzo,cena}', false, 'Rapiditas en una placa. Puré de tomate con orégano, queso y jamón arriba.
Horno fuerte 6–8 min, hasta que se derrita el queso.'),
  ('milanesas-soja-arroz', 'Milanesas de soja con arroz y ensalada', 20, 1, '{almuerzo,cena}', true, 'Milanesas al horno a 200 °C, 15 min, dándolas vuelta.
Hervís el arroz.
Ensalada de lechuga y tomate con el aceite.'),
  ('galletitas-miel', 'Café con leche y galletitas de agua con miel', 3, 1, '{desayuno,merienda}', false, 'Calentás la leche y le sumás el café.
Untás las galletitas con la miel: una cucharadita cada dos alcanza.'),
  ('arroz-con-leche', 'Arroz con leche', 35, 4, '{desayuno,merienda}', true, 'Leche, arroz y azúcar en una olla a fuego bajo, revolviendo cada tanto: 30 min, hasta que el arroz esté tierno y cremoso.
Si tenés, una cucharadita de esencia de vainilla o canela al final.
Se guarda en la heladera 3 días. Porción: un bol chico.'),
  ('avena-miel', 'Avena con leche y miel', 5, 1, '{desayuno}', false, 'Avena y leche en una olla chica: 3 min revolviendo, hasta que espese.
La miel arriba.'),
  ('tostadas-miel', 'Tostadas con miel y leche', 3, 1, '{desayuno,merienda}', false, 'Tostás el pan y lo untás con la miel.
Va con un vaso de leche, sola o con café.'),
  ('tostadas-pasta-mani', 'Tostadas con pasta de maní y banana', 3, 1, '{desayuno,merienda}', true, 'Tostás el pan y untás la pasta de maní.
Banana en rodajas arriba.'),
  ('yogur-granola', 'Yogur con granola y fruta', 2, 1, '{desayuno,merienda}', true, 'Yogur en un bol, granola y la banana cortada arriba.'),
  ('galletitas-queso', 'Galletitas de agua con queso untable', 2, 1, '{merienda}', true, 'Untás las galletitas con el queso. Va con mate, té o café.'),
  ('fideos-pomarola', 'Fideos con salsa de tomate y queso', 15, 1, '{almuerzo,cena}', true, 'Hervís los fideos en agua con sal el tiempo que diga el paquete.
Calentás la salsa en la misma olla, ya colada.
Queso rallado arriba.'),
  ('fideos-manteca', 'Fideos con manteca y queso', 12, 1, '{almuerzo,cena}', true, 'Hervís los fideos en agua con sal.
Los colás y los mezclás con la manteca y el queso rallado mientras están calientes.'),
  ('ensalada-fideos-atun', 'Ensalada de fideos, atún y jardinera', 15, 1, '{almuerzo,cena}', true, 'Hervís los fideos (mejor tirabuzones o moños), los colás y los enfriás con agua.
Los mezclás con el atún escurrido, la jardinera escurrida y la mayonesa.
Se come fría: va bien para llevar.'),
  ('arroz-atun-jardinera', 'Arroz con atún y jardinera', 20, 1, '{almuerzo,cena}', true, 'Hervís el arroz 15–18 min y lo colás.
Lo mezclás con el atún escurrido, la jardinera escurrida y el aceite.
Se come tibio o frío.'),
  ('arroz-primavera', 'Arroz primavera con huevo', 20, 1, '{almuerzo,cena}', true, 'Hervís el arroz 15–18 min.
Huevos revueltos en la sartén con el aceite.
Mezclás todo con la jardinera y las arvejas escurridas y lo calentás 2 min.'),
  ('ensalada-jardinera-atun', 'Ensalada de jardinera, atún y huevo', 12, 1, '{almuerzo,cena}', true, 'Huevos duros: 10 min desde que hierve.
Jardinera escurrida, atún y huevos en cuartos.
La mayonesa para mezclar.'),
  ('milanesas-arroz-jardinera', 'Milanesas de pollo con arroz y jardinera', 25, 1, '{almuerzo,cena}', true, 'Milanesas al horno a 200 °C, 20 min, dándolas vuelta.
Hervís el arroz y lo mezclás con la jardinera escurrida.'),
  ('milanesas-napolitanas', 'Milanesas de pollo a la napolitana', 25, 1, '{almuerzo,cena}', false, 'Milanesas al horno a 200 °C, 15 min, dándolas vuelta.
Salsa y muzzarella arriba y 5 min más, hasta que se derrita.'),
  ('lentejas-arroz', 'Guiso de lentejas con arroz', 45, 3, '{almuerzo,cena}', true, 'Lentejas en remojo desde la noche anterior (o 2 horas en agua caliente).
Cebolla picada en la olla con el aceite, 5 min. Sumás la salsa, el caldo, las lentejas y agua hasta cubrir: 25 min.
Agregás el arroz y 15 min más, con agua si hace falta.
Porción: un plato hondo.'),
  ('polenta-pomarola', 'Polenta con salsa de tomate y queso rallado', 10, 1, '{almuerzo,cena}', false, 'Hervís 350 ml de agua con sal, echás la polenta en lluvia y revolvés 2–3 min (si es instantánea).
Salsa caliente arriba y el queso rallado.'),
  ('sopa-fideos-verduras', 'Sopa de fideos con verduras', 15, 1, '{almuerzo,cena}', false, 'Hervís medio litro de agua con el caldo.
Sumás los fideos (mejor cabello de ángel o dedalitos) y la jardinera: 8 min.
Queso rallado al servir.'),
  ('omelette-atun', 'Omelette de atún y queso con tostadas', 10, 1, '{almuerzo,cena}', false, 'Batís los huevos con el atún escurrido y el queso rallado.
Sartén antiadherente a fuego medio: 3 min, doblás y 1 min más.
Va con las tostadas.'),
  ('sandwich-atun', 'Sándwich de atún con mayonesa', 8, 1, '{almuerzo,cena}', true, 'Mezclás el atún escurrido con la mayonesa.
Armás dos sándwiches con la lechuga y el tomate en rodajas.'),
  ('hamburguesa-pan', 'Hamburguesa casera al pan', 12, 1, '{almuerzo,cena}', false, 'Hamburguesa a la plancha o sartén sin aceite: 4 min de cada lado.
Armás con el queso, la lechuga y el tomate.'),
  ('panchos', 'Panchos', 8, 1, '{almuerzo,cena}', false, 'Salchichas en agua hirviendo 3 min.
Armás con el pan y la mostaza.'),
  ('guiso-arroz-salchichas', 'Guiso de arroz con salchichas', 30, 3, '{almuerzo,cena}', true, 'Cebolla picada en la olla con el aceite, 5 min.
Sumás la salsa, el caldo, el arroz y 600 ml de agua: 18 min a fuego bajo.
Salchichas en rodajas los últimos 5 min.
Porción: un plato hondo.'),
  ('pizza-casera', 'Pizza casera de muzzarella', 15, 2, '{almuerzo,cena}', false, 'Horno bien caliente (230 °C).
Salsa sobre la prepizza y 5 min de horno. Sumás la muzzarella y 6–8 min más.
Porción: media pizza.'),
  ('noquis-salsa', 'Ñoquis con salsa de tomate', 10, 1, '{almuerzo,cena}', false, 'Ñoquis en agua hirviendo con sal: se sacan cuando suben, 2–3 min.
Salsa caliente y queso rallado.'),
  ('ravioles-salsa', 'Ravioles con salsa de tomate', 12, 1, '{almuerzo,cena}', false, 'Ravioles en agua hirviendo con sal: 4–5 min.
Salsa caliente y queso rallado.')
on conflict (slug) do nothing;

insert into public.recipe_items (recipe_id, food_id, qty)
select r.id, f.id, v.qty from (values
  ('pata-muslo-horno', 'pata-muslo', 6),
  ('pata-muslo-horno', 'papa', 800),
  ('pata-muslo-horno', 'batata', 400),
  ('pata-muslo-horno', 'aceite', 15),
  ('arroz-con-pollo', 'arroz', 70),
  ('arroz-con-pollo', 'pata-muslo', 1),
  ('arroz-con-pollo', 'arvejas', 80),
  ('arroz-con-pollo', 'choclo', 80),
  ('arroz-con-pollo', 'pure-tomate', 50),
  ('fideos-con-atun', 'fideos', 85),
  ('fideos-con-atun', 'atun-natural', 1),
  ('fideos-con-atun', 'pure-tomate', 120),
  ('fideos-con-atun', 'queso-rallado', 10),
  ('milanesas-con-ensalada', 'milanesa-pollo', 2),
  ('milanesas-con-ensalada', 'lechuga', 80),
  ('milanesas-con-ensalada', 'tomate', 1),
  ('milanesas-con-ensalada', 'aceite', 5),
  ('ensalada-completa', 'lechuga', 100),
  ('ensalada-completa', 'tomate', 1),
  ('ensalada-completa', 'huevo', 2),
  ('ensalada-completa', 'atun-natural', 1),
  ('ensalada-completa', 'choclo', 50),
  ('ensalada-completa', 'aceite', 5),
  ('ensalada-completa', 'pan-integral', 2),
  ('tortilla-papa-atun', 'papa', 250),
  ('tortilla-papa-atun', 'huevo', 3),
  ('tortilla-papa-atun', 'atun-natural', 0.5),
  ('tortilla-papa-atun', 'aceite', 5),
  ('fideos-salsa-pollo', 'fideos', 70),
  ('fideos-salsa-pollo', 'salsa-bolonesa', 150),
  ('fideos-salsa-pollo', 'pata-muslo', 1),
  ('fideos-salsa-pollo', 'queso-rallado', 10),
  ('guiso-lentejas', 'lentejas', 250),
  ('guiso-lentejas', 'cebolla', 1),
  ('guiso-lentejas', 'pure-tomate', 520),
  ('guiso-lentejas', 'caldo', 1),
  ('guiso-lentejas', 'calabaza', 300),
  ('guiso-lentejas', 'pata-muslo', 2),
  ('guiso-lentejas', 'aceite', 5),
  ('omelette-queso', 'huevo', 3),
  ('omelette-queso', 'queso-cremoso', 30),
  ('omelette-queso', 'lechuga', 80),
  ('omelette-queso', 'tomate', 1),
  ('omelette-queso', 'pan-integral', 2),
  ('desayuno-sandwich-huevo', 'pan-integral', 2),
  ('desayuno-sandwich-huevo', 'queso-cremoso', 30),
  ('desayuno-sandwich-huevo', 'huevo', 2),
  ('desayuno-sandwich-huevo', 'banana', 1),
  ('desayuno-huevos-revueltos', 'huevo', 2),
  ('desayuno-huevos-revueltos', 'pan-integral', 2),
  ('desayuno-huevos-revueltos', 'manzana', 1),
  ('desayuno-avena', 'avena', 40),
  ('desayuno-avena', 'leche', 250),
  ('desayuno-avena', 'banana', 1),
  ('merienda-leche-mani', 'leche', 250),
  ('merienda-leche-mani', 'mani-cascara', 60),
  ('merienda-yogur-mani', 'yogur-natural', 200),
  ('merienda-yogur-mani', 'mani-cascara', 60),
  ('merienda-banana-mani', 'banana', 1),
  ('merienda-banana-mani', 'mani-cascara', 60),
  ('desayuno-tostadas-untable', 'pan-integral', 2),
  ('desayuno-tostadas-untable', 'queso-untable', 30),
  ('desayuno-tostadas-untable', 'mermelada-light', 20),
  ('desayuno-tostadas-untable', 'leche', 200),
  ('desayuno-yogur-avena', 'yogur-natural', 200),
  ('desayuno-yogur-avena', 'avena', 40),
  ('desayuno-yogur-avena', 'banana', 1),
  ('desayuno-copos', 'copos-maiz', 40),
  ('desayuno-copos', 'leche', 250),
  ('desayuno-copos', 'banana', 1),
  ('desayuno-tostado', 'pan-integral', 2),
  ('desayuno-tostado', 'jamon-cocido', 40),
  ('desayuno-tostado', 'queso-cremoso', 30),
  ('desayuno-tostado', 'leche', 150),
  ('desayuno-palta-huevo', 'pan-integral', 2),
  ('desayuno-palta-huevo', 'palta', 0.5),
  ('desayuno-palta-huevo', 'huevo', 2),
  ('desayuno-licuado', 'banana', 1),
  ('desayuno-licuado', 'leche', 300),
  ('desayuno-licuado', 'avena', 30),
  ('merienda-tostadas', 'pan-integral', 2),
  ('merienda-tostadas', 'queso-untable', 40),
  ('merienda-yogur-fruta', 'yogur-natural', 200),
  ('merienda-yogur-fruta', 'manzana', 1),
  ('merienda-yogur-fruta', 'avena', 20),
  ('merienda-sandwich', 'pan-integral', 2),
  ('merienda-sandwich', 'jamon-cocido', 40),
  ('merienda-sandwich', 'queso-cremoso', 30),
  ('merienda-fruta-nueces', 'manzana', 1),
  ('merienda-fruta-nueces', 'nueces', 25),
  ('merienda-galletas-arroz', 'leche', 200),
  ('merienda-galletas-arroz', 'galleta-arroz', 3),
  ('merienda-galletas-arroz', 'queso-untable', 30),
  ('merienda-huevos-banana', 'huevo', 2),
  ('merienda-huevos-banana', 'banana', 1),
  ('pechuga-ensalada', 'pechuga-cruda', 180),
  ('pechuga-ensalada', 'lechuga', 100),
  ('pechuga-ensalada', 'tomate', 1),
  ('pechuga-ensalada', 'aceite', 10),
  ('pechuga-ensalada', 'pan-integral', 2),
  ('pechuga-arroz', 'pechuga-cruda', 180),
  ('pechuga-arroz', 'arroz', 70),
  ('pechuga-arroz', 'tomate', 1),
  ('pechuga-arroz', 'aceite', 5),
  ('pechuga-pure', 'pechuga-cruda', 180),
  ('pechuga-pure', 'papa', 300),
  ('pechuga-pure', 'leche', 50),
  ('pechuga-pure', 'aceite', 5),
  ('salteado-pollo', 'pechuga-cruda', 150),
  ('salteado-pollo', 'arroz', 70),
  ('salteado-pollo', 'zanahoria', 1),
  ('salteado-pollo', 'morron', 0.5),
  ('salteado-pollo', 'cebolla', 0.5),
  ('salteado-pollo', 'salsa-soja', 15),
  ('salteado-pollo', 'aceite', 10),
  ('pollo-brocoli', 'pechuga-cruda', 180),
  ('pollo-brocoli', 'brocoli', 200),
  ('pollo-brocoli', 'arroz', 60),
  ('pollo-brocoli', 'salsa-soja', 10),
  ('pollo-brocoli', 'aceite', 5),
  ('pata-muslo-calabaza', 'pata-muslo', 4),
  ('pata-muslo-calabaza', 'calabaza', 800),
  ('pata-muslo-calabaza', 'aceite', 10),
  ('fideos-bolonesa', 'fideos', 240),
  ('fideos-bolonesa', 'carne-picada-cruda', 300),
  ('fideos-bolonesa', 'pure-tomate', 520),
  ('fideos-bolonesa', 'cebolla', 1),
  ('fideos-bolonesa', 'aceite', 10),
  ('fideos-bolonesa', 'queso-rallado', 30),
  ('hamburguesas-caseras', 'carne-picada-cruda', 300),
  ('hamburguesas-caseras', 'huevo', 1),
  ('hamburguesas-caseras', 'pan-rallado', 20),
  ('hamburguesas-caseras', 'lechuga', 150),
  ('hamburguesas-caseras', 'tomate', 2),
  ('hamburguesas-caseras', 'aceite', 10),
  ('pastel-papa', 'carne-picada-cruda', 500),
  ('pastel-papa', 'papa', 1000),
  ('pastel-papa', 'cebolla', 1),
  ('pastel-papa', 'huevo', 2),
  ('pastel-papa', 'leche', 100),
  ('pastel-papa', 'aceite', 10),
  ('pastel-papa', 'queso-rallado', 40),
  ('bife-ensalada', 'bife-nalga', 180),
  ('bife-ensalada', 'lechuga', 100),
  ('bife-ensalada', 'tomate', 1),
  ('bife-ensalada', 'aceite', 10),
  ('bife-ensalada', 'pan-integral', 2),
  ('bife-pure-calabaza', 'bife-nalga', 180),
  ('bife-pure-calabaza', 'calabaza', 300),
  ('bife-pure-calabaza', 'aceite', 5),
  ('bife-pure-calabaza', 'queso-rallado', 10),
  ('milanesa-carne-pure', 'milanesa-carne', 1),
  ('milanesa-carne-pure', 'papa', 300),
  ('milanesa-carne-pure', 'leche', 50),
  ('milanesa-carne-pure', 'tomate', 1),
  ('arroz-atun-huevo', 'arroz', 80),
  ('arroz-atun-huevo', 'atun-natural', 1),
  ('arroz-atun-huevo', 'huevo', 1),
  ('arroz-atun-huevo', 'arvejas', 60),
  ('arroz-atun-huevo', 'aceite', 5),
  ('ensalada-arroz-atun', 'arroz', 70),
  ('ensalada-arroz-atun', 'atun-natural', 1),
  ('ensalada-arroz-atun', 'choclo', 80),
  ('ensalada-arroz-atun', 'tomate', 1),
  ('ensalada-arroz-atun', 'huevo', 1),
  ('ensalada-arroz-atun', 'aceite', 5),
  ('ensalada-lentejas', 'lentejas', 80),
  ('ensalada-lentejas', 'huevo', 2),
  ('ensalada-lentejas', 'tomate', 1),
  ('ensalada-lentejas', 'aceite', 10),
  ('ensalada-garbanzos', 'garbanzos', 200),
  ('ensalada-garbanzos', 'atun-natural', 1),
  ('ensalada-garbanzos', 'tomate', 1),
  ('ensalada-garbanzos', 'aceite', 10),
  ('ensalada-cesar', 'pechuga-cruda', 150),
  ('ensalada-cesar', 'lechuga', 150),
  ('ensalada-cesar', 'queso-rallado', 20),
  ('ensalada-cesar', 'pan-integral', 2),
  ('ensalada-cesar', 'huevo', 1),
  ('ensalada-cesar', 'aceite', 10),
  ('tarta-atun', 'tapa-tarta', 1),
  ('tarta-atun', 'atun-natural', 2),
  ('tarta-atun', 'huevo', 3),
  ('tarta-atun', 'cebolla', 1),
  ('tarta-atun', 'queso-cremoso', 100),
  ('tarta-atun', 'tomate', 1),
  ('tarta-jamon-queso', 'tapa-tarta', 1),
  ('tarta-jamon-queso', 'jamon-cocido', 150),
  ('tarta-jamon-queso', 'queso-cremoso', 150),
  ('tarta-jamon-queso', 'huevo', 3),
  ('tarta-acelga', 'tapa-tarta', 1),
  ('tarta-acelga', 'acelga', 400),
  ('tarta-acelga', 'ricota', 250),
  ('tarta-acelga', 'huevo', 2),
  ('tarta-acelga', 'queso-rallado', 30),
  ('fideos-tuco', 'fideos', 90),
  ('fideos-tuco', 'pure-tomate', 150),
  ('fideos-tuco', 'huevo', 2),
  ('fideos-tuco', 'queso-rallado', 20),
  ('fideos-tuco', 'aceite', 5),
  ('revuelto-zapallitos', 'zapallito', 2),
  ('revuelto-zapallitos', 'huevo', 3),
  ('revuelto-zapallitos', 'cebolla', 0.5),
  ('revuelto-zapallitos', 'queso-rallado', 15),
  ('revuelto-zapallitos', 'aceite', 5),
  ('revuelto-zapallitos', 'pan-integral', 2),
  ('merluza-papas', 'filet-merluza', 250),
  ('merluza-papas', 'papa', 300),
  ('merluza-papas', 'aceite', 10),
  ('merluza-ensalada', 'filet-merluza', 250),
  ('merluza-ensalada', 'lechuga', 100),
  ('merluza-ensalada', 'tomate', 1),
  ('merluza-ensalada', 'aceite', 10),
  ('merluza-ensalada', 'pan-integral', 2),
  ('polenta-salsa', 'polenta', 80),
  ('polenta-salsa', 'pure-tomate', 150),
  ('polenta-salsa', 'queso-cremoso', 50),
  ('polenta-salsa', 'huevo', 1),
  ('polenta-salsa', 'queso-rallado', 10),
  ('guiso-arroz-pollo', 'arroz', 240),
  ('guiso-arroz-pollo', 'pata-muslo', 3),
  ('guiso-arroz-pollo', 'pure-tomate', 520),
  ('guiso-arroz-pollo', 'cebolla', 1),
  ('guiso-arroz-pollo', 'zanahoria', 1),
  ('guiso-arroz-pollo', 'caldo', 1),
  ('guiso-arroz-pollo', 'aceite', 10),
  ('guiso-fideos-carne', 'fideos', 240),
  ('guiso-fideos-carne', 'carne-picada-cruda', 300),
  ('guiso-fideos-carne', 'pure-tomate', 520),
  ('guiso-fideos-carne', 'cebolla', 1),
  ('guiso-fideos-carne', 'zanahoria', 1),
  ('guiso-fideos-carne', 'caldo', 1),
  ('guiso-fideos-carne', 'aceite', 10),
  ('wrap-pollo', 'rapidita', 2),
  ('wrap-pollo', 'pechuga-cruda', 150),
  ('wrap-pollo', 'lechuga', 50),
  ('wrap-pollo', 'tomate', 1),
  ('wrap-pollo', 'queso-untable', 30),
  ('wrap-atun', 'rapidita', 2),
  ('wrap-atun', 'atun-natural', 1),
  ('wrap-atun', 'huevo', 1),
  ('wrap-atun', 'lechuga', 50),
  ('wrap-atun', 'tomate', 1),
  ('wrap-atun', 'queso-untable', 30),
  ('sandwich-pollo', 'pan-integral', 4),
  ('sandwich-pollo', 'pechuga-cruda', 120),
  ('sandwich-pollo', 'huevo', 1),
  ('sandwich-pollo', 'tomate', 1),
  ('sandwich-pollo', 'lechuga', 30),
  ('sandwich-pollo', 'mostaza', 10),
  ('tortilla-papa', 'papa', 500),
  ('tortilla-papa', 'huevo', 5),
  ('tortilla-papa', 'cebolla', 1),
  ('tortilla-papa', 'aceite', 15),
  ('tortilla-papa', 'tomate', 2),
  ('omelette-jamon-queso', 'huevo', 3),
  ('omelette-jamon-queso', 'jamon-cocido', 40),
  ('omelette-jamon-queso', 'queso-cremoso', 30),
  ('omelette-jamon-queso', 'lechuga', 80),
  ('omelette-jamon-queso', 'tomate', 1),
  ('omelette-jamon-queso', 'pan-integral', 2),
  ('arroz-huevo-arvejas', 'arroz', 90),
  ('arroz-huevo-arvejas', 'huevo', 3),
  ('arroz-huevo-arvejas', 'arvejas', 100),
  ('arroz-huevo-arvejas', 'aceite', 5),
  ('pizzetas-rapidita', 'rapidita', 2),
  ('pizzetas-rapidita', 'pure-tomate', 80),
  ('pizzetas-rapidita', 'queso-cremoso', 80),
  ('pizzetas-rapidita', 'jamon-cocido', 40),
  ('milanesas-soja-arroz', 'milanesa-soja', 2),
  ('milanesas-soja-arroz', 'arroz', 60),
  ('milanesas-soja-arroz', 'lechuga', 80),
  ('milanesas-soja-arroz', 'tomate', 1),
  ('milanesas-soja-arroz', 'aceite', 5),
  ('galletitas-miel', 'galletita-agua', 6),
  ('galletitas-miel', 'miel', 20),
  ('galletitas-miel', 'leche', 200),
  ('arroz-con-leche', 'arroz', 150),
  ('arroz-con-leche', 'leche', 1000),
  ('arroz-con-leche', 'azucar', 80),
  ('avena-miel', 'avena', 40),
  ('avena-miel', 'leche', 250),
  ('avena-miel', 'miel', 15),
  ('tostadas-miel', 'pan-integral', 2),
  ('tostadas-miel', 'miel', 20),
  ('tostadas-miel', 'leche', 250),
  ('tostadas-pasta-mani', 'pan-integral', 2),
  ('tostadas-pasta-mani', 'mani-pasta', 20),
  ('tostadas-pasta-mani', 'banana', 1),
  ('yogur-granola', 'yogur-natural', 200),
  ('yogur-granola', 'granola', 40),
  ('yogur-granola', 'banana', 1),
  ('galletitas-queso', 'galletita-agua', 6),
  ('galletitas-queso', 'queso-untable', 40),
  ('fideos-pomarola', 'fideos', 100),
  ('fideos-pomarola', 'salsa-tomate', 150),
  ('fideos-pomarola', 'queso-rallado', 20),
  ('fideos-manteca', 'fideos', 100),
  ('fideos-manteca', 'manteca', 10),
  ('fideos-manteca', 'queso-rallado', 25),
  ('ensalada-fideos-atun', 'fideos', 80),
  ('ensalada-fideos-atun', 'atun-natural', 1),
  ('ensalada-fideos-atun', 'jardinera', 150),
  ('ensalada-fideos-atun', 'mayonesa-light', 15),
  ('arroz-atun-jardinera', 'arroz', 80),
  ('arroz-atun-jardinera', 'atun-natural', 1),
  ('arroz-atun-jardinera', 'jardinera', 150),
  ('arroz-atun-jardinera', 'aceite', 5),
  ('arroz-primavera', 'arroz', 80),
  ('arroz-primavera', 'jardinera', 150),
  ('arroz-primavera', 'arvejas', 50),
  ('arroz-primavera', 'huevo', 2),
  ('arroz-primavera', 'aceite', 5),
  ('ensalada-jardinera-atun', 'jardinera', 250),
  ('ensalada-jardinera-atun', 'atun-natural', 1),
  ('ensalada-jardinera-atun', 'huevo', 2),
  ('ensalada-jardinera-atun', 'mayonesa-light', 15),
  ('milanesas-arroz-jardinera', 'milanesa-pollo', 2),
  ('milanesas-arroz-jardinera', 'arroz', 50),
  ('milanesas-arroz-jardinera', 'jardinera', 100),
  ('milanesas-napolitanas', 'milanesa-pollo', 2),
  ('milanesas-napolitanas', 'salsa-tomate', 80),
  ('milanesas-napolitanas', 'muzzarella', 60),
  ('lentejas-arroz', 'lentejas', 250),
  ('lentejas-arroz', 'arroz', 100),
  ('lentejas-arroz', 'salsa-tomate', 300),
  ('lentejas-arroz', 'cebolla', 1),
  ('lentejas-arroz', 'caldo', 1),
  ('lentejas-arroz', 'aceite', 10),
  ('polenta-pomarola', 'polenta', 80),
  ('polenta-pomarola', 'salsa-tomate', 150),
  ('polenta-pomarola', 'queso-rallado', 25),
  ('sopa-fideos-verduras', 'fideos', 50),
  ('sopa-fideos-verduras', 'jardinera', 150),
  ('sopa-fideos-verduras', 'caldo', 1),
  ('sopa-fideos-verduras', 'queso-rallado', 10),
  ('omelette-atun', 'huevo', 3),
  ('omelette-atun', 'atun-natural', 0.5),
  ('omelette-atun', 'queso-rallado', 15),
  ('omelette-atun', 'pan-integral', 2),
  ('sandwich-atun', 'pan-integral', 4),
  ('sandwich-atun', 'atun-natural', 1),
  ('sandwich-atun', 'mayonesa-light', 15),
  ('sandwich-atun', 'tomate', 1),
  ('sandwich-atun', 'lechuga', 30),
  ('hamburguesa-pan', 'hamburguesa-carne', 1),
  ('hamburguesa-pan', 'pan-hamburguesa', 1),
  ('hamburguesa-pan', 'queso-tybo', 20),
  ('hamburguesa-pan', 'lechuga', 30),
  ('hamburguesa-pan', 'tomate', 0.5),
  ('panchos', 'salchicha', 2),
  ('panchos', 'pan-pancho', 2),
  ('panchos', 'mostaza', 10),
  ('guiso-arroz-salchichas', 'arroz', 240),
  ('guiso-arroz-salchichas', 'salchicha', 6),
  ('guiso-arroz-salchichas', 'salsa-tomate', 300),
  ('guiso-arroz-salchichas', 'cebolla', 1),
  ('guiso-arroz-salchichas', 'caldo', 1),
  ('guiso-arroz-salchichas', 'aceite', 10),
  ('pizza-casera', 'prepizza', 1),
  ('pizza-casera', 'salsa-tomate', 120),
  ('pizza-casera', 'muzzarella', 200),
  ('noquis-salsa', 'noquis', 300),
  ('noquis-salsa', 'salsa-tomate', 150),
  ('noquis-salsa', 'queso-rallado', 15),
  ('ravioles-salsa', 'ravioles', 250),
  ('ravioles-salsa', 'salsa-tomate', 150),
  ('ravioles-salsa', 'queso-rallado', 15)
) as v(recipe_slug, food_slug, qty)
join public.recipes r on r.slug = v.recipe_slug
join public.foods f on f.slug = v.food_slug
on conflict do nothing;
