// Datos base de Tupper: alimentos y recetas comunes a todos los usuarios.
// kcal, proteina, carbohidratos y grasa son cada 100 g (o 100 ml).
// Si la unidad es 'u', unit_grams dice cuantos gramos pesa una unidad.
// Formato: [slug, nombre, unidad, gramos por unidad, etiqueta, kcal, prot, carbs, grasa, categoria]

const alimentosBase = [
  ['pata-muslo', 'Pata muslo (sin piel)', 'u', 150, 'pieza', 185, 25, 0, 9, 'Proteínas'],
  ['pechuga-pollo', 'Pechuga de pollo cocida', 'g', null, null, 165, 31, 0, 3.6, 'Proteínas'],
  ['milanesa-pollo', 'Milanesa de pollo al horno', 'u', 110, 'unidad', 230, 16, 14, 12, 'Proteínas'],
  ['atun-natural', 'Atún al natural (lata 170 g)', 'u', 120, 'lata', 110, 25, 0, 1, 'Proteínas'],
  ['huevo', 'Huevo', 'u', 50, 'unidad', 150, 12.5, 1, 10.5, 'Proteínas'],
  ['carne-magra', 'Carne vacuna magra cocida', 'g', null, null, 200, 28, 0, 9, 'Proteínas'],
  ['carne-picada', 'Carne picada especial cocida', 'g', null, null, 230, 26, 0, 14, 'Proteínas'],
  ['lentejas', 'Lentejas secas', 'g', null, null, 340, 24, 60, 1, 'Proteínas'],
  ['jamon-cocido', 'Jamón cocido', 'g', null, null, 110, 18, 1.5, 3.5, 'Proteínas'],
  ['merluza', 'Merluza cocida', 'g', null, null, 95, 20, 0, 1.5, 'Proteínas'],

  ['arroz', 'Arroz largo fino (crudo)', 'g', null, null, 360, 7, 79, 0.6, 'Carbohidratos'],
  ['fideos', 'Fideos secos (crudos)', 'g', null, null, 355, 12, 72, 1.5, 'Carbohidratos'],
  ['avena', 'Avena', 'g', null, null, 380, 13, 62, 7, 'Carbohidratos'],
  ['pan-integral', 'Pan lactal integral', 'u', 25, 'rodaja', 250, 10, 43, 3.5, 'Carbohidratos'],
  ['pan-frances', 'Pan francés', 'g', null, null, 270, 9, 55, 1.5, 'Carbohidratos'],
  ['papa', 'Papa', 'g', null, null, 80, 2, 17, 0.1, 'Carbohidratos'],
  ['batata', 'Batata', 'g', null, null, 90, 1.6, 20, 0.1, 'Carbohidratos'],
  ['copos-maiz', 'Copos de maíz sin azúcar', 'g', null, null, 370, 7, 84, 0.5, 'Carbohidratos'],
  ['rapidita', 'Tortilla de trigo (rapidita)', 'u', 40, 'unidad', 300, 8, 50, 7, 'Carbohidratos'],

  ['lechuga', 'Lechuga', 'g', null, null, 15, 1.3, 2.9, 0.2, 'Verduras'],
  ['tomate', 'Tomate', 'u', 120, 'unidad', 18, 0.9, 3.9, 0.2, 'Verduras'],
  ['cebolla', 'Cebolla', 'u', 120, 'unidad', 40, 1.1, 9, 0.1, 'Verduras'],
  ['morron', 'Morrón', 'u', 150, 'unidad', 27, 1, 6, 0.3, 'Verduras'],
  ['calabaza', 'Calabaza', 'g', null, null, 30, 1, 7, 0.1, 'Verduras'],
  ['zapallito', 'Zapallito', 'u', 150, 'unidad', 17, 1.2, 3, 0.3, 'Verduras'],
  ['zanahoria', 'Zanahoria', 'u', 80, 'unidad', 41, 0.9, 10, 0.2, 'Verduras'],

  ['banana', 'Banana', 'u', 100, 'unidad', 90, 1.1, 23, 0.3, 'Frutas'],
  ['manzana', 'Manzana', 'u', 150, 'unidad', 52, 0.3, 14, 0.2, 'Frutas'],
  ['mandarina', 'Mandarina', 'u', 80, 'unidad', 50, 0.8, 12, 0.3, 'Frutas'],
  ['naranja', 'Naranja', 'u', 150, 'unidad', 47, 0.9, 12, 0.1, 'Frutas'],

  ['leche', 'Leche parcialmente descremada', 'ml', null, null, 45, 3.1, 4.7, 1.5, 'Lácteos'],
  ['leche-entera', 'Leche entera', 'ml', null, null, 60, 3, 4.7, 3, 'Lácteos'],
  ['yogur-natural', 'Yogur natural', 'g', null, null, 62, 3.5, 5, 3, 'Lácteos'],
  ['queso-cremoso', 'Queso cremoso', 'g', null, null, 280, 19, 2, 22, 'Lácteos'],
  ['queso-rallado', 'Queso rallado', 'g', null, null, 390, 33, 3, 27, 'Lácteos'],
  ['queso-untable', 'Queso untable light', 'g', null, null, 130, 9, 4, 9, 'Lácteos'],
  ['manteca', 'Manteca', 'g', null, null, 740, 0.6, 0, 82, 'Lácteos'],
  ['dulce-de-leche', 'Dulce de leche', 'g', null, null, 315, 6, 55, 7, 'Lácteos'],

  ['pure-tomate', 'Puré de tomate', 'g', null, null, 30, 1.5, 6, 0.2, 'Despensa'],
  ['salsa-bolonesa', 'Salsa boloñesa lista', 'g', null, null, 70, 3, 9, 2.5, 'Despensa'],
  ['arvejas', 'Arvejas en lata', 'g', null, null, 70, 4.5, 12, 0.4, 'Despensa'],
  ['choclo', 'Choclo en lata', 'g', null, null, 85, 2.5, 18, 1, 'Despensa'],
  ['aceite', 'Aceite', 'ml', null, null, 810, 0, 0, 92, 'Despensa'],
  ['caldo', 'Caldo en cubo', 'u', 10, 'cubo', 200, 10, 20, 8, 'Despensa'],
  ['azucar', 'Azúcar', 'g', null, null, 400, 0, 100, 0, 'Despensa'],
  ['miel', 'Miel', 'g', null, null, 304, 0.3, 82, 0, 'Despensa'],
  ['mayonesa', 'Mayonesa', 'g', null, null, 680, 1, 2, 75, 'Despensa'],
  ['mostaza', 'Mostaza', 'g', null, null, 66, 4, 6, 3, 'Despensa'],

  ['mani-cascara', 'Maní con cáscara (peso con cáscara)', 'g', null, null, 400, 17, 11, 33, 'Snacks'],
  ['mani-pelado', 'Maní pelado', 'g', null, null, 590, 25, 16, 49, 'Snacks'],
  ['criollo', 'Criollo', 'u', 25, 'unidad', 430, 9, 55, 19, 'Snacks'],
  ['galletita-rellena', 'Galletita rellena tipo Oreo', 'u', 11, 'unidad', 480, 5, 70, 20, 'Snacks'],
  ['galletita-agua', 'Galletita de agua', 'u', 5, 'unidad', 430, 10, 70, 12, 'Snacks'],
  ['alfajor', 'Alfajor de chocolate', 'u', 50, 'unidad', 420, 5, 62, 17, 'Snacks'],
  ['medialuna', 'Medialuna', 'u', 40, 'unidad', 400, 7, 48, 20, 'Snacks'],
  ['chocolate', 'Chocolate', 'g', null, null, 540, 7, 57, 31, 'Snacks'],
  ['helado', 'Helado', 'g', null, null, 200, 3.5, 24, 10, 'Snacks'],

  ['lomito', 'Lomito completo (estimado)', 'u', 400, 'unidad', 250, 13, 22, 12, 'Comidas hechas'],
  ['hamburguesa', 'Hamburguesa completa (estimado)', 'u', 250, 'unidad', 260, 14, 20, 14, 'Comidas hechas'],
  ['papas-fritas', 'Papas fritas', 'g', null, null, 300, 3.5, 38, 15, 'Comidas hechas'],
  ['pizza', 'Pizza muzzarella', 'u', 125, 'porción', 260, 11, 30, 10, 'Comidas hechas'],
  ['empanada', 'Empanada de carne', 'u', 80, 'unidad', 280, 11, 27, 14, 'Comidas hechas'],

  ['mate', 'Mate', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['gaseosa', 'Gaseosa común', 'ml', null, null, 42, 0, 10.5, 0, 'Bebidas'],
  ['gaseosa-zero', 'Gaseosa zero', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['jugo-naranja', 'Jugo de naranja', 'ml', null, null, 45, 0.7, 10, 0.2, 'Bebidas'],
  ['cerveza', 'Cerveza', 'ml', null, null, 43, 0.4, 3.5, 0, 'Bebidas'],
  ['fernet-coca', 'Fernet con coca', 'ml', null, null, 80, 0, 9, 0, 'Bebidas'],
  ['vino', 'Vino', 'ml', null, null, 83, 0, 2.5, 0, 'Bebidas'],
]

// Las cantidades de cada ingrediente son para la receta entera (todas las porciones).
const recetasBase = [
  {
    slug: 'pata-muslo-horno', name: 'Pata muslo al horno con papa y batata', minutes: 60, servings: 6,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Horno a 200 °C. Pollo en una placa con sal, pimentón, ajo y orégano: 50–55 min.\nPapas y batatas en cubos, sin pelar, en otra placa con el aceite y sal: 35–40 min, moviéndolas una vez.\nPorción: 1 pata sin piel y un puñado grande de papas y batatas.',
    items: [['pata-muslo', 6], ['papa', 800], ['batata', 400], ['aceite', 15]],
  },
  {
    slug: 'arroz-con-pollo', name: 'Arroz con pollo express', minutes: 15, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Hervís el arroz (o usás 1 taza de arroz ya cocido).\nDesmenuzás la pata muslo cocida, sin piel.\nTodo a una sartén con las arvejas, el choclo y el puré de tomate: 5–7 min revolviendo.',
    items: [['arroz', 70], ['pata-muslo', 1], ['arvejas', 80], ['choclo', 80], ['pure-tomate', 50]],
  },
  {
    slug: 'fideos-con-atun', name: 'Fideos con atún', minutes: 12, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Hervís los fideos 9–10 min.\nMientras, calentás el puré de tomate con el atún escurrido en una sartén.\nMezclás y queso rallado arriba. Sin pan.',
    items: [['fideos', 85], ['atun-natural', 1], ['pure-tomate', 120], ['queso-rallado', 10]],
  },
  {
    slug: 'milanesas-con-ensalada', name: 'Milanesas de pollo con ensalada', minutes: 25, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Horno a 200 °C, 20–25 min, dando vuelta las milanesas a la mitad.\nEnsalada de lechuga y tomate con el aceite, sal y limón o vinagre.',
    items: [['milanesa-pollo', 2], ['lechuga', 80], ['tomate', 1], ['aceite', 5]],
  },
  {
    slug: 'ensalada-completa', name: 'Ensalada completa', minutes: 5, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Cortás la lechuga, el tomate y los huevos duros.\nSumás el atún escurrido y el choclo.\nCondimentás con el aceite, limón o vinagre y sal. Va con las 2 rodajas de pan.',
    items: [['lechuga', 100], ['tomate', 1], ['huevo', 2], ['atun-natural', 1], ['choclo', 50], ['aceite', 5], ['pan-integral', 2]],
  },
  {
    slug: 'tortilla-papa-atun', name: 'Tortilla de papa y atún', minutes: 15, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Papa en cubitos en un bowl con un chorrito de agua, tapado, al microondas 5–6 min.\nBatís los huevos con la papa, el atún y sal.\nSartén antiadherente con el aceite, fuego bajo, 4–5 min por lado. Para dar vuelta, usá un plato.',
    items: [['papa', 250], ['huevo', 3], ['atun-natural', 0.5], ['aceite', 5]],
  },
  {
    slug: 'fideos-salsa-pollo', name: 'Fideos con salsa y pollo', minutes: 12, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Hervís los fideos 9–10 min.\nCalentás la salsa con la pata muslo cocida y desmenuzada, sin piel.\nMezclás y queso rallado arriba. Sin pan.',
    items: [['fideos', 70], ['salsa-bolonesa', 150], ['pata-muslo', 1], ['queso-rallado', 10]],
  },
  {
    slug: 'guiso-lentejas', name: 'Guiso de lentejas con pollo', minutes: 35, servings: 3,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Rehogás la cebolla picada con el aceite, 3 min.\nAgregás las lentejas (sin remojo), el puré de tomate, el caldo, la calabaza en cubos, el pollo desmenuzado, pimentón y 1 L de agua.\n30 min a fuego medio, revolviendo cada tanto. La calabaza se deshace y no se nota.\nLo que sobra va al freezer.',
    items: [['lentejas', 250], ['cebolla', 1], ['pure-tomate', 520], ['caldo', 1], ['calabaza', 300], ['pata-muslo', 2], ['aceite', 5]],
  },
  {
    slug: 'omelette-queso', name: 'Omelette de queso con ensalada', minutes: 5, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: false,
    steps: 'Batís los huevos con sal.\nSartén antiadherente, huevos, queso en el medio y doblás: 3–4 min.\nEnsalada de lechuga y tomate al lado, con las 2 rodajas de pan.',
    items: [['huevo', 3], ['queso-cremoso', 30], ['lechuga', 80], ['tomate', 1], ['pan-integral', 2]],
  },
  {
    slug: 'desayuno-sandwich-huevo', name: 'Sándwich de queso, huevos duros y banana', minutes: 5, servings: 1,
    meal_types: ['desayuno'], portable: true,
    steps: 'Sándwich con las 2 rodajas de pan y el queso cremoso.\n2 huevos duros (10 min de hervor; podés dejarlos hechos de antes) y la banana.',
    items: [['pan-integral', 2], ['queso-cremoso', 30], ['huevo', 2], ['banana', 1]],
  },
  {
    slug: 'desayuno-huevos-revueltos', name: 'Huevos revueltos con tostadas y manzana', minutes: 5, servings: 1,
    meal_types: ['desayuno'], portable: false,
    steps: 'Batís los huevos con sal en una taza: 1 min 30 s al microondas, revolviendo a la mitad.\nTostás el pan. La manzana, de postre.',
    items: [['huevo', 2], ['pan-integral', 2], ['manzana', 1]],
  },
  {
    slug: 'desayuno-avena', name: 'Avena con leche y banana', minutes: 3, servings: 1,
    meal_types: ['desayuno'], portable: false,
    steps: 'Avena con la leche, 2 min al microondas.\nBanana cortada arriba.',
    items: [['avena', 40], ['leche', 250], ['banana', 1]],
  },
  {
    slug: 'merienda-leche-mani', name: 'Leche con maní', minutes: 1, servings: 1,
    meal_types: ['merienda'], portable: true,
    steps: '1 vaso de leche sola, con café o en mate cocido, sin azúcar.\n60 g de maní con cáscara, medido.',
    items: [['leche', 250], ['mani-cascara', 60]],
  },
  {
    slug: 'merienda-yogur-mani', name: 'Yogur natural con maní', minutes: 1, servings: 1,
    meal_types: ['merienda'], portable: true,
    steps: '200 g de yogur natural.\n60 g de maní con cáscara, medido.',
    items: [['yogur-natural', 200], ['mani-cascara', 60]],
  },
  {
    slug: 'merienda-banana-mani', name: 'Banana con maní y mate', minutes: 1, servings: 1,
    meal_types: ['merienda'], portable: true,
    steps: '1 banana y 60 g de maní con cáscara, medido. Mate sin azúcar.',
    items: [['banana', 1], ['mani-cascara', 60]],
  },
]

// ---------------------------------------------------------------------------
// Segunda tanda: bebidas, más alimentos y más recetas
// ---------------------------------------------------------------------------
export const alimentosNuevos = [
  // Bebidas (valores cada 100 ml)
  ['agua', 'Agua', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['soda', 'Soda o agua con gas', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['agua-saborizada', 'Agua saborizada con azúcar', 'ml', null, null, 18, 0, 4.5, 0, 'Bebidas'],
  ['agua-saborizada-zero', 'Agua saborizada sin azúcar', 'ml', null, null, 1, 0, 0.2, 0, 'Bebidas'],
  ['tonica', 'Agua tónica', 'ml', null, null, 34, 0, 8.5, 0, 'Bebidas'],
  ['jugo-polvo', 'Jugo en polvo preparado', 'ml', null, null, 10, 0, 2.3, 0, 'Bebidas'],
  ['jugo-caja', 'Jugo de caja o botella', 'ml', null, null, 45, 0.3, 11, 0, 'Bebidas'],
  ['limonada', 'Limonada con azúcar', 'ml', null, null, 40, 0, 10, 0, 'Bebidas'],
  ['isotonica', 'Bebida isotónica (tipo Gatorade)', 'ml', null, null, 24, 0, 6, 0, 'Bebidas'],
  ['energizante', 'Energizante (tipo Speed o Red Bull)', 'ml', null, null, 45, 0, 11, 0, 'Bebidas'],
  ['energizante-zero', 'Energizante sin azúcar', 'ml', null, null, 3, 0, 0, 0, 'Bebidas'],
  ['cafe-con-leche', 'Café con leche', 'ml', null, null, 25, 1.6, 2.4, 0.8, 'Bebidas'],
  ['chocolatada', 'Leche chocolatada', 'ml', null, null, 75, 3, 12, 1.8, 'Bebidas'],
  ['licuado-banana', 'Licuado de banana con leche', 'ml', null, null, 70, 2.5, 12, 1.3, 'Bebidas'],
  ['yogur-bebible', 'Yogur bebible', 'ml', null, null, 75, 2.8, 12.5, 1.5, 'Bebidas'],
  ['cerveza-negra', 'Cerveza negra', 'ml', null, null, 55, 0.5, 5, 0, 'Bebidas'],
  ['cerveza-ipa', 'Cerveza IPA o artesanal', 'ml', null, null, 55, 0.5, 4.5, 0, 'Bebidas'],
  ['cerveza-sin-alcohol', 'Cerveza sin alcohol', 'ml', null, null, 25, 0.3, 5.5, 0, 'Bebidas'],
  ['vino-blanco', 'Vino blanco o rosado', 'ml', null, null, 80, 0, 2, 0, 'Bebidas'],
  ['espumante', 'Espumante o champagne', 'ml', null, null, 78, 0, 1.5, 0, 'Bebidas'],
  ['sidra', 'Sidra', 'ml', null, null, 50, 0, 5, 0, 'Bebidas'],
  ['fernet', 'Fernet solo', 'ml', null, null, 240, 0, 8, 0, 'Bebidas'],
  ['bebida-blanca', 'Vodka, gin, whisky o ron (solo)', 'ml', null, null, 222, 0, 0, 0, 'Bebidas'],
  ['gin-tonic', 'Gin tonic', 'ml', null, null, 80, 0, 6.4, 0, 'Bebidas'],
  ['ron-cola', 'Ron con coca (cuba libre)', 'ml', null, null, 75, 0, 7.5, 0, 'Bebidas'],
  ['campari', 'Campari u otro bitter (solo)', 'ml', null, null, 230, 0, 24, 0, 'Bebidas'],
  ['aperol-spritz', 'Aperol spritz', 'ml', null, null, 90, 0, 8, 0, 'Bebidas'],
  ['vermut', 'Vermut (Cinzano, Gancia)', 'ml', null, null, 140, 0, 12, 0, 'Bebidas'],
  ['trago-dulce', 'Trago dulce (daiquiri, mojito, caipirinha)', 'ml', null, null, 120, 0, 12, 0, 'Bebidas'],
  ['licor', 'Licor dulce', 'ml', null, null, 280, 0, 30, 0, 'Bebidas'],

  ['pechuga-cruda', 'Pechuga de pollo (cruda)', 'g', null, null, 110, 23, 0, 1.5, 'Proteínas'],
  ['carne-picada-cruda', 'Carne picada (cruda)', 'g', null, null, 200, 19, 0, 13, 'Proteínas'],
  ['bife-nalga', 'Bife de nalga o cuadrada (crudo)', 'g', null, null, 130, 21, 0, 5, 'Proteínas'],
  ['milanesa-carne', 'Milanesa de carne al horno', 'u', 120, 'unidad', 240, 20, 12, 12, 'Proteínas'],
  ['filet-merluza', 'Filet de merluza (crudo)', 'g', null, null, 85, 18, 0, 1, 'Proteínas'],
  ['garbanzos', 'Garbanzos en lata', 'g', null, null, 120, 7, 18, 2, 'Proteínas'],
  ['milanesa-soja', 'Milanesa de soja', 'u', 85, 'unidad', 200, 15, 15, 8, 'Proteínas'],

  ['polenta', 'Polenta (harina de maíz)', 'g', null, null, 350, 8, 77, 1.5, 'Carbohidratos'],
  ['tapa-tarta', 'Tapa de tarta', 'u', 200, 'unidad', 300, 6, 45, 10, 'Carbohidratos'],
  ['galleta-arroz', 'Galleta de arroz', 'u', 9, 'unidad', 385, 8, 81, 3, 'Carbohidratos'],
  ['pan-rallado', 'Pan rallado', 'g', null, null, 370, 11, 73, 3, 'Carbohidratos'],

  ['palta', 'Palta', 'u', 150, 'unidad', 160, 2, 9, 15, 'Verduras'],
  ['acelga', 'Acelga o espinaca', 'g', null, null, 22, 2.5, 3.5, 0.3, 'Verduras'],
  ['brocoli', 'Brócoli', 'g', null, null, 34, 2.8, 7, 0.4, 'Verduras'],

  ['pera', 'Pera', 'u', 150, 'unidad', 57, 0.4, 15, 0.1, 'Frutas'],
  ['durazno', 'Durazno', 'u', 130, 'unidad', 39, 0.9, 10, 0.3, 'Frutas'],
  ['frutilla', 'Frutillas', 'g', null, null, 32, 0.7, 7.7, 0.3, 'Frutas'],
  ['uva', 'Uvas', 'g', null, null, 69, 0.7, 18, 0.2, 'Frutas'],

  ['queso-port-salut', 'Queso port salut light', 'g', null, null, 230, 24, 2, 14, 'Lácteos'],
  ['ricota', 'Ricota', 'g', null, null, 150, 11, 3, 10, 'Lácteos'],
  ['crema', 'Crema de leche', 'g', null, null, 340, 2, 3, 35, 'Lácteos'],
  ['yogur-saborizado', 'Yogur saborizado', 'g', null, null, 90, 3.5, 14, 2.5, 'Lácteos'],

  ['salsa-soja', 'Salsa de soja', 'ml', null, null, 55, 8, 5, 0, 'Despensa'],
  ['mermelada', 'Mermelada', 'g', null, null, 250, 0.4, 62, 0, 'Despensa'],
  ['mermelada-light', 'Mermelada light', 'g', null, null, 120, 0.4, 30, 0, 'Despensa'],
  ['cacao', 'Cacao en polvo azucarado', 'g', null, null, 380, 4, 88, 2.5, 'Despensa'],
  ['aceitunas', 'Aceitunas', 'g', null, null, 145, 1, 4, 15, 'Despensa'],
  ['ketchup', 'Ketchup', 'g', null, null, 100, 1.2, 25, 0.1, 'Despensa'],

  ['nueces', 'Nueces', 'g', null, null, 650, 15, 14, 65, 'Snacks'],
  ['almendras', 'Almendras', 'g', null, null, 580, 21, 22, 50, 'Snacks'],
  ['barrita-cereal', 'Barrita de cereal', 'u', 23, 'unidad', 390, 6, 70, 9, 'Snacks'],
  ['turron', 'Turrón de maní', 'u', 25, 'unidad', 400, 9, 70, 10, 'Snacks'],
  ['papas-paquete', 'Papas fritas de paquete', 'g', null, null, 540, 6, 52, 34, 'Snacks'],

  ['sandwich-miga', 'Sándwich de miga', 'u', 60, 'unidad', 250, 9, 28, 11, 'Comidas hechas'],
  ['pancho', 'Pancho', 'u', 150, 'unidad', 250, 9, 24, 13, 'Comidas hechas'],
  ['choripan', 'Choripán', 'u', 250, 'unidad', 300, 13, 20, 18, 'Comidas hechas'],
  ['asado', 'Asado (carne)', 'g', null, null, 280, 24, 0, 20, 'Comidas hechas'],
  ['tarta-porcion', 'Tarta de jamón y queso (porción)', 'u', 150, 'porción', 250, 10, 20, 14, 'Comidas hechas'],
  ['sushi', 'Sushi (pieza)', 'u', 30, 'pieza', 150, 5, 25, 3, 'Comidas hechas'],
  ['wrap-comprado', 'Wrap de pollo comprado (estimado)', 'u', 300, 'unidad', 200, 11, 20, 8, 'Comidas hechas'],
]

const P = ['almuerzo', 'cena']
const r = (slug, name, minutes, servings, meal_types, portable, steps, items) => ({ slug, name, minutes, servings, meal_types, portable, steps, items })

export const recetasNuevas = [
  // Desayunos
  r('desayuno-tostadas-untable', 'Tostadas con queso untable y mermelada light', 3, 1, ['desayuno'], false,
    'Tostás el pan.\nUntás el queso y la mermelada. Va con café con leche o mate.',
    [['pan-integral', 2], ['queso-untable', 30], ['mermelada-light', 20], ['leche', 200]]),
  r('desayuno-yogur-avena', 'Yogur con avena y banana', 2, 1, ['desayuno'], true,
    'Mezclás el yogur con la avena.\nBanana cortada arriba. Se puede dejar armado la noche anterior.',
    [['yogur-natural', 200], ['avena', 40], ['banana', 1]]),
  r('desayuno-copos', 'Copos de maíz con leche y banana', 2, 1, ['desayuno'], false,
    'Copos con la leche fría o tibia.\nBanana cortada arriba.',
    [['copos-maiz', 40], ['leche', 250], ['banana', 1]]),
  r('desayuno-tostado', 'Tostado de jamón y queso con café con leche', 5, 1, ['desayuno'], true,
    'Armás el sándwich con el jamón y el queso.\nLo tostás en sartén o tostadora, 2 min por lado.\nCafé con la leche.',
    [['pan-integral', 2], ['jamon-cocido', 40], ['queso-cremoso', 30], ['leche', 150]]),
  r('desayuno-palta-huevo', 'Tostadas con palta y huevo', 6, 1, ['desayuno'], false,
    'Tostás el pan y pisás la media palta arriba, con sal.\nHuevos revueltos o a la plancha, sin aceite.',
    [['pan-integral', 2], ['palta', 0.5], ['huevo', 2]]),
  r('desayuno-licuado', 'Licuado de banana, leche y avena', 3, 1, ['desayuno'], false,
    'Todo a la licuadora, 30 segundos. Sin azúcar.',
    [['banana', 1], ['leche', 300], ['avena', 30]]),

  // Meriendas
  r('merienda-tostadas', 'Tostadas con queso untable', 3, 1, ['merienda'], true,
    'Tostás el pan y untás el queso. Con mate o café sin azúcar.',
    [['pan-integral', 2], ['queso-untable', 40]]),
  r('merienda-yogur-fruta', 'Yogur natural con manzana y avena', 2, 1, ['merienda'], true,
    'Yogur con la manzana en cubos y la avena.',
    [['yogur-natural', 200], ['manzana', 1], ['avena', 20]]),
  r('merienda-sandwich', 'Sándwich de jamón y queso', 2, 1, ['merienda'], true,
    'Pan, jamón y queso. Frío o tostado.',
    [['pan-integral', 2], ['jamon-cocido', 40], ['queso-cremoso', 30]]),
  r('merienda-fruta-nueces', 'Manzana con nueces', 1, 1, ['merienda'], true,
    '1 manzana y un puñado chico de nueces (25 g).',
    [['manzana', 1], ['nueces', 25]]),
  r('merienda-galletas-arroz', 'Café con leche y galletas de arroz con queso', 3, 1, ['merienda'], false,
    'Café con la leche, sin azúcar.\nGalletas de arroz con el queso untable.',
    [['leche', 200], ['galleta-arroz', 3], ['queso-untable', 30]]),
  r('merienda-huevos-banana', 'Huevos duros y banana', 1, 1, ['merienda'], true,
    '2 huevos duros (hechos de antes) y 1 banana.',
    [['huevo', 2], ['banana', 1]]),

  // Almuerzos y cenas
  r('pechuga-ensalada', 'Pechuga a la plancha con ensalada', 12, 1, P, true,
    'Pechuga fileteada fina, con sal y limón, a la plancha: 4–5 min por lado.\nEnsalada de lechuga y tomate con el aceite.\nVa con las 2 rodajas de pan.',
    [['pechuga-cruda', 180], ['lechuga', 100], ['tomate', 1], ['aceite', 10], ['pan-integral', 2]]),
  r('pechuga-arroz', 'Pechuga con arroz', 20, 1, P, true,
    'Hervís el arroz.\nPechuga en cubos o fileteada, a la plancha con el aceite, sal y pimentón.\nTomate en rodajas al lado.',
    [['pechuga-cruda', 180], ['arroz', 70], ['tomate', 1], ['aceite', 5]]),
  r('pechuga-pure', 'Pechuga con puré de papa', 25, 1, P, true,
    'Papas en cubos, hervidas 15 min. Las pisás con la leche y sal.\nPechuga a la plancha con el aceite, 4–5 min por lado.',
    [['pechuga-cruda', 180], ['papa', 300], ['leche', 50], ['aceite', 5]]),
  r('salteado-pollo', 'Salteado de pollo con arroz y verduras', 20, 1, P, true,
    'Hervís el arroz.\nPollo en tiras a la sartén con el aceite, 5 min.\nSumás zanahoria rallada, morrón y cebolla en tiras, 5 min más.\nSalsa de soja y mezclás con el arroz.',
    [['pechuga-cruda', 150], ['arroz', 70], ['zanahoria', 1], ['morron', 0.5], ['cebolla', 0.5], ['salsa-soja', 15], ['aceite', 10]]),
  r('pollo-brocoli', 'Pollo con brócoli y arroz', 20, 1, P, true,
    'Hervís el arroz y el brócoli (5 min, que quede firme).\nPollo en cubos a la sartén con el aceite.\nJuntás todo con la salsa de soja.',
    [['pechuga-cruda', 180], ['brocoli', 200], ['arroz', 60], ['salsa-soja', 10], ['aceite', 5]]),
  r('pata-muslo-calabaza', 'Pata muslo al horno con calabaza', 55, 4, P, true,
    'Horno a 200 °C. Pollo con sal, pimentón y ajo en una placa: 50–55 min.\nCalabaza en cubos grandes con el aceite, en la misma placa o en otra: 35–40 min.\nPorción: 1 pata sin piel con calabaza.',
    [['pata-muslo', 4], ['calabaza', 800], ['aceite', 10]]),
  r('fideos-bolonesa', 'Fideos con boloñesa casera', 25, 3, P, true,
    'Rehogás la cebolla picada con el aceite y dorás la carne.\nAgregás el puré de tomate, sal y orégano: 15 min a fuego bajo.\nHervís los fideos y servís con queso rallado. Sin pan.',
    [['fideos', 240], ['carne-picada-cruda', 300], ['pure-tomate', 520], ['cebolla', 1], ['aceite', 10], ['queso-rallado', 30]]),
  r('hamburguesas-caseras', 'Hamburguesas caseras con ensalada', 20, 2, P, true,
    'Mezclás la carne con el huevo, el pan rallado, sal y ajo. Armás 4 hamburguesas.\nA la plancha o al horno, 4–5 min por lado.\nEnsalada de lechuga y tomate con el aceite.',
    [['carne-picada-cruda', 300], ['huevo', 1], ['pan-rallado', 20], ['lechuga', 150], ['tomate', 2], ['aceite', 10]]),
  r('pastel-papa', 'Pastel de papa', 50, 4, P, true,
    'Hervís las papas y hacés un puré con la leche.\nRehogás la cebolla con el aceite, dorás la carne y sumás los huevos duros picados.\nEn una fuente: carne abajo, puré arriba y queso rallado. Horno 200 °C, 15 min.',
    [['carne-picada-cruda', 500], ['papa', 1000], ['cebolla', 1], ['huevo', 2], ['leche', 100], ['aceite', 10], ['queso-rallado', 40]]),
  r('bife-ensalada', 'Bife a la plancha con ensalada', 10, 1, P, true,
    'Bife a la plancha bien caliente, 3–4 min por lado, sal al final.\nEnsalada de lechuga y tomate con el aceite.\nVa con las 2 rodajas de pan.',
    [['bife-nalga', 180], ['lechuga', 100], ['tomate', 1], ['aceite', 10], ['pan-integral', 2]]),
  r('bife-pure-calabaza', 'Bife con puré de calabaza', 25, 1, P, true,
    'Calabaza en cubos, hervida o al microondas, 12–15 min. La pisás con sal y el queso rallado.\nBife a la plancha con el aceite, 3–4 min por lado.',
    [['bife-nalga', 180], ['calabaza', 300], ['aceite', 5], ['queso-rallado', 10]]),
  r('milanesa-carne-pure', 'Milanesa de carne al horno con puré', 25, 1, P, true,
    'Milanesa al horno a 200 °C, 20 min, dándola vuelta a la mitad.\nPuré: papas hervidas y pisadas con la leche.\nTomate en rodajas al lado.',
    [['milanesa-carne', 1], ['papa', 300], ['leche', 50], ['tomate', 1]]),
  r('arroz-atun-huevo', 'Arroz con atún y huevo', 15, 1, P, true,
    'Hervís el arroz y el huevo (10 min).\nMezclás el arroz con el atún escurrido, las arvejas y el aceite.\nHuevo duro picado arriba.',
    [['arroz', 80], ['atun-natural', 1], ['huevo', 1], ['arvejas', 60], ['aceite', 5]]),
  r('ensalada-arroz-atun', 'Ensalada de arroz, atún y choclo', 15, 1, P, true,
    'Hervís el arroz y lo enfriás con agua.\nMezclás con el atún, el choclo, el tomate en cubos y el huevo duro.\nAceite, sal y limón o vinagre.',
    [['arroz', 70], ['atun-natural', 1], ['choclo', 80], ['tomate', 1], ['huevo', 1], ['aceite', 5]]),
  r('ensalada-lentejas', 'Ensalada de lentejas, huevo y tomate', 30, 1, P, true,
    'Hervís las lentejas 25 min, sin remojo, y las escurrís.\nMezclás con el tomate en cubos y los huevos duros.\nAceite, sal y vinagre.',
    [['lentejas', 80], ['huevo', 2], ['tomate', 1], ['aceite', 10]]),
  r('ensalada-garbanzos', 'Ensalada de garbanzos, atún y tomate', 5, 1, P, true,
    'Escurrís los garbanzos y el atún.\nMezclás con el tomate en cubos, el aceite, sal y limón.',
    [['garbanzos', 200], ['atun-natural', 1], ['tomate', 1], ['aceite', 10]]),
  r('ensalada-cesar', 'Ensalada César simple', 15, 1, P, true,
    'Pechuga a la plancha y cortada en tiras.\nPan tostado en cubos.\nLechuga, pollo, pan, huevo duro y queso rallado, con el aceite y limón.',
    [['pechuga-cruda', 150], ['lechuga', 150], ['queso-rallado', 20], ['pan-integral', 2], ['huevo', 1], ['aceite', 10]]),
  r('tarta-atun', 'Tarta de atún', 40, 3, P, true,
    'Tapa en una tartera. Mezclás el atún, la cebolla rehogada, los huevos batidos y el queso en cubos.\nRelleno adentro, tomate en rodajas arriba.\nHorno a 180 °C, 30 min.',
    [['tapa-tarta', 1], ['atun-natural', 2], ['huevo', 3], ['cebolla', 1], ['queso-cremoso', 100], ['tomate', 1]]),
  r('tarta-jamon-queso', 'Tarta de jamón y queso', 35, 3, P, true,
    'Tapa en una tartera. Jamón y queso en capas.\nHuevos batidos con sal por arriba.\nHorno a 180 °C, 25–30 min.',
    [['tapa-tarta', 1], ['jamon-cocido', 150], ['queso-cremoso', 150], ['huevo', 3]]),
  r('tarta-acelga', 'Tarta de acelga y ricota', 40, 3, P, true,
    'Hervís la acelga 3 min, la escurrís bien y la picás.\nMezclás con la ricota, los huevos y el queso rallado.\nRelleno sobre la tapa. Horno a 180 °C, 30 min.',
    [['tapa-tarta', 1], ['acelga', 400], ['ricota', 250], ['huevo', 2], ['queso-rallado', 30]]),
  r('fideos-tuco', 'Fideos con tuco, huevo y queso', 15, 1, P, true,
    'Hervís los fideos y los huevos.\nCalentás el puré de tomate con el aceite, sal y orégano, 5 min.\nFideos con la salsa, huevo duro picado y queso rallado. Sin pan.',
    [['fideos', 90], ['pure-tomate', 150], ['huevo', 2], ['queso-rallado', 20], ['aceite', 5]]),
  r('revuelto-zapallitos', 'Revuelto de zapallitos con huevo', 15, 1, P, false,
    'Cebolla y zapallitos en cubos chicos a la sartén con el aceite, 8 min.\nAgregás los huevos batidos y revolvés hasta que cuajen.\nQueso rallado arriba. Va con las 2 rodajas de pan.',
    [['zapallito', 2], ['huevo', 3], ['cebolla', 0.5], ['queso-rallado', 15], ['aceite', 5], ['pan-integral', 2]]),
  r('merluza-papas', 'Merluza al horno con papas', 30, 1, P, true,
    'Papas en rodajas finas en una placa con el aceite y sal: 15 min a 200 °C.\nSumás la merluza arriba con sal y limón: 12–15 min más.',
    [['filet-merluza', 250], ['papa', 300], ['aceite', 10]]),
  r('merluza-ensalada', 'Merluza a la plancha con ensalada', 12, 1, P, false,
    'Merluza a la plancha con sal y limón, 3–4 min por lado.\nEnsalada de lechuga y tomate con el aceite.\nVa con las 2 rodajas de pan.',
    [['filet-merluza', 250], ['lechuga', 100], ['tomate', 1], ['aceite', 10], ['pan-integral', 2]]),
  r('polenta-salsa', 'Polenta con salsa, queso y huevo', 12, 1, P, false,
    'Polenta en lluvia sobre agua hirviendo con sal, revolviendo 3–5 min.\nCalentás el puré de tomate con orégano.\nPolenta, salsa, queso en cubos, huevo duro y queso rallado.',
    [['polenta', 80], ['pure-tomate', 150], ['queso-cremoso', 50], ['huevo', 1], ['queso-rallado', 10]]),
  r('guiso-arroz-pollo', 'Guiso de arroz con pollo', 35, 3, P, true,
    'Rehogás la cebolla y la zanahoria rallada con el aceite.\nSumás el pollo sin piel, el puré de tomate, el caldo y 700 ml de agua: 15 min.\nAgregás el arroz y cocinás 15 min más. Desmenuzás el pollo.',
    [['arroz', 240], ['pata-muslo', 3], ['pure-tomate', 520], ['cebolla', 1], ['zanahoria', 1], ['caldo', 1], ['aceite', 10]]),
  r('guiso-fideos-carne', 'Guiso de fideos con carne', 30, 3, P, true,
    'Rehogás la cebolla y la zanahoria rallada con el aceite y dorás la carne.\nSumás el puré de tomate, el caldo y 700 ml de agua: 10 min.\nAgregás los fideos y cocinás hasta que estén.',
    [['fideos', 240], ['carne-picada-cruda', 300], ['pure-tomate', 520], ['cebolla', 1], ['zanahoria', 1], ['caldo', 1], ['aceite', 10]]),
  r('wrap-pollo', 'Wrap de pollo', 15, 1, P, true,
    'Pechuga en tiras a la plancha.\nUntás las rapiditas con el queso y armás con el pollo, la lechuga y el tomate.',
    [['rapidita', 2], ['pechuga-cruda', 150], ['lechuga', 50], ['tomate', 1], ['queso-untable', 30]]),
  r('wrap-atun', 'Wrap de atún y huevo', 5, 1, P, true,
    'Untás las rapiditas con el queso.\nAtún escurrido, huevo duro picado, lechuga y tomate. Enrollás.',
    [['rapidita', 2], ['atun-natural', 1], ['huevo', 1], ['lechuga', 50], ['tomate', 1], ['queso-untable', 30]]),
  r('sandwich-pollo', 'Sándwich de pollo, huevo y tomate', 12, 1, P, true,
    'Pechuga a la plancha.\nArmás 2 sándwiches con el pollo, huevo duro, tomate, lechuga y mostaza.',
    [['pan-integral', 4], ['pechuga-cruda', 120], ['huevo', 1], ['tomate', 1], ['lechuga', 30], ['mostaza', 10]]),
  r('tortilla-papa', 'Tortilla de papa', 25, 2, P, true,
    'Papas en cubitos al microondas con un chorrito de agua, tapadas, 8 min.\nCebolla rehogada con parte del aceite. Mezclás todo con los huevos batidos y sal.\nSartén con el resto del aceite, fuego bajo, 5 min por lado.\nVa con tomate en rodajas.',
    [['papa', 500], ['huevo', 5], ['cebolla', 1], ['aceite', 15], ['tomate', 2]]),
  r('omelette-jamon-queso', 'Omelette de jamón y queso con ensalada', 6, 1, P, false,
    'Batís los huevos con sal.\nSartén antiadherente, huevos, jamón y queso en el medio y doblás: 3–4 min.\nEnsalada de lechuga y tomate, con las 2 rodajas de pan.',
    [['huevo', 3], ['jamon-cocido', 40], ['queso-cremoso', 30], ['lechuga', 80], ['tomate', 1], ['pan-integral', 2]]),
  r('arroz-huevo-arvejas', 'Arroz con huevo y arvejas', 15, 1, P, true,
    'Hervís el arroz.\nHuevos revueltos en la sartén con el aceite.\nMezclás arroz, huevo y arvejas, con sal y pimentón.',
    [['arroz', 90], ['huevo', 3], ['arvejas', 100], ['aceite', 5]]),
  r('pizzetas-rapidita', 'Pizzetas de rapidita', 10, 1, P, false,
    'Rapiditas en una placa. Puré de tomate con orégano, queso y jamón arriba.\nHorno fuerte 6–8 min, hasta que se derrita el queso.',
    [['rapidita', 2], ['pure-tomate', 80], ['queso-cremoso', 80], ['jamon-cocido', 40]]),
  r('milanesas-soja-arroz', 'Milanesas de soja con arroz y ensalada', 20, 1, P, true,
    'Milanesas al horno a 200 °C, 15 min, dándolas vuelta.\nHervís el arroz.\nEnsalada de lechuga y tomate con el aceite.',
    [['milanesa-soja', 2], ['arroz', 60], ['lechuga', 80], ['tomate', 1], ['aceite', 5]]),
]

// ---------------------------------------------------------------------------
// Tercera tanda: infusiones (valores cada 100 ml, sin endulzar: el azúcar se carga aparte)
// ---------------------------------------------------------------------------
export const infusiones = [
  ['terere', 'Tereré con agua', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['terere-jugo', 'Tereré con jugo', 'ml', null, null, 10, 0, 2.3, 0, 'Bebidas'],
  ['mate-cocido', 'Mate cocido', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['mate-cocido-leche', 'Mate cocido con leche', 'ml', null, null, 22, 1.5, 2.3, 0.7, 'Bebidas'],
  ['cafe', 'Café negro', 'ml', null, null, 1, 0.1, 0, 0, 'Bebidas'],
  ['cortado', 'Café cortado', 'ml', null, null, 10, 0.6, 0.9, 0.3, 'Bebidas'],
  ['capuchino', 'Capuchino', 'ml', null, null, 40, 2, 4.5, 1.5, 'Bebidas'],
  ['te', 'Té', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['te-leche', 'Té con leche', 'ml', null, null, 12, 0.8, 1.2, 0.4, 'Bebidas'],
]

// Bebidas con alcohol: no cuentan para el objetivo de líquido
export const conAlcohol = ['cerveza', 'cerveza-negra', 'cerveza-ipa', 'vino', 'vino-blanco', 'espumante', 'sidra', 'fernet', 'fernet-coca',
  'bebida-blanca', 'gin-tonic', 'ron-cola', 'campari', 'aperol-spritz', 'vermut', 'trago-dulce', 'licor']

export const foods = [...alimentosBase, ...alimentosNuevos, ...infusiones]
export const recipes = [...recetasBase, ...recetasNuevas]
