// Datos base de Tupper: alimentos y recetas comunes a todos los usuarios.
// kcal, proteina, carbohidratos y grasa son cada 100 g (o 100 ml).
// Si la unidad es 'u', unit_grams dice cuantos gramos pesa una unidad.
// Formato: [slug, nombre, unidad, gramos por unidad, etiqueta, kcal, prot, carbs, grasa, categoria]

const alimentosBase = [
  ['pata-muslo', 'Pata muslo (sin piel)', 'u', 150, 'pieza', 185, 25, 0, 9, 'Carnes y huevos'],
  ['pechuga-pollo', 'Pechuga de pollo cocida', 'g', null, null, 165, 31, 0, 3.6, 'Carnes y huevos'],
  ['milanesa-pollo', 'Milanesa de pollo al horno', 'u', 110, 'unidad', 230, 16, 14, 12, 'Carnes y huevos'],
  ['atun-natural', 'Atún al natural (lata 170 g)', 'u', 120, 'lata', 110, 25, 0, 1, 'Pescados'],
  ['huevo', 'Huevo', 'u', 50, 'unidad', 150, 12.5, 1, 10.5, 'Carnes y huevos'],
  ['carne-magra', 'Carne vacuna magra cocida', 'g', null, null, 200, 28, 0, 9, 'Carnes y huevos'],
  ['carne-picada', 'Carne picada especial cocida', 'g', null, null, 230, 26, 0, 14, 'Carnes y huevos'],
  ['lentejas', 'Lentejas secas', 'g', null, null, 340, 24, 60, 1, 'Legumbres'],
  ['jamon-cocido', 'Jamón cocido', 'g', null, null, 110, 18, 1.5, 3.5, 'Carnes y huevos'],
  ['merluza', 'Merluza cocida', 'g', null, null, 95, 20, 0, 1.5, 'Pescados'],

  ['arroz', 'Arroz largo fino (crudo)', 'g', null, null, 360, 7, 79, 0.6, 'Pastas y arroz'],
  ['fideos', 'Fideos secos (crudos)', 'g', null, null, 355, 12, 72, 1.5, 'Pastas y arroz'],
  ['avena', 'Avena', 'g', null, null, 380, 13, 62, 7, 'Cereales'],
  ['pan-integral', 'Pan lactal integral', 'u', 25, 'rodaja', 250, 10, 43, 3.5, 'Panadería'],
  ['pan-frances', 'Pan francés', 'g', null, null, 270, 9, 55, 1.5, 'Panadería'],
  ['papa', 'Papa', 'g', null, null, 80, 2, 17, 0.1, 'Verduras'],
  ['batata', 'Batata', 'g', null, null, 90, 1.6, 20, 0.1, 'Verduras'],
  ['copos-maiz', 'Copos de maíz sin azúcar', 'g', null, null, 370, 7, 84, 0.5, 'Cereales'],
  ['rapidita', 'Tortilla de trigo (rapidita)', 'u', 40, 'unidad', 300, 8, 50, 7, 'Panadería'],

  ['lechuga', 'Lechuga', 'g', null, null, 15, 1.3, 2.9, 0.2, 'Verduras'],
  ['tomate', 'Tomate', 'u', 120, 'unidad', 18, 0.9, 3.9, 0.2, 'Verduras'],
  ['cebolla', 'Cebolla', 'u', 120, 'unidad', 40, 1.1, 9, 0.1, 'Verduras'],
  ['morron', 'Morrón', 'u', 150, 'unidad', 27, 1, 6, 0.3, 'Verduras'],
  ['calabaza', 'Calabaza', 'g', null, null, 30, 1, 7, 0.1, 'Verduras'],
  ['zapallito', 'Zapallito', 'u', 150, 'unidad', 17, 1.2, 3, 0.3, 'Verduras'],
  ['zanahoria', 'Zanahoria', 'u', 80, 'unidad', 41, 0.9, 10, 0.2, 'Verduras'],

  ['banana', 'Banana', 'u', 100, 'unidad', 90, 1.1, 23, 0.3, 'Frutas'],
  ['manzana', 'Manzana', 'u', 150, 'unidad', 52, 0.3, 14, 0.2, 'Frutas'],
  ['mandarina', 'Mandarina', 'u', 80, 'unidad', 50, 0.8, 12, 0.3, 'Frutas'],
  ['naranja', 'Naranja', 'u', 150, 'unidad', 47, 0.9, 12, 0.1, 'Frutas'],

  ['leche', 'Leche parcialmente descremada', 'ml', null, null, 45, 3.1, 4.7, 1.5, 'Lácteos'],
  ['leche-entera', 'Leche entera', 'ml', null, null, 60, 3, 4.7, 3, 'Lácteos'],
  ['yogur-natural', 'Yogur natural', 'g', null, null, 62, 3.5, 5, 3, 'Lácteos'],
  ['queso-cremoso', 'Queso cremoso', 'g', null, null, 280, 19, 2, 22, 'Lácteos'],
  ['queso-rallado', 'Queso rallado', 'g', null, null, 390, 33, 3, 27, 'Lácteos'],
  ['queso-untable', 'Queso untable light', 'g', null, null, 130, 9, 4, 9, 'Lácteos'],
  ['manteca', 'Manteca', 'g', null, null, 740, 0.6, 0, 82, 'Lácteos'],
  ['dulce-de-leche', 'Dulce de leche', 'g', null, null, 315, 6, 55, 7, 'Despensa'],

  ['pure-tomate', 'Puré de tomate', 'g', null, null, 30, 1.5, 6, 0.2, 'Salsas y aderezos'],
  ['salsa-bolonesa', 'Salsa boloñesa lista', 'g', null, null, 70, 3, 9, 2.5, 'Salsas y aderezos'],
  ['arvejas', 'Arvejas en lata', 'g', null, null, 70, 4.5, 12, 0.4, 'Enlatados'],
  ['choclo', 'Choclo en lata', 'g', null, null, 85, 2.5, 18, 1, 'Enlatados'],
  ['aceite', 'Aceite', 'ml', null, null, 810, 0, 0, 92, 'Despensa'],
  ['caldo', 'Caldo en cubo', 'u', 10, 'cubo', 200, 10, 20, 8, 'Despensa'],
  ['azucar', 'Azúcar', 'g', null, null, 400, 0, 100, 0, 'Despensa'],
  ['miel', 'Miel', 'g', null, null, 304, 0.3, 82, 0, 'Despensa'],
  ['mayonesa', 'Mayonesa', 'g', null, null, 680, 1, 2, 75, 'Salsas y aderezos'],
  ['mostaza', 'Mostaza', 'g', null, null, 66, 4, 6, 3, 'Salsas y aderezos'],

  ['mani-cascara', 'Maní con cáscara (peso con cáscara)', 'g', null, null, 400, 17, 11, 33, 'Snacks y dulces'],
  ['mani-pelado', 'Maní pelado', 'g', null, null, 590, 25, 16, 49, 'Snacks y dulces'],
  ['criollo', 'Criollo', 'u', 25, 'unidad', 430, 9, 55, 19, 'Panadería'],
  ['galletita-rellena', 'Galletita rellena tipo Oreo', 'u', 11, 'unidad', 480, 5, 70, 20, 'Snacks y dulces'],
  ['galletita-agua', 'Galletita de agua', 'u', 5, 'unidad', 430, 10, 70, 12, 'Panadería'],
  ['alfajor', 'Alfajor de chocolate', 'u', 50, 'unidad', 420, 5, 62, 17, 'Snacks y dulces'],
  ['medialuna', 'Medialuna', 'u', 40, 'unidad', 400, 7, 48, 20, 'Panadería'],
  ['chocolate', 'Chocolate', 'g', null, null, 540, 7, 57, 31, 'Snacks y dulces'],
  ['helado', 'Helado', 'g', null, null, 200, 3.5, 24, 10, 'Congelados'],

  ['lomito', 'Lomito completo (estimado)', 'u', 400, 'unidad', 250, 13, 22, 12, 'Comidas hechas'],
  ['hamburguesa', 'Hamburguesa completa (estimado)', 'u', 250, 'unidad', 260, 14, 20, 14, 'Comidas hechas'],
  ['papas-fritas', 'Papas fritas', 'g', null, null, 300, 3.5, 38, 15, 'Comidas hechas'],
  ['pizza', 'Pizza muzzarella', 'u', 125, 'porción', 260, 11, 30, 10, 'Comidas hechas'],
  ['empanada', 'Empanada de carne', 'u', 80, 'unidad', 280, 11, 27, 14, 'Comidas hechas'],

  ['mate', 'Mate', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['gaseosa', 'Gaseosa común', 'ml', null, null, 42, 0, 10.5, 0, 'Bebidas'],
  ['gaseosa-zero', 'Gaseosa zero', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['jugo-naranja', 'Jugo de naranja', 'ml', null, null, 45, 0.7, 10, 0.2, 'Bebidas'],
  ['cerveza', 'Cerveza', 'ml', null, null, 43, 0.4, 3.5, 0, 'Bebidas'],
  ['fernet-coca', 'Fernet con coca', 'ml', null, null, 80, 0, 9, 0, 'Bebidas'],
  ['vino', 'Vino', 'ml', null, null, 83, 0, 2.5, 0, 'Bebidas'],
]

// Las cantidades de cada ingrediente son para la receta entera (todas las porciones).
const recetasBase = [
  {
    slug: 'pata-muslo-horno', name: 'Pata muslo al horno con papa y batata', minutes: 60, servings: 6,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Horno a 200 °C. Pollo en una placa con sal, pimentón, ajo y orégano: 50–55 min.\nPapas y batatas en cubos, sin pelar, en otra placa con el aceite y sal: 35–40 min, moviéndolas una vez.\nPorción: 1 pata sin piel y un puñado grande de papas y batatas.',
    items: [['pata-muslo', 6], ['papa', 800], ['batata', 400], ['aceite', 15]],
  },
  {
    slug: 'arroz-con-pollo', name: 'Arroz con pollo express', minutes: 15, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Hervís el arroz (o usás 1 taza de arroz ya cocido).\nDesmenuzás la pata muslo cocida, sin piel.\nTodo a una sartén con las arvejas, el choclo y el puré de tomate: 5–7 min revolviendo.',
    items: [['arroz', 70], ['pata-muslo', 1], ['arvejas', 80], ['choclo', 80], ['pure-tomate', 50]],
  },
  {
    slug: 'fideos-con-atun', name: 'Fideos con atún', minutes: 12, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Hervís los fideos 9–10 min.\nMientras, calentás el puré de tomate con el atún escurrido en una sartén.\nMezclás y queso rallado arriba. Sin pan.',
    items: [['fideos', 85], ['atun-natural', 1], ['pure-tomate', 120], ['queso-rallado', 10]],
  },
  {
    slug: 'milanesas-con-ensalada', name: 'Milanesas de pollo con ensalada', minutes: 25, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Horno a 200 °C, 20–25 min, dando vuelta las milanesas a la mitad.\nEnsalada de lechuga y tomate con el aceite, sal y limón o vinagre.',
    items: [['milanesa-pollo', 2], ['lechuga', 80], ['tomate', 1], ['aceite', 5]],
  },
  {
    slug: 'ensalada-completa', name: 'Ensalada completa', minutes: 5, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Cortás la lechuga, el tomate y los huevos duros.\nSumás el atún escurrido y el choclo.\nCondimentás con el aceite, limón o vinagre y sal. Va con las 2 rodajas de pan.',
    items: [['lechuga', 100], ['tomate', 1], ['huevo', 2], ['atun-natural', 1], ['choclo', 50], ['aceite', 5], ['pan-integral', 2]],
  },
  {
    slug: 'tortilla-papa-atun', name: 'Tortilla de papa y atún', minutes: 15, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Papa en cubitos en un bowl con un chorrito de agua, tapado, al microondas 5–6 min.\nBatís los huevos con la papa, el atún y sal.\nSartén antiadherente con el aceite, fuego bajo, 4–5 min por lado. Para dar vuelta, usá un plato.',
    items: [['papa', 250], ['huevo', 3], ['atun-natural', 0.5], ['aceite', 5]],
  },
  {
    slug: 'fideos-salsa-pollo', name: 'Fideos con salsa y pollo', minutes: 12, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Hervís los fideos 9–10 min.\nCalentás la salsa con la pata muslo cocida y desmenuzada, sin piel.\nMezclás y queso rallado arriba. Sin pan.',
    items: [['fideos', 70], ['salsa-bolonesa', 150], ['pata-muslo', 1], ['queso-rallado', 10]],
  },
  {
    slug: 'guiso-lentejas', name: 'Guiso de lentejas con pollo', minutes: 35, servings: 3,
    meal_types: ['almuerzo', 'cena'], portable: true,
    steps: 'Rehogás la cebolla picada con el aceite, 3 min.\nAgregás las lentejas (sin remojo), el puré de tomate, el caldo, la calabaza en cubos, el pollo desmenuzado, pimentón y 1 L de agua.\n30 min a fuego medio, revolviendo cada tanto. La calabaza se deshace y no se nota.\nLo que sobra va al freezer.',
    items: [['lentejas', 250], ['cebolla', 1], ['pure-tomate', 520], ['caldo', 1], ['calabaza', 300], ['pata-muslo', 2], ['aceite', 5]],
  },
  {
    slug: 'omelette-queso', name: 'Omelette de queso con ensalada', minutes: 5, servings: 1,
    meal_types: ['almuerzo', 'cena'], portable: false,
    steps: 'Batís los huevos con sal.\nSartén antiadherente, huevos, queso en el medio y doblás: 3–4 min.\nEnsalada de lechuga y tomate al lado, con las 2 rodajas de pan.',
    items: [['huevo', 3], ['queso-cremoso', 30], ['lechuga', 80], ['tomate', 1], ['pan-integral', 2]],
  },
  {
    slug: 'desayuno-sandwich-huevo', name: 'Sándwich de queso, huevos duros y banana', minutes: 5, servings: 1,
    meal_types: ['desayuno'], portable: true,
    steps: 'Sándwich con las 2 rodajas de pan y el queso cremoso.\n2 huevos duros (10 min de hervor; podés dejarlos hechos de antes) y la banana.',
    items: [['pan-integral', 2], ['queso-cremoso', 30], ['huevo', 2], ['banana', 1]],
  },
  {
    slug: 'desayuno-huevos-revueltos', name: 'Huevos revueltos con tostadas y manzana', minutes: 5, servings: 1,
    meal_types: ['desayuno'], portable: false,
    steps: 'Batís los huevos con sal en una taza: 1 min 30 s al microondas, revolviendo a la mitad.\nTostás el pan. La manzana, de postre.',
    items: [['huevo', 2], ['pan-integral', 2], ['manzana', 1]],
  },
  {
    slug: 'desayuno-avena', name: 'Avena con leche y banana', minutes: 3, servings: 1,
    meal_types: ['desayuno'], portable: false,
    steps: 'Avena con la leche, 2 min al microondas.\nBanana cortada arriba.',
    items: [['avena', 40], ['leche', 250], ['banana', 1]],
  },
  {
    slug: 'merienda-leche-mani', name: 'Leche con maní', minutes: 1, servings: 1,
    meal_types: ['merienda'], portable: true,
    steps: '1 vaso de leche sola, con café o en mate cocido, sin azúcar.\n60 g de maní con cáscara, medido.',
    items: [['leche', 250], ['mani-cascara', 60]],
  },
  {
    slug: 'merienda-yogur-mani', name: 'Yogur natural con maní', minutes: 1, servings: 1,
    meal_types: ['merienda'], portable: true,
    steps: '200 g de yogur natural.\n60 g de maní con cáscara, medido.',
    items: [['yogur-natural', 200], ['mani-cascara', 60]],
  },
  {
    slug: 'merienda-banana-mani', name: 'Banana con maní y mate', minutes: 1, servings: 1,
    meal_types: ['merienda'], portable: true,
    steps: '1 banana y 60 g de maní con cáscara, medido. Mate sin azúcar.',
    items: [['banana', 1], ['mani-cascara', 60]],
  },
]

// ---------------------------------------------------------------------------
// Segunda tanda: bebidas, más alimentos y más recetas
// ---------------------------------------------------------------------------
export const alimentosNuevos = [
  // Bebidas (valores cada 100 ml)
  ['agua', 'Agua', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['soda', 'Soda o agua con gas', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['agua-saborizada', 'Agua saborizada con azúcar', 'ml', null, null, 18, 0, 4.5, 0, 'Bebidas'],
  ['agua-saborizada-zero', 'Agua saborizada sin azúcar', 'ml', null, null, 1, 0, 0.2, 0, 'Bebidas'],
  ['tonica', 'Agua tónica', 'ml', null, null, 34, 0, 8.5, 0, 'Bebidas'],
  ['jugo-polvo', 'Jugo en polvo preparado', 'ml', null, null, 10, 0, 2.3, 0, 'Bebidas'],
  ['jugo-caja', 'Jugo de caja o botella', 'ml', null, null, 45, 0.3, 11, 0, 'Bebidas'],
  ['limonada', 'Limonada con azúcar', 'ml', null, null, 40, 0, 10, 0, 'Bebidas'],
  ['isotonica', 'Bebida isotónica (tipo Gatorade)', 'ml', null, null, 24, 0, 6, 0, 'Bebidas'],
  ['energizante', 'Energizante (tipo Speed o Red Bull)', 'ml', null, null, 45, 0, 11, 0, 'Bebidas'],
  ['energizante-zero', 'Energizante sin azúcar', 'ml', null, null, 3, 0, 0, 0, 'Bebidas'],
  ['cafe-con-leche', 'Café con leche', 'ml', null, null, 25, 1.6, 2.4, 0.8, 'Bebidas'],
  ['chocolatada', 'Leche chocolatada', 'ml', null, null, 75, 3, 12, 1.8, 'Bebidas'],
  ['licuado-banana', 'Licuado de banana con leche', 'ml', null, null, 70, 2.5, 12, 1.3, 'Bebidas'],
  ['yogur-bebible', 'Yogur bebible', 'ml', null, null, 75, 2.8, 12.5, 1.5, 'Bebidas'],
  ['cerveza-negra', 'Cerveza negra', 'ml', null, null, 55, 0.5, 5, 0, 'Bebidas'],
  ['cerveza-ipa', 'Cerveza IPA o artesanal', 'ml', null, null, 55, 0.5, 4.5, 0, 'Bebidas'],
  ['cerveza-sin-alcohol', 'Cerveza sin alcohol', 'ml', null, null, 25, 0.3, 5.5, 0, 'Bebidas'],
  ['vino-blanco', 'Vino blanco o rosado', 'ml', null, null, 80, 0, 2, 0, 'Bebidas'],
  ['espumante', 'Espumante o champagne', 'ml', null, null, 78, 0, 1.5, 0, 'Bebidas'],
  ['sidra', 'Sidra', 'ml', null, null, 50, 0, 5, 0, 'Bebidas'],
  ['fernet', 'Fernet solo', 'ml', null, null, 240, 0, 8, 0, 'Bebidas'],
  ['bebida-blanca', 'Vodka, gin, whisky o ron (solo)', 'ml', null, null, 222, 0, 0, 0, 'Bebidas'],
  ['gin-tonic', 'Gin tonic', 'ml', null, null, 80, 0, 6.4, 0, 'Bebidas'],
  ['ron-cola', 'Ron con coca (cuba libre)', 'ml', null, null, 75, 0, 7.5, 0, 'Bebidas'],
  ['campari', 'Campari u otro bitter (solo)', 'ml', null, null, 230, 0, 24, 0, 'Bebidas'],
  ['aperol-spritz', 'Aperol spritz', 'ml', null, null, 90, 0, 8, 0, 'Bebidas'],
  ['vermut', 'Vermut (Cinzano, Gancia)', 'ml', null, null, 140, 0, 12, 0, 'Bebidas'],
  ['trago-dulce', 'Trago dulce (daiquiri, mojito, caipirinha)', 'ml', null, null, 120, 0, 12, 0, 'Bebidas'],
  ['licor', 'Licor dulce', 'ml', null, null, 280, 0, 30, 0, 'Bebidas'],

  ['pechuga-cruda', 'Pechuga de pollo (cruda)', 'g', null, null, 110, 23, 0, 1.5, 'Carnes y huevos'],
  ['carne-picada-cruda', 'Carne picada (cruda)', 'g', null, null, 200, 19, 0, 13, 'Carnes y huevos'],
  ['bife-nalga', 'Bife de nalga o cuadrada (crudo)', 'g', null, null, 130, 21, 0, 5, 'Carnes y huevos'],
  ['milanesa-carne', 'Milanesa de carne al horno', 'u', 120, 'unidad', 240, 20, 12, 12, 'Carnes y huevos'],
  ['filet-merluza', 'Filet de merluza (crudo)', 'g', null, null, 85, 18, 0, 1, 'Pescados'],
  ['garbanzos', 'Garbanzos en lata', 'g', null, null, 120, 7, 18, 2, 'Enlatados'],
  ['milanesa-soja', 'Milanesa de soja', 'u', 85, 'unidad', 200, 15, 15, 8, 'Congelados'],

  ['polenta', 'Polenta (harina de maíz)', 'g', null, null, 350, 8, 77, 1.5, 'Pastas y arroz'],
  ['tapa-tarta', 'Tapa de tarta', 'u', 200, 'unidad', 300, 6, 45, 10, 'Panadería'],
  ['galleta-arroz', 'Galleta de arroz', 'u', 9, 'unidad', 385, 8, 81, 3, 'Panadería'],
  ['pan-rallado', 'Pan rallado', 'g', null, null, 370, 11, 73, 3, 'Panadería'],

  ['palta', 'Palta', 'u', 150, 'unidad', 160, 2, 9, 15, 'Verduras'],
  ['acelga', 'Acelga o espinaca', 'g', null, null, 22, 2.5, 3.5, 0.3, 'Verduras'],
  ['brocoli', 'Brócoli', 'g', null, null, 34, 2.8, 7, 0.4, 'Verduras'],

  ['pera', 'Pera', 'u', 150, 'unidad', 57, 0.4, 15, 0.1, 'Frutas'],
  ['durazno', 'Durazno', 'u', 130, 'unidad', 39, 0.9, 10, 0.3, 'Frutas'],
  ['frutilla', 'Frutillas', 'g', null, null, 32, 0.7, 7.7, 0.3, 'Frutas'],
  ['uva', 'Uvas', 'g', null, null, 69, 0.7, 18, 0.2, 'Frutas'],

  ['queso-port-salut', 'Queso port salut light', 'g', null, null, 230, 24, 2, 14, 'Lácteos'],
  ['ricota', 'Ricota', 'g', null, null, 150, 11, 3, 10, 'Lácteos'],
  ['crema', 'Crema de leche', 'g', null, null, 340, 2, 3, 35, 'Lácteos'],
  ['yogur-saborizado', 'Yogur saborizado', 'g', null, null, 90, 3.5, 14, 2.5, 'Lácteos'],

  ['salsa-soja', 'Salsa de soja', 'ml', null, null, 55, 8, 5, 0, 'Salsas y aderezos'],
  ['mermelada', 'Mermelada', 'g', null, null, 250, 0.4, 62, 0, 'Despensa'],
  ['mermelada-light', 'Mermelada light', 'g', null, null, 120, 0.4, 30, 0, 'Despensa'],
  ['cacao', 'Cacao en polvo azucarado', 'g', null, null, 380, 4, 88, 2.5, 'Despensa'],
  ['aceitunas', 'Aceitunas', 'g', null, null, 145, 1, 4, 15, 'Enlatados'],
  ['ketchup', 'Ketchup', 'g', null, null, 100, 1.2, 25, 0.1, 'Salsas y aderezos'],

  ['nueces', 'Nueces', 'g', null, null, 650, 15, 14, 65, 'Snacks y dulces'],
  ['almendras', 'Almendras', 'g', null, null, 580, 21, 22, 50, 'Snacks y dulces'],
  ['barrita-cereal', 'Barrita de cereal', 'u', 23, 'unidad', 390, 6, 70, 9, 'Snacks y dulces'],
  ['turron', 'Turrón de maní', 'u', 25, 'unidad', 400, 9, 70, 10, 'Snacks y dulces'],
  ['papas-paquete', 'Papas fritas de paquete', 'g', null, null, 540, 6, 52, 34, 'Snacks y dulces'],

  ['sandwich-miga', 'Sándwich de miga', 'u', 60, 'unidad', 250, 9, 28, 11, 'Comidas hechas'],
  ['pancho', 'Pancho', 'u', 150, 'unidad', 250, 9, 24, 13, 'Comidas hechas'],
  ['choripan', 'Choripán', 'u', 250, 'unidad', 300, 13, 20, 18, 'Comidas hechas'],
  ['asado', 'Asado (carne)', 'g', null, null, 280, 24, 0, 20, 'Comidas hechas'],
  ['tarta-porcion', 'Tarta de jamón y queso (porción)', 'u', 150, 'porción', 250, 10, 20, 14, 'Comidas hechas'],
  ['sushi', 'Sushi (pieza)', 'u', 30, 'pieza', 150, 5, 25, 3, 'Comidas hechas'],
  ['wrap-comprado', 'Wrap de pollo comprado (estimado)', 'u', 300, 'unidad', 200, 11, 20, 8, 'Comidas hechas'],
]

const P = ['almuerzo', 'cena']
const r = (slug, name, minutes, servings, meal_types, portable, steps, items) => ({ slug, name, minutes, servings, meal_types, portable, steps, items })

export const recetasNuevas = [
  // Desayunos
  r('desayuno-tostadas-untable', 'Tostadas con queso untable y mermelada light', 3, 1, ['desayuno'], false,
    'Tostás el pan.\nUntás el queso y la mermelada. Va con café con leche o mate.',
    [['pan-integral', 2], ['queso-untable', 30], ['mermelada-light', 20], ['leche', 200]]),
  r('desayuno-yogur-avena', 'Yogur con avena y banana', 2, 1, ['desayuno'], true,
    'Mezclás el yogur con la avena.\nBanana cortada arriba. Se puede dejar armado la noche anterior.',
    [['yogur-natural', 200], ['avena', 40], ['banana', 1]]),
  r('desayuno-copos', 'Copos de maíz con leche y banana', 2, 1, ['desayuno'], false,
    'Copos con la leche fría o tibia.\nBanana cortada arriba.',
    [['copos-maiz', 40], ['leche', 250], ['banana', 1]]),
  r('desayuno-tostado', 'Tostado de jamón y queso con café con leche', 5, 1, ['desayuno'], true,
    'Armás el sándwich con el jamón y el queso.\nLo tostás en sartén o tostadora, 2 min por lado.\nCafé con la leche.',
    [['pan-integral', 2], ['jamon-cocido', 40], ['queso-cremoso', 30], ['leche', 150]]),
  r('desayuno-palta-huevo', 'Tostadas con palta y huevo', 6, 1, ['desayuno'], false,
    'Tostás el pan y pisás la media palta arriba, con sal.\nHuevos revueltos o a la plancha, sin aceite.',
    [['pan-integral', 2], ['palta', 0.5], ['huevo', 2]]),
  r('desayuno-licuado', 'Licuado de banana, leche y avena', 3, 1, ['desayuno'], false,
    'Todo a la licuadora, 30 segundos. Sin azúcar.',
    [['banana', 1], ['leche', 300], ['avena', 30]]),

  // Meriendas
  r('merienda-tostadas', 'Tostadas con queso untable', 3, 1, ['merienda'], true,
    'Tostás el pan y untás el queso. Con mate o café sin azúcar.',
    [['pan-integral', 2], ['queso-untable', 40]]),
  r('merienda-yogur-fruta', 'Yogur natural con manzana y avena', 2, 1, ['merienda'], true,
    'Yogur con la manzana en cubos y la avena.',
    [['yogur-natural', 200], ['manzana', 1], ['avena', 20]]),
  r('merienda-sandwich', 'Sándwich de jamón y queso', 2, 1, ['merienda'], true,
    'Pan, jamón y queso. Frío o tostado.',
    [['pan-integral', 2], ['jamon-cocido', 40], ['queso-cremoso', 30]]),
  r('merienda-fruta-nueces', 'Manzana con nueces', 1, 1, ['merienda'], true,
    '1 manzana y un puñado chico de nueces (25 g).',
    [['manzana', 1], ['nueces', 25]]),
  r('merienda-galletas-arroz', 'Café con leche y galletas de arroz con queso', 3, 1, ['merienda'], false,
    'Café con la leche, sin azúcar.\nGalletas de arroz con el queso untable.',
    [['leche', 200], ['galleta-arroz', 3], ['queso-untable', 30]]),
  r('merienda-huevos-banana', 'Huevos duros y banana', 1, 1, ['merienda'], true,
    '2 huevos duros (hechos de antes) y 1 banana.',
    [['huevo', 2], ['banana', 1]]),

  // Almuerzos y cenas
  r('pechuga-ensalada', 'Pechuga a la plancha con ensalada', 12, 1, P, true,
    'Pechuga fileteada fina, con sal y limón, a la plancha: 4–5 min por lado.\nEnsalada de lechuga y tomate con el aceite.\nVa con las 2 rodajas de pan.',
    [['pechuga-cruda', 180], ['lechuga', 100], ['tomate', 1], ['aceite', 10], ['pan-integral', 2]]),
  r('pechuga-arroz', 'Pechuga con arroz', 20, 1, P, true,
    'Hervís el arroz.\nPechuga en cubos o fileteada, a la plancha con el aceite, sal y pimentón.\nTomate en rodajas al lado.',
    [['pechuga-cruda', 180], ['arroz', 70], ['tomate', 1], ['aceite', 5]]),
  r('pechuga-pure', 'Pechuga con puré de papa', 25, 1, P, true,
    'Papas en cubos, hervidas 15 min. Las pisás con la leche y sal.\nPechuga a la plancha con el aceite, 4–5 min por lado.',
    [['pechuga-cruda', 180], ['papa', 300], ['leche', 50], ['aceite', 5]]),
  r('salteado-pollo', 'Salteado de pollo con arroz y verduras', 20, 1, P, true,
    'Hervís el arroz.\nPollo en tiras a la sartén con el aceite, 5 min.\nSumás zanahoria rallada, morrón y cebolla en tiras, 5 min más.\nSalsa de soja y mezclás con el arroz.',
    [['pechuga-cruda', 150], ['arroz', 70], ['zanahoria', 1], ['morron', 0.5], ['cebolla', 0.5], ['salsa-soja', 15], ['aceite', 10]]),
  r('pollo-brocoli', 'Pollo con brócoli y arroz', 20, 1, P, true,
    'Hervís el arroz y el brócoli (5 min, que quede firme).\nPollo en cubos a la sartén con el aceite.\nJuntás todo con la salsa de soja.',
    [['pechuga-cruda', 180], ['brocoli', 200], ['arroz', 60], ['salsa-soja', 10], ['aceite', 5]]),
  r('pata-muslo-calabaza', 'Pata muslo al horno con calabaza', 55, 4, P, true,
    'Horno a 200 °C. Pollo con sal, pimentón y ajo en una placa: 50–55 min.\nCalabaza en cubos grandes con el aceite, en la misma placa o en otra: 35–40 min.\nPorción: 1 pata sin piel con calabaza.',
    [['pata-muslo', 4], ['calabaza', 800], ['aceite', 10]]),
  r('fideos-bolonesa', 'Fideos con boloñesa casera', 25, 3, P, true,
    'Rehogás la cebolla picada con el aceite y dorás la carne.\nAgregás el puré de tomate, sal y orégano: 15 min a fuego bajo.\nHervís los fideos y servís con queso rallado. Sin pan.',
    [['fideos', 240], ['carne-picada-cruda', 300], ['pure-tomate', 520], ['cebolla', 1], ['aceite', 10], ['queso-rallado', 30]]),
  r('hamburguesas-caseras', 'Hamburguesas caseras con ensalada', 20, 2, P, true,
    'Mezclás la carne con el huevo, el pan rallado, sal y ajo. Armás 4 hamburguesas.\nA la plancha o al horno, 4–5 min por lado.\nEnsalada de lechuga y tomate con el aceite.',
    [['carne-picada-cruda', 300], ['huevo', 1], ['pan-rallado', 20], ['lechuga', 150], ['tomate', 2], ['aceite', 10]]),
  r('pastel-papa', 'Pastel de papa', 50, 4, P, true,
    'Hervís las papas y hacés un puré con la leche.\nRehogás la cebolla con el aceite, dorás la carne y sumás los huevos duros picados.\nEn una fuente: carne abajo, puré arriba y queso rallado. Horno 200 °C, 15 min.',
    [['carne-picada-cruda', 500], ['papa', 1000], ['cebolla', 1], ['huevo', 2], ['leche', 100], ['aceite', 10], ['queso-rallado', 40]]),
  r('bife-ensalada', 'Bife a la plancha con ensalada', 10, 1, P, true,
    'Bife a la plancha bien caliente, 3–4 min por lado, sal al final.\nEnsalada de lechuga y tomate con el aceite.\nVa con las 2 rodajas de pan.',
    [['bife-nalga', 180], ['lechuga', 100], ['tomate', 1], ['aceite', 10], ['pan-integral', 2]]),
  r('bife-pure-calabaza', 'Bife con puré de calabaza', 25, 1, P, true,
    'Calabaza en cubos, hervida o al microondas, 12–15 min. La pisás con sal y el queso rallado.\nBife a la plancha con el aceite, 3–4 min por lado.',
    [['bife-nalga', 180], ['calabaza', 300], ['aceite', 5], ['queso-rallado', 10]]),
  r('milanesa-carne-pure', 'Milanesa de carne al horno con puré', 25, 1, P, true,
    'Milanesa al horno a 200 °C, 20 min, dándola vuelta a la mitad.\nPuré: papas hervidas y pisadas con la leche.\nTomate en rodajas al lado.',
    [['milanesa-carne', 1], ['papa', 300], ['leche', 50], ['tomate', 1]]),
  r('arroz-atun-huevo', 'Arroz con atún y huevo', 15, 1, P, true,
    'Hervís el arroz y el huevo (10 min).\nMezclás el arroz con el atún escurrido, las arvejas y el aceite.\nHuevo duro picado arriba.',
    [['arroz', 80], ['atun-natural', 1], ['huevo', 1], ['arvejas', 60], ['aceite', 5]]),
  r('ensalada-arroz-atun', 'Ensalada de arroz, atún y choclo', 15, 1, P, true,
    'Hervís el arroz y lo enfriás con agua.\nMezclás con el atún, el choclo, el tomate en cubos y el huevo duro.\nAceite, sal y limón o vinagre.',
    [['arroz', 70], ['atun-natural', 1], ['choclo', 80], ['tomate', 1], ['huevo', 1], ['aceite', 5]]),
  r('ensalada-lentejas', 'Ensalada de lentejas, huevo y tomate', 30, 1, P, true,
    'Hervís las lentejas 25 min, sin remojo, y las escurrís.\nMezclás con el tomate en cubos y los huevos duros.\nAceite, sal y vinagre.',
    [['lentejas', 80], ['huevo', 2], ['tomate', 1], ['aceite', 10]]),
  r('ensalada-garbanzos', 'Ensalada de garbanzos, atún y tomate', 5, 1, P, true,
    'Escurrís los garbanzos y el atún.\nMezclás con el tomate en cubos, el aceite, sal y limón.',
    [['garbanzos', 200], ['atun-natural', 1], ['tomate', 1], ['aceite', 10]]),
  r('ensalada-cesar', 'Ensalada César simple', 15, 1, P, true,
    'Pechuga a la plancha y cortada en tiras.\nPan tostado en cubos.\nLechuga, pollo, pan, huevo duro y queso rallado, con el aceite y limón.',
    [['pechuga-cruda', 150], ['lechuga', 150], ['queso-rallado', 20], ['pan-integral', 2], ['huevo', 1], ['aceite', 10]]),
  r('tarta-atun', 'Tarta de atún', 40, 3, P, true,
    'Tapa en una tartera. Mezclás el atún, la cebolla rehogada, los huevos batidos y el queso en cubos.\nRelleno adentro, tomate en rodajas arriba.\nHorno a 180 °C, 30 min.',
    [['tapa-tarta', 1], ['atun-natural', 2], ['huevo', 3], ['cebolla', 1], ['queso-cremoso', 100], ['tomate', 1]]),
  r('tarta-jamon-queso', 'Tarta de jamón y queso', 35, 3, P, true,
    'Tapa en una tartera. Jamón y queso en capas.\nHuevos batidos con sal por arriba.\nHorno a 180 °C, 25–30 min.',
    [['tapa-tarta', 1], ['jamon-cocido', 150], ['queso-cremoso', 150], ['huevo', 3]]),
  r('tarta-acelga', 'Tarta de acelga y ricota', 40, 3, P, true,
    'Hervís la acelga 3 min, la escurrís bien y la picás.\nMezclás con la ricota, los huevos y el queso rallado.\nRelleno sobre la tapa. Horno a 180 °C, 30 min.',
    [['tapa-tarta', 1], ['acelga', 400], ['ricota', 250], ['huevo', 2], ['queso-rallado', 30]]),
  r('fideos-tuco', 'Fideos con tuco, huevo y queso', 15, 1, P, true,
    'Hervís los fideos y los huevos.\nCalentás el puré de tomate con el aceite, sal y orégano, 5 min.\nFideos con la salsa, huevo duro picado y queso rallado. Sin pan.',
    [['fideos', 90], ['pure-tomate', 150], ['huevo', 2], ['queso-rallado', 20], ['aceite', 5]]),
  r('revuelto-zapallitos', 'Revuelto de zapallitos con huevo', 15, 1, P, false,
    'Cebolla y zapallitos en cubos chicos a la sartén con el aceite, 8 min.\nAgregás los huevos batidos y revolvés hasta que cuajen.\nQueso rallado arriba. Va con las 2 rodajas de pan.',
    [['zapallito', 2], ['huevo', 3], ['cebolla', 0.5], ['queso-rallado', 15], ['aceite', 5], ['pan-integral', 2]]),
  r('merluza-papas', 'Merluza al horno con papas', 30, 1, P, true,
    'Papas en rodajas finas en una placa con el aceite y sal: 15 min a 200 °C.\nSumás la merluza arriba con sal y limón: 12–15 min más.',
    [['filet-merluza', 250], ['papa', 300], ['aceite', 10]]),
  r('merluza-ensalada', 'Merluza a la plancha con ensalada', 12, 1, P, false,
    'Merluza a la plancha con sal y limón, 3–4 min por lado.\nEnsalada de lechuga y tomate con el aceite.\nVa con las 2 rodajas de pan.',
    [['filet-merluza', 250], ['lechuga', 100], ['tomate', 1], ['aceite', 10], ['pan-integral', 2]]),
  r('polenta-salsa', 'Polenta con salsa, queso y huevo', 12, 1, P, false,
    'Polenta en lluvia sobre agua hirviendo con sal, revolviendo 3–5 min.\nCalentás el puré de tomate con orégano.\nPolenta, salsa, queso en cubos, huevo duro y queso rallado.',
    [['polenta', 80], ['pure-tomate', 150], ['queso-cremoso', 50], ['huevo', 1], ['queso-rallado', 10]]),
  r('guiso-arroz-pollo', 'Guiso de arroz con pollo', 35, 3, P, true,
    'Rehogás la cebolla y la zanahoria rallada con el aceite.\nSumás el pollo sin piel, el puré de tomate, el caldo y 700 ml de agua: 15 min.\nAgregás el arroz y cocinás 15 min más. Desmenuzás el pollo.',
    [['arroz', 240], ['pata-muslo', 3], ['pure-tomate', 520], ['cebolla', 1], ['zanahoria', 1], ['caldo', 1], ['aceite', 10]]),
  r('guiso-fideos-carne', 'Guiso de fideos con carne', 30, 3, P, true,
    'Rehogás la cebolla y la zanahoria rallada con el aceite y dorás la carne.\nSumás el puré de tomate, el caldo y 700 ml de agua: 10 min.\nAgregás los fideos y cocinás hasta que estén.',
    [['fideos', 240], ['carne-picada-cruda', 300], ['pure-tomate', 520], ['cebolla', 1], ['zanahoria', 1], ['caldo', 1], ['aceite', 10]]),
  r('wrap-pollo', 'Wrap de pollo', 15, 1, P, true,
    'Pechuga en tiras a la plancha.\nUntás las rapiditas con el queso y armás con el pollo, la lechuga y el tomate.',
    [['rapidita', 2], ['pechuga-cruda', 150], ['lechuga', 50], ['tomate', 1], ['queso-untable', 30]]),
  r('wrap-atun', 'Wrap de atún y huevo', 5, 1, P, true,
    'Untás las rapiditas con el queso.\nAtún escurrido, huevo duro picado, lechuga y tomate. Enrollás.',
    [['rapidita', 2], ['atun-natural', 1], ['huevo', 1], ['lechuga', 50], ['tomate', 1], ['queso-untable', 30]]),
  r('sandwich-pollo', 'Sándwich de pollo, huevo y tomate', 12, 1, P, true,
    'Pechuga a la plancha.\nArmás 2 sándwiches con el pollo, huevo duro, tomate, lechuga y mostaza.',
    [['pan-integral', 4], ['pechuga-cruda', 120], ['huevo', 1], ['tomate', 1], ['lechuga', 30], ['mostaza', 10]]),
  r('tortilla-papa', 'Tortilla de papa', 25, 2, P, true,
    'Papas en cubitos al microondas con un chorrito de agua, tapadas, 8 min.\nCebolla rehogada con parte del aceite. Mezclás todo con los huevos batidos y sal.\nSartén con el resto del aceite, fuego bajo, 5 min por lado.\nVa con tomate en rodajas.',
    [['papa', 500], ['huevo', 5], ['cebolla', 1], ['aceite', 15], ['tomate', 2]]),
  r('omelette-jamon-queso', 'Omelette de jamón y queso con ensalada', 6, 1, P, false,
    'Batís los huevos con sal.\nSartén antiadherente, huevos, jamón y queso en el medio y doblás: 3–4 min.\nEnsalada de lechuga y tomate, con las 2 rodajas de pan.',
    [['huevo', 3], ['jamon-cocido', 40], ['queso-cremoso', 30], ['lechuga', 80], ['tomate', 1], ['pan-integral', 2]]),
  r('arroz-huevo-arvejas', 'Arroz con huevo y arvejas', 15, 1, P, true,
    'Hervís el arroz.\nHuevos revueltos en la sartén con el aceite.\nMezclás arroz, huevo y arvejas, con sal y pimentón.',
    [['arroz', 90], ['huevo', 3], ['arvejas', 100], ['aceite', 5]]),
  r('pizzetas-rapidita', 'Pizzetas de rapidita', 10, 1, P, false,
    'Rapiditas en una placa. Puré de tomate con orégano, queso y jamón arriba.\nHorno fuerte 6–8 min, hasta que se derrita el queso.',
    [['rapidita', 2], ['pure-tomate', 80], ['queso-cremoso', 80], ['jamon-cocido', 40]]),
  r('milanesas-soja-arroz', 'Milanesas de soja con arroz y ensalada', 20, 1, P, true,
    'Milanesas al horno a 200 °C, 15 min, dándolas vuelta.\nHervís el arroz.\nEnsalada de lechuga y tomate con el aceite.',
    [['milanesa-soja', 2], ['arroz', 60], ['lechuga', 80], ['tomate', 1], ['aceite', 5]]),
]

// ---------------------------------------------------------------------------
// Tercera tanda: infusiones (valores cada 100 ml, sin endulzar: el azúcar se carga aparte)
// ---------------------------------------------------------------------------
export const infusiones = [
  ['terere', 'Tereré con agua', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['terere-jugo', 'Tereré con jugo', 'ml', null, null, 10, 0, 2.3, 0, 'Bebidas'],
  ['mate-cocido', 'Mate cocido', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['mate-cocido-leche', 'Mate cocido con leche', 'ml', null, null, 22, 1.5, 2.3, 0.7, 'Bebidas'],
  ['cafe', 'Café negro', 'ml', null, null, 1, 0.1, 0, 0, 'Bebidas'],
  ['cortado', 'Café cortado', 'ml', null, null, 10, 0.6, 0.9, 0.3, 'Bebidas'],
  ['capuchino', 'Capuchino', 'ml', null, null, 40, 2, 4.5, 1.5, 'Bebidas'],
  ['te', 'Té', 'ml', null, null, 0, 0, 0, 0, 'Bebidas'],
  ['te-leche', 'Té con leche', 'ml', null, null, 12, 0.8, 1.2, 0.4, 'Bebidas'],
]

// Bebidas con alcohol: no cuentan para el objetivo de líquido
export const conAlcohol = ['cerveza', 'cerveza-negra', 'cerveza-ipa', 'vino', 'vino-blanco', 'espumante', 'sidra', 'fernet', 'fernet-coca',
  'bebida-blanca', 'gin-tonic', 'ron-cola', 'campari', 'aperol-spritz', 'vermut', 'trago-dulce', 'licor']

// ---------------------------------------------------------------------------
// Cuarta tanda: más productos de góndola (para depender menos de Open Food Facts) y recetas con ellos.
// Las categorías son por góndola, como se ordena una despensa.
// ---------------------------------------------------------------------------
export const alimentosCuarta = [
  // Carnes y huevos
  ['hamburguesa-carne', 'Hamburguesa de carne (medallón crudo)', 'u', 80, 'unidad', 250, 15, 2, 20, 'Carnes y huevos'],
  ['salchicha', 'Salchicha tipo viena', 'u', 45, 'unidad', 270, 11, 3, 24, 'Carnes y huevos'],
  ['chorizo', 'Chorizo parrillero', 'u', 100, 'unidad', 300, 15, 1, 26, 'Carnes y huevos'],
  ['carre-cerdo', 'Carré o bondiola de cerdo (crudo)', 'g', null, null, 170, 20, 0, 10, 'Carnes y huevos'],
  ['carne-guiso', 'Carne para guiso o estofado (cruda)', 'g', null, null, 140, 21, 0, 6, 'Carnes y huevos'],
  ['pollo-trozado', 'Pollo trozado con piel (crudo)', 'g', null, null, 215, 18, 0, 15, 'Carnes y huevos'],
  ['paleta', 'Paleta cocida (fiambre)', 'g', null, null, 105, 16, 3, 3, 'Carnes y huevos'],
  ['salame', 'Salame', 'g', null, null, 400, 22, 1, 34, 'Carnes y huevos'],
  ['mortadela', 'Mortadela', 'g', null, null, 250, 13, 3, 21, 'Carnes y huevos'],
  // Pescados
  ['atun-aceite', 'Atún en aceite (lata 170 g)', 'u', 120, 'lata', 190, 24, 0, 10, 'Pescados'],
  ['caballa', 'Caballa en lata', 'g', null, null, 150, 20, 0, 8, 'Pescados'],
  ['sardinas', 'Sardinas en lata', 'g', null, null, 190, 22, 0, 11, 'Pescados'],
  // Lácteos
  ['leche-descremada', 'Leche descremada', 'ml', null, null, 34, 3.2, 4.8, 0.1, 'Lácteos'],
  ['leche-polvo', 'Leche en polvo entera', 'g', null, null, 490, 26, 38, 26, 'Lácteos'],
  ['yogur-griego', 'Yogur griego natural', 'g', null, null, 95, 8, 4, 5, 'Lácteos'],
  ['yogur-descremado', 'Yogur descremado', 'g', null, null, 40, 4, 5, 0.1, 'Lácteos'],
  ['yogur-proteico', 'Yogur alto en proteínas', 'g', null, null, 65, 7, 6, 1, 'Lácteos'],
  ['queso-tybo', 'Queso tybo o en barra (fetas)', 'g', null, null, 330, 25, 1, 25, 'Lácteos'],
  ['muzzarella', 'Queso muzzarella', 'g', null, null, 290, 21, 2, 22, 'Lácteos'],
  ['queso-untable-clasico', 'Queso untable clásico', 'g', null, null, 240, 7, 3, 22, 'Lácteos'],
  ['postre-lacteo', 'Postre de vainilla o chocolate (pote)', 'g', null, null, 125, 3, 20, 3.5, 'Lácteos'],
  ['flan', 'Flan', 'g', null, null, 120, 3.5, 20, 3, 'Lácteos'],
  // Verduras
  ['ajo', 'Ajo (diente)', 'u', 5, 'diente', 149, 6.4, 33, 0.5, 'Verduras'],
  ['pepino', 'Pepino', 'u', 200, 'unidad', 15, 0.7, 3.6, 0.1, 'Verduras'],
  ['berenjena', 'Berenjena', 'u', 250, 'unidad', 25, 1, 6, 0.2, 'Verduras'],
  ['repollo', 'Repollo', 'g', null, null, 25, 1.3, 6, 0.1, 'Verduras'],
  ['remolacha', 'Remolacha', 'u', 100, 'unidad', 43, 1.6, 10, 0.2, 'Verduras'],
  ['champinones', 'Champiñones', 'g', null, null, 22, 3.1, 3.3, 0.3, 'Verduras'],
  ['chauchas', 'Chauchas', 'g', null, null, 31, 1.8, 7, 0.2, 'Verduras'],
  ['rucula', 'Rúcula', 'g', null, null, 25, 2.6, 3.7, 0.7, 'Verduras'],
  ['coliflor', 'Coliflor', 'g', null, null, 25, 1.9, 5, 0.3, 'Verduras'],
  ['cebolla-verdeo', 'Cebolla de verdeo', 'g', null, null, 32, 1.8, 7, 0.2, 'Verduras'],
  ['tomate-cherry', 'Tomates cherry', 'g', null, null, 18, 0.9, 3.9, 0.2, 'Verduras'],
  // Frutas
  ['limon', 'Limón', 'u', 100, 'unidad', 29, 1.1, 9, 0.3, 'Frutas'],
  ['kiwi', 'Kiwi', 'u', 75, 'unidad', 61, 1.1, 15, 0.5, 'Frutas'],
  ['anana', 'Ananá', 'g', null, null, 50, 0.5, 13, 0.1, 'Frutas'],
  ['sandia', 'Sandía', 'g', null, null, 30, 0.6, 8, 0.2, 'Frutas'],
  ['melon', 'Melón', 'g', null, null, 34, 0.8, 8, 0.2, 'Frutas'],
  ['ciruela', 'Ciruela', 'u', 65, 'unidad', 46, 0.7, 11, 0.3, 'Frutas'],
  ['pomelo', 'Pomelo', 'u', 250, 'unidad', 42, 0.8, 11, 0.1, 'Frutas'],
  ['arandanos', 'Arándanos', 'g', null, null, 57, 0.7, 14, 0.3, 'Frutas'],
  // Pastas y arroz
  ['fideos-integrales', 'Fideos integrales (crudos)', 'g', null, null, 345, 13, 66, 2.5, 'Pastas y arroz'],
  ['fideos-frescos', 'Fideos frescos (tallarines)', 'g', null, null, 280, 11, 55, 2, 'Pastas y arroz'],
  ['fideos-instantaneos', 'Fideos instantáneos (tipo ramen)', 'g', null, null, 450, 9, 60, 19, 'Pastas y arroz'],
  ['arroz-integral', 'Arroz integral (crudo)', 'g', null, null, 350, 7.5, 73, 2.7, 'Pastas y arroz'],
  ['ravioles', 'Ravioles de ricota o verdura (frescos)', 'g', null, null, 200, 9, 30, 5, 'Pastas y arroz'],
  ['noquis', 'Ñoquis de papa (frescos)', 'g', null, null, 160, 4, 34, 1, 'Pastas y arroz'],
  // Legumbres
  ['porotos', 'Porotos secos', 'g', null, null, 335, 22, 60, 1.2, 'Legumbres'],
  ['garbanzos-secos', 'Garbanzos secos', 'g', null, null, 364, 19, 61, 6, 'Legumbres'],
  ['soja-texturizada', 'Soja texturizada', 'g', null, null, 330, 50, 30, 1, 'Legumbres'],
  // Panadería
  ['pan-lactal-blanco', 'Pan lactal blanco', 'u', 25, 'rodaja', 265, 8, 50, 3, 'Panadería'],
  ['pan-hamburguesa', 'Pan de hamburguesa', 'u', 60, 'unidad', 280, 9, 50, 4, 'Panadería'],
  ['pan-pancho', 'Pan de pancho', 'u', 40, 'unidad', 280, 9, 50, 4, 'Panadería'],
  ['pan-arabe', 'Pan árabe', 'u', 60, 'unidad', 260, 9, 53, 1, 'Panadería'],
  ['tostadas-mesa', 'Tostadas de mesa', 'u', 7, 'unidad', 390, 11, 72, 6, 'Panadería'],
  ['galletita-salvado', 'Galletita de salvado', 'u', 6, 'unidad', 430, 10, 62, 15, 'Panadería'],
  ['bizcochos', 'Bizcochos de grasa', 'u', 8, 'unidad', 480, 9, 58, 23, 'Panadería'],
  ['grisines', 'Grisines', 'g', null, null, 400, 11, 70, 8, 'Panadería'],
  ['prepizza', 'Prepizza', 'u', 250, 'unidad', 270, 8, 52, 3, 'Panadería'],
  ['tapa-empanada', 'Tapa de empanada', 'u', 28, 'tapa', 300, 7, 50, 8, 'Panadería'],
  // Cereales
  ['granola', 'Granola', 'g', null, null, 430, 10, 65, 14, 'Cereales'],
  ['cereal-azucarado', 'Cereales azucarados o de chocolate', 'g', null, null, 385, 5, 87, 2, 'Cereales'],
  ['quinoa', 'Quinoa (cruda)', 'g', null, null, 370, 14, 64, 6, 'Cereales'],
  ['chia', 'Semillas de chía', 'g', null, null, 490, 17, 42, 31, 'Cereales'],
  // Enlatados
  ['jardinera', 'Jardinera en lata', 'g', null, null, 55, 2.5, 10, 0.4, 'Enlatados'],
  ['lentejas-lata', 'Lentejas en lata', 'g', null, null, 90, 7, 13, 0.5, 'Enlatados'],
  ['porotos-lata', 'Porotos en lata', 'g', null, null, 95, 6, 16, 0.5, 'Enlatados'],
  ['palmitos', 'Palmitos', 'g', null, null, 28, 2.5, 4.6, 0.6, 'Enlatados'],
  ['duraznos-almibar', 'Duraznos en almíbar', 'g', null, null, 75, 0.4, 19, 0.1, 'Enlatados'],
  ['picadillo', 'Picadillo o paté de carne', 'g', null, null, 210, 11, 3, 17, 'Enlatados'],
  // Salsas y aderezos
  ['salsa-tomate', 'Salsa de tomate lista (pomarola, filetto)', 'g', null, null, 45, 1.5, 7, 1.2, 'Salsas y aderezos'],
  ['tomate-triturado', 'Tomate triturado o perita en lata', 'g', null, null, 25, 1.2, 4.5, 0.2, 'Salsas y aderezos'],
  ['salsa-golf', 'Salsa golf', 'g', null, null, 420, 1, 12, 41, 'Salsas y aderezos'],
  ['mayonesa-light', 'Mayonesa light', 'g', null, null, 330, 1, 10, 32, 'Salsas y aderezos'],
  ['vinagre', 'Vinagre', 'ml', null, null, 4, 0, 0.6, 0, 'Salsas y aderezos'],
  ['aceto', 'Aceto balsámico', 'ml', null, null, 90, 0.5, 17, 0, 'Salsas y aderezos'],
  ['jugo-limon', 'Jugo de limón (en botella)', 'ml', null, null, 22, 0.4, 7, 0, 'Salsas y aderezos'],
  ['salsa-barbacoa', 'Salsa barbacoa', 'g', null, null, 170, 1, 40, 0.5, 'Salsas y aderezos'],
  ['salsa-blanca', 'Salsa blanca', 'g', null, null, 110, 3.5, 9, 6.5, 'Salsas y aderezos'],
  ['chimichurri', 'Chimichurri', 'g', null, null, 250, 1, 6, 25, 'Salsas y aderezos'],
  ['pesto', 'Pesto', 'g', null, null, 450, 5, 6, 45, 'Salsas y aderezos'],
  // Despensa
  ['aceite-oliva', 'Aceite de oliva', 'ml', null, null, 820, 0, 0, 92, 'Despensa'],
  ['sal', 'Sal', 'g', null, null, 0, 0, 0, 0, 'Despensa'],
  ['harina', 'Harina de trigo', 'g', null, null, 340, 10, 72, 1, 'Despensa'],
  ['maicena', 'Fécula de maíz (maicena)', 'g', null, null, 350, 0.3, 87, 0.1, 'Despensa'],
  ['pure-instantaneo', 'Puré de papas instantáneo (en polvo)', 'g', null, null, 350, 8, 78, 0.6, 'Despensa'],
  ['leche-condensada', 'Leche condensada', 'g', null, null, 325, 8, 55, 8, 'Despensa'],
  ['mani-pasta', 'Pasta de maní', 'g', null, null, 600, 25, 20, 50, 'Despensa'],
  ['cafe-polvo', 'Café instantáneo (en polvo)', 'g', null, null, 240, 12, 41, 0.5, 'Despensa'],
  ['yerba', 'Yerba mate', 'g', null, null, 0, 0, 0, 0, 'Despensa'],
  ['saquitos', 'Té o mate cocido (saquito)', 'u', 2, 'saquito', 0, 0, 0, 0, 'Despensa'],
  ['proteina-polvo', 'Proteína en polvo (whey)', 'g', null, null, 380, 78, 8, 5, 'Despensa'],
  // Snacks y dulces
  ['galletita-dulce', 'Galletita dulce simple (vainilla o tipo María)', 'u', 6, 'unidad', 440, 7, 72, 13, 'Snacks y dulces'],
  ['budin', 'Budín', 'g', null, null, 380, 5, 52, 17, 'Snacks y dulces'],
  ['magdalena', 'Magdalena', 'u', 30, 'unidad', 420, 5, 50, 22, 'Snacks y dulces'],
  ['alfajor-maicena', 'Alfajor de maicena', 'u', 40, 'unidad', 420, 5, 65, 16, 'Snacks y dulces'],
  ['alfajor-triple', 'Alfajor triple', 'u', 70, 'unidad', 430, 5, 62, 18, 'Snacks y dulces'],
  ['bombon', 'Bombón de chocolate con relleno', 'u', 15, 'unidad', 530, 9, 50, 33, 'Snacks y dulces'],
  ['gomitas', 'Gomitas', 'g', null, null, 340, 5, 78, 0, 'Snacks y dulces'],
  ['gelatina', 'Gelatina preparada', 'g', null, null, 60, 1.5, 14, 0, 'Snacks y dulces'],
  ['dulce-membrillo', 'Dulce de membrillo o batata', 'g', null, null, 270, 0.5, 67, 0.2, 'Snacks y dulces'],
  ['postre-mani', 'Postre de maní (tipo Mantecol)', 'g', null, null, 540, 13, 45, 35, 'Snacks y dulces'],
  ['palitos-salados', 'Palitos salados', 'g', null, null, 480, 9, 60, 22, 'Snacks y dulces'],
  ['chizitos', 'Chizitos', 'g', null, null, 500, 6, 60, 26, 'Snacks y dulces'],
  ['pochoclo', 'Pochoclo dulce', 'g', null, null, 400, 9, 75, 8, 'Snacks y dulces'],
  ['mix-frutos-secos', 'Mix de frutos secos', 'g', null, null, 550, 17, 30, 42, 'Snacks y dulces'],
  ['pasas', 'Pasas de uva', 'g', null, null, 300, 3, 79, 0.5, 'Snacks y dulces'],
  ['barrita-proteica', 'Barrita proteica', 'u', 45, 'unidad', 380, 30, 35, 13, 'Snacks y dulces'],
  // Congelados
  ['nuggets', 'Nuggets de pollo', 'u', 20, 'unidad', 250, 13, 16, 15, 'Congelados'],
  ['medallon-pollo', 'Medallón de pollo rebozado', 'u', 65, 'unidad', 220, 12, 15, 12, 'Congelados'],
  ['filet-rebozado', 'Filet de merluza rebozado', 'u', 100, 'unidad', 200, 12, 18, 9, 'Congelados'],
  ['medallon-verdura', 'Medallón de verdura', 'u', 80, 'unidad', 180, 5, 22, 8, 'Congelados'],
  ['papas-congeladas', 'Papas prefritas congeladas (al horno)', 'g', null, null, 150, 2.5, 24, 5, 'Congelados'],
  ['vegetales-congelados', 'Vegetales congelados (mix)', 'g', null, null, 50, 3, 8, 0.5, 'Congelados'],
  // Comidas hechas
  ['milanesa-napolitana', 'Milanesa napolitana (estimado)', 'u', 250, 'unidad', 250, 15, 12, 15, 'Comidas hechas'],
  ['sandwich-milanesa', 'Sándwich de milanesa (estimado)', 'u', 350, 'unidad', 250, 13, 25, 11, 'Comidas hechas'],
  ['empanada-jyq', 'Empanada de jamón y queso', 'u', 80, 'unidad', 290, 11, 28, 15, 'Comidas hechas'],
  ['empanada-pollo', 'Empanada de pollo', 'u', 80, 'unidad', 260, 12, 27, 11, 'Comidas hechas'],
  ['tarta-verdura-porcion', 'Tarta de verdura (porción)', 'u', 150, 'porción', 200, 7, 20, 10, 'Comidas hechas'],
  ['canelones', 'Canelones con salsa (porción)', 'u', 300, 'porción', 140, 6, 14, 6, 'Comidas hechas'],
  ['ensalada-rusa', 'Ensalada rusa', 'g', null, null, 150, 2, 12, 10, 'Comidas hechas'],
  ['pollo-spiedo', 'Pollo al spiedo (con piel)', 'g', null, null, 215, 25, 0, 13, 'Comidas hechas'],
  ['tostado-bar', 'Tostado de jamón y queso (de bar)', 'u', 150, 'unidad', 270, 14, 28, 11, 'Comidas hechas'],
  // Bebidas (valores cada 100 ml)
  ['bebida-almendras', 'Bebida de almendras', 'ml', null, null, 15, 0.5, 0.5, 1.2, 'Bebidas'],
  ['bebida-soja', 'Bebida de soja', 'ml', null, null, 40, 3, 3, 1.8, 'Bebidas'],
  ['batido-proteina', 'Batido de proteína (con agua)', 'ml', null, null, 38, 7.8, 0.8, 0.5, 'Bebidas'],
]

const DM = ['desayuno', 'merienda']
export const recetasCuarta = [
  // Desayunos y meriendas
  r('galletitas-miel', 'Café con leche y galletitas de agua con miel', 3, 1, DM, false,
    'Calentás la leche y le sumás el café.\nUntás las galletitas con la miel: una cucharadita cada dos alcanza.',
    [['galletita-agua', 6], ['miel', 20], ['leche', 200]]),
  r('arroz-con-leche', 'Arroz con leche', 35, 4, DM, true,
    'Leche, arroz y azúcar en una olla a fuego bajo, revolviendo cada tanto: 30 min, hasta que el arroz esté tierno y cremoso.\nSi tenés, una cucharadita de esencia de vainilla o canela al final.\nSe guarda en la heladera 3 días. Porción: un bol chico.',
    [['arroz', 150], ['leche', 1000], ['azucar', 80]]),
  r('avena-miel', 'Avena con leche y miel', 5, 1, ['desayuno'], false,
    'Avena y leche en una olla chica: 3 min revolviendo, hasta que espese.\nLa miel arriba.',
    [['avena', 40], ['leche', 250], ['miel', 15]]),
  r('tostadas-miel', 'Tostadas con miel y leche', 3, 1, DM, false,
    'Tostás el pan y lo untás con la miel.\nVa con un vaso de leche, sola o con café.',
    [['pan-integral', 2], ['miel', 20], ['leche', 250]]),
  r('tostadas-pasta-mani', 'Tostadas con pasta de maní y banana', 3, 1, DM, true,
    'Tostás el pan y untás la pasta de maní.\nBanana en rodajas arriba.',
    [['pan-integral', 2], ['mani-pasta', 20], ['banana', 1]]),
  r('yogur-granola', 'Yogur con granola y fruta', 2, 1, DM, true,
    'Yogur en un bol, granola y la banana cortada arriba.',
    [['yogur-natural', 200], ['granola', 40], ['banana', 1]]),
  r('galletitas-queso', 'Galletitas de agua con queso untable', 2, 1, ['merienda'], true,
    'Untás las galletitas con el queso. Va con mate, té o café.',
    [['galletita-agua', 6], ['queso-untable', 40]]),

  // Con lo que suele haber en la alacena
  r('fideos-pomarola', 'Fideos con salsa de tomate y queso', 15, 1, P, true,
    'Hervís los fideos en agua con sal el tiempo que diga el paquete.\nCalentás la salsa en la misma olla, ya colada.\nQueso rallado arriba.',
    [['fideos', 100], ['salsa-tomate', 150], ['queso-rallado', 20]]),
  r('fideos-manteca', 'Fideos con manteca y queso', 12, 1, P, true,
    'Hervís los fideos en agua con sal.\nLos colás y los mezclás con la manteca y el queso rallado mientras están calientes.',
    [['fideos', 100], ['manteca', 10], ['queso-rallado', 25]]),
  r('ensalada-fideos-atun', 'Ensalada de fideos, atún y jardinera', 15, 1, P, true,
    'Hervís los fideos (mejor tirabuzones o moños), los colás y los enfriás con agua.\nLos mezclás con el atún escurrido, la jardinera escurrida y la mayonesa.\nSe come fría: va bien para llevar.',
    [['fideos', 80], ['atun-natural', 1], ['jardinera', 150], ['mayonesa-light', 15]]),
  r('arroz-atun-jardinera', 'Arroz con atún y jardinera', 20, 1, P, true,
    'Hervís el arroz 15–18 min y lo colás.\nLo mezclás con el atún escurrido, la jardinera escurrida y el aceite.\nSe come tibio o frío.',
    [['arroz', 80], ['atun-natural', 1], ['jardinera', 150], ['aceite', 5]]),
  r('arroz-primavera', 'Arroz primavera con huevo', 20, 1, P, true,
    'Hervís el arroz 15–18 min.\nHuevos revueltos en la sartén con el aceite.\nMezclás todo con la jardinera y las arvejas escurridas y lo calentás 2 min.',
    [['arroz', 80], ['jardinera', 150], ['arvejas', 50], ['huevo', 2], ['aceite', 5]]),
  r('ensalada-jardinera-atun', 'Ensalada de jardinera, atún y huevo', 12, 1, P, true,
    'Huevos duros: 10 min desde que hierve.\nJardinera escurrida, atún y huevos en cuartos.\nLa mayonesa para mezclar.',
    [['jardinera', 250], ['atun-natural', 1], ['huevo', 2], ['mayonesa-light', 15]]),
  r('milanesas-arroz-jardinera', 'Milanesas de pollo con arroz y jardinera', 25, 1, P, true,
    'Milanesas al horno a 200 °C, 20 min, dándolas vuelta.\nHervís el arroz y lo mezclás con la jardinera escurrida.',
    [['milanesa-pollo', 2], ['arroz', 50], ['jardinera', 100]]),
  r('milanesas-napolitanas', 'Milanesas de pollo a la napolitana', 25, 1, P, false,
    'Milanesas al horno a 200 °C, 15 min, dándolas vuelta.\nSalsa y muzzarella arriba y 5 min más, hasta que se derrita.',
    [['milanesa-pollo', 2], ['salsa-tomate', 80], ['muzzarella', 60]]),
  r('lentejas-arroz', 'Guiso de lentejas con arroz', 45, 3, P, true,
    'Lentejas en remojo desde la noche anterior (o 2 horas en agua caliente).\nCebolla picada en la olla con el aceite, 5 min. Sumás la salsa, el caldo, las lentejas y agua hasta cubrir: 25 min.\nAgregás el arroz y 15 min más, con agua si hace falta.\nPorción: un plato hondo.',
    [['lentejas', 250], ['arroz', 100], ['salsa-tomate', 300], ['cebolla', 1], ['caldo', 1], ['aceite', 10]]),
  r('polenta-pomarola', 'Polenta con salsa de tomate y queso rallado', 10, 1, P, false,
    'Hervís 350 ml de agua con sal, echás la polenta en lluvia y revolvés 2–3 min (si es instantánea).\nSalsa caliente arriba y el queso rallado.',
    [['polenta', 80], ['salsa-tomate', 150], ['queso-rallado', 25]]),
  r('sopa-fideos-verduras', 'Sopa de fideos con verduras', 15, 1, P, false,
    'Hervís medio litro de agua con el caldo.\nSumás los fideos (mejor cabello de ángel o dedalitos) y la jardinera: 8 min.\nQueso rallado al servir.',
    [['fideos', 50], ['jardinera', 150], ['caldo', 1], ['queso-rallado', 10]]),
  r('omelette-atun', 'Omelette de atún y queso con tostadas', 10, 1, P, false,
    'Batís los huevos con el atún escurrido y el queso rallado.\nSartén antiadherente a fuego medio: 3 min, doblás y 1 min más.\nVa con las tostadas.',
    [['huevo', 3], ['atun-natural', 0.5], ['queso-rallado', 15], ['pan-integral', 2]]),
  r('sandwich-atun', 'Sándwich de atún con mayonesa', 8, 1, P, true,
    'Mezclás el atún escurrido con la mayonesa.\nArmás dos sándwiches con la lechuga y el tomate en rodajas.',
    [['pan-integral', 4], ['atun-natural', 1], ['mayonesa-light', 15], ['tomate', 1], ['lechuga', 30]]),

  // Rápidas de todos los días
  r('hamburguesa-pan', 'Hamburguesa casera al pan', 12, 1, P, false,
    'Hamburguesa a la plancha o sartén sin aceite: 4 min de cada lado.\nArmás con el queso, la lechuga y el tomate.',
    [['hamburguesa-carne', 1], ['pan-hamburguesa', 1], ['queso-tybo', 20], ['lechuga', 30], ['tomate', 0.5]]),
  r('panchos', 'Panchos', 8, 1, P, false,
    'Salchichas en agua hirviendo 3 min.\nArmás con el pan y la mostaza.',
    [['salchicha', 2], ['pan-pancho', 2], ['mostaza', 10]]),
  r('guiso-arroz-salchichas', 'Guiso de arroz con salchichas', 30, 3, P, true,
    'Cebolla picada en la olla con el aceite, 5 min.\nSumás la salsa, el caldo, el arroz y 600 ml de agua: 18 min a fuego bajo.\nSalchichas en rodajas los últimos 5 min.\nPorción: un plato hondo.',
    [['arroz', 240], ['salchicha', 6], ['salsa-tomate', 300], ['cebolla', 1], ['caldo', 1], ['aceite', 10]]),
  r('pizza-casera', 'Pizza casera de muzzarella', 15, 2, P, false,
    'Horno bien caliente (230 °C).\nSalsa sobre la prepizza y 5 min de horno. Sumás la muzzarella y 6–8 min más.\nPorción: media pizza.',
    [['prepizza', 1], ['salsa-tomate', 120], ['muzzarella', 200]]),
  r('noquis-salsa', 'Ñoquis con salsa de tomate', 10, 1, P, false,
    'Ñoquis en agua hirviendo con sal: se sacan cuando suben, 2–3 min.\nSalsa caliente y queso rallado.',
    [['noquis', 300], ['salsa-tomate', 150], ['queso-rallado', 15]]),
  r('ravioles-salsa', 'Ravioles con salsa de tomate', 12, 1, P, false,
    'Ravioles en agua hirviendo con sal: 4–5 min.\nSalsa caliente y queso rallado.',
    [['ravioles', 250], ['salsa-tomate', 150], ['queso-rallado', 15]]),
]

export const foods = [...alimentosBase, ...alimentosNuevos, ...infusiones, ...alimentosCuarta]
export const recipes = [...recetasBase, ...recetasNuevas, ...recetasCuarta]
