// Cambios de la v2: no comí, bebidas y extras, Open Food Facts, sincronización con comidas afuera, buscador de recetas, validaciones
import { expect, test } from '@playwright/test'
import { API, APP, captura, contexto, escuchar, guardarSesion, hoyEnLaPagina, rest, sinErrores } from './apoyo.js'

const OFF = { count: 4, products: [
  { code: '7791337001234', product_name: 'Yogur bebible frutilla', brands: 'Ser, Danone', quantity: '185 g',
    nutriments: { 'energy-kcal_100g': 38, proteins_100g: 3.1, carbohydrates_100g: 5.2, fat_100g: 0.1 } },
  { code: '7790895000997', product_name: 'Coca-Cola Sabor Original', brands: 'Coca-Cola', quantity: '500 ml',
    nutriments: { energy_100g: 176, proteins_100g: 0, carbohydrates_100g: 10.6, fat_100g: 0 }, categories_tags: ['en:beverages'] },
  { code: '111', product_name: 'Producto sin datos', brands: 'X', nutriments: {} },
  { code: '222', product_name: 'Producto mal cargado', brands: 'X', nutriments: { 'energy-kcal_100g': 38000, proteins_100g: 3 } },
] }

test('no comí, bebidas y extras, comidas afuera y validaciones', async ({ browser }) => {
  const ctx = await contexto(browser, { sesion: true })
  const pg = await ctx.newPage()
  const errores = escuchar(pg, [], { dialogos: true })
  const pedidos = []
  await pg.route('**/cgi/search.pl*', (route) => {
    pedidos.push(route.request().url())
    return route.fulfill({ status: 200, contentType: 'application/json', headers: { 'Access-Control-Allow-Origin': '*' }, body: JSON.stringify(OFF) })
  })
  await pg.route('https://search.openfoodfacts.org/**', (route) => route.abort()) // el buscador nuevo, caído: tiene que responder el viejo
  await pg.goto(APP + '/')
  await pg.waitForSelector('text=¡Hola, Santi!')
  const hoy = await hoyEnLaPagina(pg)

  await test.step('no comí', async () => {
    const kcalAntes = await pg.locator('header .pill').innerText()
    await pg.click('button[aria-label="No comí merienda"]')
    await pg.waitForSelector('text=No comiste')
    await pg.waitForSelector('text=1 sin comer')
    expect(await pg.locator('header .pill').innerText()).toBe(kcalAntes)
    await captura(pg, 'v10_no_comi')
    await pg.click('button:has-text("Deshacer")')
    await pg.waitForSelector('button[aria-label="No comí merienda"]')
    expect(await pg.locator('text=sin comer').count()).toBe(0)
    await pg.click('button[aria-label="No comí merienda"]')
    await pg.waitForSelector('text=No comiste')
    await pg.click('button:has-text("Al final comí")')
    await pg.waitForSelector('text=Tu plato')
    await pg.click('button:has-text("Alimento")')
    await pg.fill('input[placeholder="Buscar alimento..."]', 'banana')
    await pg.locator('div.divide-y button:has-text("Banana")').first().click()
    await pg.click('button:has-text("Agregar a la merienda")')
    await pg.waitForSelector('text=¡Hola, Santi!')
    const filas = await rest(pg, 'log_entries', `&date=eq.${hoy}&meal=eq.merienda`)
    expect(filas.every((f) => !f.skipped) && filas.length === 1).toBe(true)
    expect(await pg.locator('text=No comiste').count()).toBe(0)
  })

  await test.step('bebidas y extras', async () => {
    await pg.click('button:has-text("Vaso de agua")')
    await pg.waitForSelector('text=Un vaso de agua anotado')
    await pg.waitForSelector('b:has-text("0,5 L")')
    const comidas = await pg.locator('p:has-text(" de 4")').innerText()
    await pg.locator('section:has-text("BEBIDAS Y ENTRE COMIDAS") button:has-text("Bebida")').click()
    await pg.waitForSelector('input[placeholder="Buscar bebida..."]')
    const todas = await pg.locator('div.divide-y > button').count()
    await pg.click('button:has-text("Con alcohol")')
    await pg.waitForTimeout(200)
    const con = (await pg.locator('div.divide-y > button').allInnerTexts()).map((t) => t.split('\n')[0])
    expect(!con.includes('Agua') && con.includes('Cerveza') && con.length === 17 && todas === 49).toBe(true)
    await captura(pg, 'v11_bebidas', false)
    await pg.click('button:has-text("Sin alcohol")')
    await pg.waitForTimeout(200)
    const sin = (await pg.locator('div.divide-y > button').allInnerTexts()).map((t) => t.split('\n')[0])
    expect(sin.includes('Agua') && !sin.includes('Cerveza')).toBe(true)
    await pg.click('button:has-text("Con alcohol")')
    await pg.locator('div.divide-y > button:has-text("Fernet con coca")').click()
    await pg.waitForSelector('text=Tu plato')
    expect(await pg.locator('button.bg-verde:has-text("Entre comidas")').count(), 'tiene que venir elegido Entre comidas').toBe(1)
    await pg.click('button:has-text("Vaso grande · 400 ml")')
    await pg.waitForSelector('text=320 kcal')
    await pg.fill('input[aria-label="Cantidad"]', '99999')
    await pg.waitForSelector('text=Como mucho 5.000 ml.')
    expect(await pg.locator('button:has-text("Agregar entre comidas")').isDisabled()).toBe(true)
    await pg.fill('input[aria-label="Cantidad"]', '0')
    await pg.waitForSelector('text=Tiene que ser mayor a cero.')
    await pg.click('button:has-text("Vaso · 250 ml")')
    await captura(pg, 'v12_registrar_bebida')
    await pg.click('button:has-text("Agregar entre comidas")')
    await pg.waitForSelector('text=¡Hola, Santi!')
    await pg.waitForSelector('text=Fernet con coca · 250 ml')
    expect(await pg.locator('b:has-text("0,5 L")').count(), 'el alcohol no tiene que contar como líquido').toBe(1)
    expect(await pg.locator('p:has-text(" de 4")').innerText(), 'una bebida no cuenta como comida').toBe(comidas)
    await captura(pg, 'v13_diario_extras')
  })

  await test.step('Open Food Facts (respuesta simulada)', async () => {
    await pg.goto(APP + '/registrar?comida=extra')
    await pg.waitForSelector('text=Tu plato')
    await pg.click('button:has-text("Alimento")')
    await pg.fill('input[placeholder="Buscar alimento..."]', 'ser frutilla')
    await pg.click('button:has-text("en Open Food Facts")')
    await pg.waitForSelector('text=Yogur bebible frutilla (Ser)')
    const offItems = await pg.locator('div.bg-teal-suave button').allInnerTexts()
    expect(offItems.length).toBe(2)
    await captura(pg, 'v14_off', false)
    await pg.click('button:has-text("Coca-Cola Sabor Original")')
    await pg.waitForSelector('text=Tu plato')
    await pg.waitForSelector('text=Coca-Cola Sabor Original')
    await pg.waitForSelector('text=Vaso · 250 ml')
    await rest(pg, 'foods', '&slug=is.null')
    // error de red
    await pg.unroute('**/cgi/search.pl*')
    await pg.route('**/cgi/search.pl*', (route) => route.abort())
    await pg.click('button:has-text("Alimento")')
    await pg.fill('input[placeholder="Buscar alimento..."]', 'algo raro')
    await pg.click('button:has-text("en Open Food Facts")')
    await pg.waitForSelector('text=Sigue buscando', { timeout: 15000 })
    await pg.waitForSelector('text=Open Food Facts no está respondiendo ahora', { timeout: 40000 })
    await pg.waitForSelector('button:has-text("Reintentar")')
    await pg.click('button[aria-label="Cerrar"]')
  })

  await test.step('sincronización con comidas afuera', async () => {
    await pg.goto(APP + '/plan')
    await pg.waitForSelector('text=Esta semana')
    await pg.click('button[aria-label="Semana siguiente"]')
    await pg.waitForSelector('text=Semana que viene')
    await pg.locator('button:has-text("CENA")').first().click()
    await pg.waitForSelector('text=Cena del lunes')
    await pg.locator('div.divide-y > button:has-text("Omelette de queso con ensalada")').click()
    await pg.waitForTimeout(400)
    const cenas = await rest(pg, 'plan', '&meal=eq.cena')
    const lunes = cenas.filter((f) => f.date > hoy).sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))[1]
    await pg.goto(APP + '/perfil')
    await pg.waitForSelector('text=Comidas fuera de casa')
    await pg.click('button[aria-label="Cena Lu"]')
    await pg.waitForSelector('text=para llevar')
    await captura(pg, 'v20_perfil_regla', false)
    const recetas = Object.fromEntries((await rest(pg, 'recipes', '')).map((r) => [r.id, r]))
    let fila = (await rest(pg, 'plan', `&meal=eq.cena&date=eq.${lunes.date}`))[0]
    expect(fila.away && recetas[fila.recipe_id].portable).toBeTruthy()
    await pg.waitForTimeout(2700)
    await pg.click('button[aria-label="Cena Lu"]')
    await pg.waitForSelector('text=a ser en casa')
    fila = (await rest(pg, 'plan', `&meal=eq.cena&date=eq.${lunes.date}`))[0]
    expect(fila.away).toBeFalsy()
    // toggle puntual en el plan con receta que no se puede llevar
    await pg.goto(APP + '/plan')
    await pg.waitForSelector('text=Esta semana')
    await pg.click('button[aria-label="Semana siguiente"]')
    await pg.waitForSelector('text=Semana que viene')
    await pg.locator('button:has-text("CENA")').first().click()
    await pg.waitForSelector('text=Cena del lunes')
    await pg.locator('div.divide-y > button:has-text("Omelette de queso con ensalada")').click()
    await pg.waitForTimeout(2700)
    const lunesCard = pg.locator('section:has-text("Lunes")').first()
    await lunesCard.locator('button[aria-label="Marcar fuera de casa"]').nth(3).click()
    await pg.waitForSelector('text=que se puede llevar')
    await captura(pg, 'v21_plan_afuera')
    // elegir a mano una que no es para llevar: queda avisado
    await pg.locator('button:has-text("CENA")').first().click()
    await pg.waitForSelector('text=primero van las recetas que se pueden llevar')
    await captura(pg, 'v22_elegir_afuera', false)
    await pg.locator('div.divide-y > button:has-text("Omelette de queso con ensalada")').click()
    await pg.waitForSelector('text=No es para llevar')
    // regla sin plan: el diario igual avisa
    await pg.click('button[aria-label="Semana anterior"]')
    await pg.waitForSelector('text=Esta semana')
    let dom = pg.locator('section:has-text("Domingo")').first()
    await dom.locator('button:has-text("ALMUERZO")').click()
    await pg.waitForSelector('text=Almuerzo del domingo')
    await pg.click('button:has-text("Dejar vacío")')
    await pg.waitForTimeout(400)
    // se borra la fila para que solo quede la regla
    const manana = new Date(hoy + 'T00:00:00Z')
    manana.setUTCDate(manana.getUTCDate() + 1)
    await pg.evaluate(async ([api, f]) => {
      const k = Object.keys(localStorage).find((x) => x.includes('auth-token'))
      const ses = JSON.parse(localStorage.getItem(k))
      await fetch(api + '/rest/v1/plan?meal=eq.almuerzo&date=eq.' + f, { method: 'DELETE', headers: { Authorization: 'Bearer ' + ses.access_token, apikey: 'test' } })
    }, [API, manana.toISOString().slice(0, 10)])
    await pg.goto(APP + '/')
    await pg.waitForSelector('text=PARA LLEVAR')
    expect(await pg.locator('section:has-text("PARA LLEVAR")').innerText()).toContain('no hay nada planificado')
    await captura(pg, 'v23_diario_llevar')
    await pg.goto(APP + '/plan')
    await pg.waitForSelector('text=Esta semana')
    dom = pg.locator('section:has-text("Domingo")').first()
    expect(await dom.locator('button[aria-label="Marcar en casa"]').count(), 'el plan tiene que mostrar afuera por la regla aunque no haya fila').toBe(1)
  })

  await test.step('recetas: buscador y filtro', async () => {
    await pg.goto(APP + '/recetas')
    await pg.waitForSelector('text=para cocinar')
    const total = await pg.locator('a.tarjeta').count()
    await pg.fill('input[placeholder^="Buscar receta"]', 'atun')
    await pg.waitForTimeout(200)
    const conAtun = await pg.locator('a.tarjeta').count()
    await pg.fill('input[placeholder^="Buscar receta"]', '')
    await pg.click('button:has-text("Para llevar")')
    await pg.waitForTimeout(200)
    const llevar = await pg.locator('a.tarjeta').count()
    expect(total >= 62 && 0 < conAtun && conAtun < total && 0 < llevar && llevar < total).toBe(true)
    await captura(pg, 'v30_recetas', false)
  })

  await test.step('validaciones del resto de los formularios', async () => {
    await pg.goto(APP + '/despensa')
    await pg.waitForSelector('input[placeholder="Buscar..."]')
    await pg.locator('button:has-text("unidades")').first().click()
    await pg.waitForSelector('text=¿Cuánto tenés?')
    await pg.locator('div.fixed input').fill('99999999')
    await pg.waitForSelector('text=Como mucho 2.000')
    expect(await pg.locator('div.fixed button:has-text("Guardar")').isDisabled()).toBe(true)
    await captura(pg, 'v40_stock_error', false)
    await pg.click('button[aria-label="Cerrar"]')
    await pg.goto(APP + '/compras')
    await pg.waitForSelector('text=Para comprar')
    await pg.click('button:has-text("Anotar")')
    await pg.fill('input[placeholder="Buscar alimento..."]', 'arroz')
    await pg.locator('div.divide-y > button').first().click()
    await pg.waitForTimeout(300)
    await pg.locator('button:has-text("Comprado")').first().click()
    await pg.locator('div.fixed input').nth(0).fill('0')
    await pg.waitForSelector('text=Tiene que ser mayor a cero.')
    expect(await pg.locator('button:has-text("Confirmar compra")').isDisabled()).toBe(true)
    await pg.locator('div.fixed input').nth(0).fill('1000')
    await pg.fill('#cp-precio', '12.3.4.5')
    expect(await pg.inputValue('#cp-precio')).toBe('12.34')
    await pg.click('button[aria-label="Cerrar"]')
    await pg.goto(APP + '/recetas/nueva')
    await pg.waitForSelector('text=Ingredientes')
    await pg.fill('#rn-min', '0')
    await pg.fill('#rn-rinde', '99')
    await pg.click('button:has-text("Guardar receta")')
    await pg.waitForSelector('text=Agregá al menos un ingrediente.')
    const errs = await pg.locator('p.text-rojo-texto').allInnerTexts()
    expect(errs.length >= 4).toBe(true)
    await captura(pg, 'v41_receta_errores')
    await pg.goto(APP + '/perfil')
    await pg.waitForSelector('text=Progreso')
    await pg.click('button:has-text("Anotar")')
    await pg.fill('#md-peso', '500')
    await pg.fill('#md-cintura', '10')
    await pg.waitForSelector('text=Tiene que estar entre 30 y 300.')
    await pg.waitForSelector('text=Tiene que estar entre 40 y 250.')
    expect(await pg.locator('div.fixed button:has-text("Guardar")').isDisabled()).toBe(true)
    await pg.fill('#md-fecha', '1990-01-01')
    await pg.waitForSelector('text=No puede ser anterior')
    await captura(pg, 'v42_medida_errores', false)
    await pg.click('button[aria-label="Cerrar"]')
    // editar perfil: lo que pasó en la captura (altura 170000) ya no se puede
    await pg.click('button:has-text("Editar")')
    await pg.waitForSelector('#pf-altura')
    await pg.fill('#pf-altura', '')
    await pg.click('#pf-altura')
    await pg.keyboard.type('170000')
    expect(await pg.inputValue('#pf-altura')).toBe('170')
    await pg.click('button[aria-label="Cerrar"]')
    // alimento nuevo con valores imposibles
    await pg.goto(APP + '/registrar')
    await pg.waitForSelector('text=Tu plato')
    await pg.click('button:has-text("Alimento")')
    await pg.click('button:has-text("Crear alimento nuevo")')
    await pg.click('button:has-text("Guardar")')
    await pg.waitForSelector('text=Completá este dato.')
    await pg.fill('#na-nombre', 'Prueba')
    await pg.fill('#na-kcal', '950')
    await pg.waitForSelector('text=Tiene que estar entre 0 y 900.')
    await pg.fill('#na-kcal', '100')
    await pg.fill('#na-prot', '60')
    await pg.waitForSelector('text=Es mucha proteína para esas calorías')
    await pg.fill('#na-kcal', '400')
    await pg.fill('#na-prot', '40')
    await pg.fill('#na-carb', '50')
    await pg.fill('#na-grasa', '30')
    await pg.waitForSelector('text=no pueden sumar más de 100')
    await captura(pg, 'v43_alimento_errores', false)
  })

  await guardarSesion(ctx)
  await ctx.close()
  sinErrores(errores)
})
