// Acceso con código, contraseñas, recuperar, descargar datos y borrar cuenta (con una cuenta aparte). Después, con la sesión de las pruebas anteriores:
// bebidas con medidas y azúcar, líquido, recetas (favoritas/ocultas/editar), mis alimentos, recientes y resumen. Deja la sesión para las que siguen.
import fs from 'node:fs'
import { expect, test } from '@playwright/test'
import { API, APP, aviso, captura, contexto, escuchar, guardarSesion, hoyEnLaPagina, rest, simulador, sinErrores } from './apoyo.js'

test('cuenta con código, bebidas, recetas y resumen', async ({ browser }) => {
  const errores = []
  let ctx = await contexto(browser)
  let pg = await ctx.newPage()
  escuchar(pg, errores, { dialogos: true })
  let hoy

  // =================== ACCESO ===================
  await test.step('acceso: mail mal tipeado y descartable', async () => {
    await pg.goto(APP + '/')
    await pg.waitForSelector('text=Crear cuenta')
    await captura(pg, 'w01_acceso', false)
    await pg.click('button:has-text("Crear cuenta") >> nth=0')
    await pg.waitForSelector('#clave2')
    // mail mal tipeado y descartable
    await pg.fill('#email', 'ana@gmial.com')
    await pg.waitForSelector('text=¿Quisiste decir')
    await pg.click('button:has-text("¿Quisiste decir")')
    expect(await pg.inputValue('#email')).toBe('ana@gmail.com')
    await pg.fill('#email', 'ana@yopmail.com')
    await pg.fill('#clave', 'Zx9kLm2p')
    await pg.fill('#clave2', 'Zx9kLm2p')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=los temporales no sirven')
  })

  await test.step('acceso: contraseñas fáciles y el ojito', async () => {
    // contraseñas fáciles
    await pg.fill('#email', 'anita.perez@codigo.test')
    for (const mala of ['password1', 'Qwerty123', 'Abc12345', 'AnitaPerez1', '12345678', 'Boca2024', 'Cordoba2026']) {
      await pg.fill('#clave', mala)
      await pg.fill('#clave2', mala)
      await pg.click('form button[type=submit]')
      await pg.waitForSelector('text=todavía no cumple los requisitos')
    }
    // ojito
    expect(await pg.getAttribute('#clave', 'type')).toBe('password')
    await pg.click('button[aria-label="Ver la contraseña"] >> nth=0')
    expect(await pg.getAttribute('#clave', 'type')).toBe('text')
    await captura(pg, 'w02_crear_clave', false)
    await pg.click('button[aria-label="Ocultar la contraseña"]')
    expect(await pg.getAttribute('#clave', 'type')).toBe('password')
    await pg.fill('#clave', 'MiTupper7x')
    await pg.fill('#clave2', 'MiTupper7y')
    await pg.waitForSelector('text=Todavía no coinciden')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Las dos contraseñas no coinciden')
  })

  await test.step('acceso: términos sin sesión', async () => {
    // términos sin sesión
    await pg.click('a:has-text("Términos")')
    await pg.waitForSelector('text=No reemplaza a un profesional')
    await captura(pg, 'w03_terminos', false)
    await pg.click('a:has-text("Ver Política de privacidad")')
    await pg.waitForSelector('text=Qué datos guardamos')
  })

  await test.step('acceso: crear la cuenta y confirmarla con el código', async () => {
    await pg.goto(APP + '/')
    await pg.click('button:has-text("Crear cuenta") >> nth=0')
    await pg.fill('#email', 'ana@codigo.test')
    await pg.fill('#clave', 'MiTupper7x')
    await pg.fill('#clave2', 'MiTupper7x')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Confirmá tu email')
    await captura(pg, 'w04_codigo', false)
    expect(await pg.locator('button:has-text("Podés pedir otro en")').isDisabled()).toBe(true)
    await pg.fill('#codigo', '12ab34')
    expect(await pg.inputValue('#codigo')).toBe('1234')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=/Escribí el código completo|El código tiene 6 dígitos/')
    await pg.fill('#codigo', '000000')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=El código no es correcto o ya venció')
    await pg.fill('#codigo', '123456')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Armemos tu perfil')
  })

  await test.step('acceso: menor de 18, sin recorte', async () => {
    // menor de 18: sin recorte
    await pg.fill('#pf-nombre', 'Ana')
    await pg.fill('#pf-nac', '2010-05-01')
    await pg.fill('#pf-altura', '160')
    await pg.fill('#pf-peso', '60')
    await pg.fill('#pf-meta', '50')
    await pg.waitForSelector('text=Como tenés menos de 18')
    const menor = await pg.inputValue('#pf-kcal')
    await pg.fill('#pf-nac', '2000-05-01')
    await pg.waitForTimeout(200)
    const adulto = await pg.inputValue('#pf-kcal')
    expect(parseInt(menor, 10)).toBeGreaterThan(parseInt(adulto, 10))
    expect(await pg.locator('text=Como tenés menos de 18').count()).toBe(0)
    await pg.click('button:has-text("Empezar")')
    await pg.waitForSelector('text=¡Hola, Ana!')
  })

  await test.step('acceso: cuenta ya registrada', async () => {
    // cuenta ya registrada
    await pg.goto(APP + '/perfil')
    await pg.click('button:has-text("Cerrar sesión")')
    await pg.waitForSelector('text=Iniciar sesión')
    await pg.click('button:has-text("Crear cuenta") >> nth=0')
    await pg.fill('#email', 'ana@codigo.test')
    await pg.fill('#clave', 'OtraClave9z')
    await pg.fill('#clave2', 'OtraClave9z')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Ya hay una cuenta con ese email')
  })

  await test.step('acceso: recuperar contraseña', async () => {
    // recuperar contraseña
    await pg.click('button:has-text("Iniciar sesión")')
    await pg.click('button:has-text("Olvidé mi contraseña")')
    await pg.waitForSelector('text=Recuperar contraseña')
    await pg.fill('#email', 'ana@codigo.test')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Contraseña nueva')
    await captura(pg, 'w05_recuperar', false)
    await pg.fill('#codigo', '123456')
    await pg.fill('#clave', 'MiTupper7x')
    await pg.fill('#clave2', 'MiTupper7x')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=tiene que ser distinta a la anterior')
    expect(await pg.locator('#codigo').count(), 'tiene que seguir en la pantalla de contraseña').toBe(0)
    expect(await pg.locator('text=¡Hola').count(), 'tiene que seguir en la pantalla de contraseña').toBe(0)
    await pg.fill('#clave', 'NuevaClave8k')
    await pg.fill('#clave2', 'NuevaClave8k')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=¡Hola, Ana!')
    await simulador('/auth/v1/_mock', {})
  })

  await test.step('acceso: cuenta sin confirmar que intenta entrar', async () => {
    // cuenta sin confirmar que intenta entrar
    await pg.goto(APP + '/perfil')
    await pg.click('button:has-text("Cerrar sesión")')
    await pg.waitForSelector('text=Iniciar sesión')
    await pg.click('button:has-text("Crear cuenta") >> nth=0')
    await pg.fill('#email', 'beto@codigo.test')
    await pg.fill('#clave', 'OtroCodigo5m')
    await pg.fill('#clave2', 'OtroCodigo5m')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Confirmá tu email')
    await pg.click('button:has-text("Volver")')
    await pg.fill('#email', 'beto@codigo.test')
    await pg.fill('#clave', 'OtroCodigo5m')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Te falta confirmar el email')
    await pg.fill('#codigo', '123456')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=Armemos tu perfil')
  })

  await test.step('acceso: descargar los datos y borrar la cuenta de Ana', async () => {
    // borrar la cuenta de Ana
    await pg.click('button:has-text("Salir")')
    await pg.waitForSelector('text=Iniciar sesión')
    await pg.fill('#email', 'ana@codigo.test')
    await pg.fill('#clave', 'NuevaClave8k')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=¡Hola, Ana!')
    await pg.goto(APP + '/perfil')
    await pg.waitForSelector('text=Borrar mi cuenta')
    const [dl] = await Promise.all([pg.waitForEvent('download'), pg.click('button:has-text("Descargar mis datos")')])
    const datos = JSON.parse(fs.readFileSync(await dl.path(), 'utf8'))
    expect(datos.email).toBe('ana@codigo.test')
    expect(datos.perfil.name).toBe('Ana')
    expect(datos.medidas.length).toBe(1)
    await pg.click('button:has-text("Borrar mi cuenta")')
    await pg.waitForSelector('text=No se puede deshacer')
    await captura(pg, 'w06_borrar', false)
    expect(await pg.locator('button:has-text("Borrar todo para siempre")').isDisabled()).toBe(true)
    await pg.fill('#bc-confirmar', 'borrar')
    await pg.click('button:has-text("Borrar todo para siempre")')
    await pg.waitForSelector('text=Iniciar sesión')
    await pg.fill('#email', 'ana@codigo.test')
    await pg.fill('#clave', 'NuevaClave8k')
    await pg.click('form button[type=submit]')
    await pg.waitForSelector('text=El email o la contraseña no coinciden')
    await ctx.close()
  })

  // =================== FUNCIONES NUEVAS (usuario principal) ===================
  await test.step('usuario principal: el diario', async () => {
    ctx = await contexto(browser, { sesion: true })
    pg = await ctx.newPage()
    escuchar(pg, errores, { dialogos: true })
    await pg.goto(APP + '/')
    await pg.waitForSelector('text=¡Hola, Santi!')
    hoy = await hoyEnLaPagina(pg)
    expect(await pg.locator('text=g carbohidratos').count()).toBe(1)
    expect(await pg.locator('text=g grasas').count()).toBe(1)
    // líquido antes
    await pg.locator('span:has(> b)').filter({ hasText: ' L / ' }).innerText()
  })

  await test.step('mate: medidas, termo y azúcar', async () => {
    await pg.locator('section:has-text("BEBIDAS Y ENTRE COMIDAS") button:has-text("Bebida")').click()
    await pg.fill('input[placeholder="Buscar bebida..."]', 'mate')
    await pg.locator('div.divide-y > button').filter({ hasText: 'Mate' }).first().click()
    await pg.waitForSelector('text=Tu plato')
    await pg.inputValue('input[aria-label="Cantidad"]')
    await pg.selectOption('select[aria-label="Tamaño del termo"]', '1200')
    await pg.waitForSelector('button:has-text("Medio termo · 600 ml")')
    await pg.click('button:has-text("Medio termo · 600 ml")')
    expect(await pg.inputValue('input[aria-label="Cantidad"]')).toBe('600')
    await pg.click('button:has-text("Azúcar")')
    await pg.waitForSelector('text=cucharadita en total · 20 kcal')
    await pg.click('button[aria-label="Más azúcar"]')
    await pg.click('button[aria-label="Más azúcar"]')
    await pg.waitForSelector('text=cucharaditas en total · 40 kcal')
    await pg.waitForSelector('text=40 kcal')
    await captura(pg, 'w10_mate')
    await pg.click('button:has-text("Agregar entre comidas")')
    await pg.waitForSelector('text=¡Hola, Santi!')
    await pg.waitForSelector('text=Mate · 600 ml')
    await pg.waitForSelector('text=Azúcar')
    // líquido después del mate
    await pg.locator('span:has(> b)').filter({ hasText: ' L / ' }).innerText()
    const az = (await rest(pg, 'log_entries', `&date=eq.${hoy}&meal=eq.extra`)).filter((r) => r.name === 'Azúcar')
    expect(az.length).toBeGreaterThan(0)
    expect(az[0].qty).toBe(10)
    expect(az[0].kcal).toBe(40)
    const perfil = (await rest(pg, 'profiles'))[0]
    expect(perfil.thermos_ml).toBe(1200)
    // recientes: el mate vuelve con su cantidad y su azúcar
    await pg.goto(APP + '/registrar?comida=extra')
    await pg.waitForSelector('text=Lo que más registrás')
    await pg.locator('p:has-text("Lo que más registrás") + div button').filter({ hasText: 'Mate' }).click()
    expect(await pg.inputValue('input[aria-label="Cantidad"]')).toBe('600')
    await pg.waitForSelector('text=cucharaditas en total · 40 kcal')
    await pg.click('button[aria-label="Quitar"]')
    // café: pocillo, taza, jarro + edulcorante
    await pg.click('button:has-text("Bebida")')
    await pg.fill('input[placeholder="Buscar bebida..."]', 'café negro')
    await pg.locator('div.divide-y > button').first().click()
    await pg.inputValue('input[aria-label="Cantidad"]')
    await pg.click('button:has-text("Edulcorante")')
    await pg.waitForSelector('text=El edulcorante no suma calorías')
    await pg.click('button[aria-label="Quitar"]')
    // cerveza y vino
    for (const bebida of ['Cerveza', 'Vino']) {
      await pg.click('button:has-text("Bebida")')
      await pg.fill('input[placeholder="Buscar bebida..."]', bebida)
      await pg.locator('div.divide-y > button').first().click()
      expect(await pg.locator('text=Endulzado con').count()).toBe(0)
      await pg.click('button[aria-label="Quitar"]')
    }
    // repetir lo de ayer
    const ayer = new Date(Date.parse(hoy + 'T00:00:00Z') - 24 * 60 * 60 * 1000).toISOString().slice(0, 10)
    await pg.evaluate(async ([api, ayer]) => {
      const k = Object.keys(localStorage).find((x) => x.includes('auth-token'))
      const ses = JSON.parse(localStorage.getItem(k))
      const h = { Authorization: 'Bearer ' + ses.access_token, apikey: 'test', 'Content-Type': 'application/json' }
      const foods = await (await fetch(api + '/rest/v1/foods?select=*', { headers: h })).json()
      const f = (s) => foods.find((x) => x.slug === s)
      const filas = [['cena', 'arroz', 70, 252, 4.9], ['cena', 'huevo', 2, 150, 12.5], ['almuerzo', 'fideos', 100, 355, 12]].map(([meal, s, qty, kcal, protein]) => ({ user_id: ses.user.id, date: ayer, meal, name: f(s).name, food_id: f(s).id, qty, kcal, protein, carbs: 0, fat: 0 }))
      await fetch(api + '/rest/v1/log_entries', { method: 'POST', headers: h, body: JSON.stringify(filas) })
    }, [API, ayer])
    await pg.goto(APP + '/registrar?comida=cena')
    await pg.waitForSelector('text=Repetir lo de ayer')
    await pg.click('button:has-text("Repetir lo de ayer")')
    await pg.waitForSelector('text=2 cosas')
    await captura(pg, 'w11_repetir')
  })

  await test.step('objetivo de líquido propio', async () => {
    await pg.goto(APP + '/perfil')
    await pg.waitForSelector('text=Objetivos por día')
    await pg.click('button:has-text("Editar")')
    await pg.fill('#pf-liquido', '3')
    await pg.click('div.fixed button:has-text("Guardar")')
    await pg.waitForSelector('text=Perfil guardado')
    await pg.waitForSelector('p.text-teal-oscuro:has-text("3 L")')
    await captura(pg, 'w12_perfil')
  })

  await test.step('recetas: favorita, ocultar, mostrar', async () => {
    await pg.goto(APP + '/recetas')
    await pg.waitForSelector('text=para cocinar')
    const total = await pg.locator('a.tarjeta').count()
    await pg.click('button[aria-label="Marcar Fideos con atún como favorita"]')
    await pg.waitForSelector('button[aria-label="Quitar Fideos con atún de favoritas"]')
    await pg.click('button:has-text("Favoritas")')
    await pg.waitForTimeout(200)
    expect(await pg.locator('a.tarjeta').count()).toBe(1)
    expect(await pg.locator('button:has-text("Ocultas")').count()).toBe(0)
    const planeadas = (await rest(pg, 'plan')).filter((r) => r.date >= hoy && r.recipe_id)
    const recetas = new Map((await rest(pg, 'recipes')).map((r) => [r.id, r]))
    const ultima = planeadas[planeadas.length - 1].recipe_id
    const nombre = recetas.get(ultima).name
    await pg.click('button:has-text("Todas")')
    await pg.fill('input[placeholder^="Buscar receta"]', nombre)
    await pg.locator('a.tarjeta').first().click()
    await pg.waitForSelector('text=Ingredientes')
    await pg.click('button:has-text("No me gusta")')
    await pg.waitForSelector('text=Receta oculta')
    await aviso(pg)
    await pg.waitForSelector('text=para cocinar')
    expect(await pg.locator('a.tarjeta').count()).toBe(total - 1)
    const vacias = (await rest(pg, 'plan')).filter((r) => r.date >= hoy && r.recipe_id === ultima)
    expect(vacias).toEqual([])
    await pg.click('button:has-text("Ocultas")')
    await pg.waitForSelector('button:has-text("Mostrar")')
    await captura(pg, 'w13_ocultas', false)
    // el plan no la vuelve a elegir
    await pg.goto(APP + '/plan')
    await pg.waitForSelector('text=Esta semana')
    for (let i = 0; i < 2; i++) {
      if (await pg.locator('button:has-text("Armar con lo que tengo")').isEnabled()) {
        await pg.click('button:has-text("Armar con lo que tengo")')
        await pg.waitForSelector('text=Semana completa')
      }
      await pg.click('button[aria-label="Semana siguiente"]')
      await pg.waitForTimeout(300)
    }
    const otra = (await rest(pg, 'plan')).filter((r) => r.date >= hoy && r.recipe_id === ultima)
    expect(otra, 'el plan volvió a elegir una receta oculta').toEqual([])
    await pg.goto(APP + '/recetas')
    await pg.click('button:has-text("Ocultas")')
    await pg.click('button:has-text("Mostrar")')
    await pg.waitForSelector('text=No tenés recetas ocultas')
    await pg.click('button:has-text("Todas")')
    await pg.waitForTimeout(200)
    expect(await pg.locator('a.tarjeta').count()).toBe(total)
  })

  await test.step('receta propia: crear, editar, borrar', async () => {
    await pg.goto(APP + '/recetas/nueva')
    await pg.waitForSelector('text=Ingredientes')
    await pg.fill('#rn-nombre', 'Prueba para editar')
    await pg.click('button:has-text("Agregar")')
    await pg.fill('input[placeholder="Buscar alimento..."]', 'arroz')
    await pg.locator('div.divide-y > button').first().click()
    await pg.click('button:has-text("Guardar receta")')
    await pg.waitForSelector('button:has-text("Editar")')
    await pg.click('button:has-text("Editar")')
    await pg.waitForSelector('text=Editar receta')
    expect(await pg.inputValue('#rn-nombre')).toBe('Prueba para editar')
    await pg.fill('#rn-nombre', 'Arroz editado')
    await pg.locator('input[aria-label^="Cantidad de"]').fill('150')
    await pg.click('button:has-text("Agregar")')
    await pg.fill('input[placeholder="Buscar alimento..."]', 'huevo')
    await pg.locator('div.divide-y > button').first().click()
    await pg.click('button:has-text("Guardar cambios")')
    await pg.waitForSelector('h2:has-text("Arroz editado")')
    await captura(pg, 'w14_receta_editada')
    const propia = (await rest(pg, 'recipes')).filter((r) => r.name === 'Arroz editado')[0]
    await rest(pg, 'recipe_items', `&recipe_id=eq.${propia.id}`)
    await pg.click('button:has-text("Borrar")')
    await pg.waitForSelector('text=¿Borrar esta receta?')
    await pg.click('[role=alertdialog] button:has-text("Borrar")')
    await pg.waitForSelector('text=para cocinar')
  })

  await test.step('mis alimentos', async () => {
    await pg.goto(APP + '/alimentos')
    await pg.waitForSelector('text=Coca-Cola Sabor Original')
    await pg.click('button[aria-label="Editar Coca-Cola Sabor Original"]')
    await pg.fill('#na-kcal', '44')
    await pg.click('div.fixed button:has-text("Guardar")')
    await pg.waitForSelector('text=44 kcal')
    await pg.click('button:has-text("Crear alimento")')
    await pg.fill('#na-nombre', 'Licor casero')
    await pg.selectOption('#na-unidad', 'ml')
    await pg.selectOption('#na-cat', 'Bebidas')
    await pg.fill('#na-kcal', '250')
    await pg.check('text=Tiene alcohol')
    await pg.click('div.fixed button:has-text("Guardar")')
    await pg.waitForSelector('text=Licor casero')
    await captura(pg, 'w15_mis_alimentos')
    const lic = (await rest(pg, 'foods', '&slug=is.null')).filter((f) => f.name === 'Licor casero')[0]
    expect(lic.alcohol).toBe(true)
    await pg.click('button[aria-label="Borrar Licor casero"]')
    await pg.waitForSelector('text=¿Borrar Licor casero?')
    await pg.click('[role=alertdialog] button:has-text("Borrar")')
    await pg.waitForSelector('text=Alimento borrado')
    expect(await pg.locator('text=Licor casero').count()).toBe(0)
  })

  await test.step('compras con el gasto del mes', async () => {
    await pg.goto(APP + '/compras')
    await pg.waitForSelector('text=Para comprar')
    await pg.waitForSelector('text=Gastaste en')
    await captura(pg, 'w16_compras')
  })

  await test.step('resumen semanal', async () => {
    await pg.goto(APP + '/')
    await pg.click('a:has-text("Ver el resumen de la semana")')
    await pg.waitForSelector('text=CÓMO VENÍS')
    await pg.locator('section:has-text("CÓMO VENÍS")').innerText()
    // día elegido
    await pg.locator('div.bg-campo:has(b)').innerText()
    await captura(pg, 'w17_resumen')
    await pg.locator('svg[role=img] g').nth(4).click()
    await pg.waitForTimeout(200)
    // otro día
    await pg.locator('div.bg-campo:has(b)').innerText()
    await pg.goto(APP + '/')
    await pg.waitForSelector('text=¡Hola, Santi!')
    await captura(pg, 'w18_diario')
  })

  await guardarSesion(ctx)
  await ctx.close()
  sinErrores(errores)
})
